"""Who is Who domain — /api/v2/who-is-who/departments/* and /api/v2/who-is-who/officials/*.

LIVE — copy-pasted verbatim from the v1 surface (api.v1.who_is_who); the body delegates
to the v1 handlers so there is exactly one implementation during the v1+v2
coexistence period. Only the in-description example URLs are rehomed to
/api/v2/who-is-who/*.

Generated by scripts/_gen_v2_who_is_who.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import who_is_who as _v1
from api.v1.who_is_who import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


from api.v1.who_is_who import _DESC  # noqa: F401 - used in decorators

departments_router = APIRouter(prefix="/departments", tags=["v2-who-is-who-departments"])
officials_router = APIRouter(prefix="/officials", tags=["v2-who-is-who-officials"])


@departments_router.get(
    "",
    response_model=PaginatedResponse[WhoIsWhoDepartmentItem],
    summary="EU departments — organisational units across all EU institutions",
    description=_DESC(
        "Returns the organisational units of the EU institutions — Directorates-General, directorates, units, cabinets, services — from the official interinstitutional directory, each with its code and the number of officials listed.",
        "To map the EU's organisational structure, resolve a department code, or find which unit owns a policy area.",
        "- `q` — substring search over department name / code.\n- `mnemonic` — exact department code (e.g. AGRI).\n- `limit` (default 25, max 100), `page`.",
        "A `PaginatedResponse[WhoIsWhoDepartmentItem]`.",
        "GET /api/v2/who-is-who/departments?q=agriculture",
    ),
)
async def list_departments(
    request: Request,
    q: Optional[str] = Query(None),
    mnemonic: Optional[str] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[WhoIsWhoDepartmentItem]:
    return await _v1.list_departments(request=request, q=q, mnemonic=mnemonic, limit=limit, page=page, user=user, db=db)


@departments_router.get(
    "/{item_id}",
    response_model=WhoIsWhoDepartmentItem,
    summary="One EU department by id",
    description="Fetch a single EU department by its Brubru UUID. 404 with `reason_code: not_found` if absent.",
)
async def get_department(item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db)) -> WhoIsWhoDepartmentItem:
    return await _v1.get_department(item_id=item_id, user=user, db=db)


@officials_router.get(
    "",
    response_model=PaginatedResponse[WhoIsWhoOfficialItem],
    summary="EU officials — named officials with position and department",
    description=_DESC(
        "Returns named EU officials from the official interinstitutional directory — each with their position (job title) and the department they belong to, across all EU institutions.",
        "To find who holds a position (e.g. the Director-General of a DG), or to list the officials of a department.",
        "- `q` — substring search over the official's name.\n- `department` — substring match on the department name.\n- `mnemonic` — exact department code.\n- `position` — substring match on the position / job title.\n- `limit` (default 25, max 100), `page`.",
        "A `PaginatedResponse[WhoIsWhoOfficialItem]`.",
        "GET /api/v2/who-is-who/officials?position=Director-General&mnemonic=AGRI",
    ),
)
async def list_officials(
    request: Request,
    q: Optional[str] = Query(None),
    department: Optional[str] = Query(None),
    mnemonic: Optional[str] = Query(None),
    position: Optional[str] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[WhoIsWhoOfficialItem]:
    return await _v1.list_officials(request=request, q=q, department=department, mnemonic=mnemonic, position=position, limit=limit, page=page, user=user, db=db)


@officials_router.get(
    "/{item_id}",
    response_model=WhoIsWhoOfficialItem,
    summary="One EU official by id",
    description="Fetch a single EU official by its Brubru UUID. 404 with `reason_code: not_found` if absent.",
)
async def get_official(item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db)) -> WhoIsWhoOfficialItem:
    return await _v1.get_official(item_id=item_id, user=user, db=db)
