"""Funding & Tenders domain — /api/v2/funding/ft-calls-for-proposals/* and /api/v2/funding/ft-calls-for-tenders/* and /api/v2/funding/ft-funded-projects/*.

LIVE — copy-pasted verbatim from the v1 surface (api.v1.funding_tenders_collections); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/funding/*.

Generated by scripts/_gen_v2_funding.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import funding_tenders_collections as _v1
from api.v1.funding_tenders_collections import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


calls_router = APIRouter(prefix="/ft-calls-for-proposals", tags=["v2-funding-ft-calls-for-proposals"])
tenders_router = APIRouter(prefix="/ft-calls-for-tenders", tags=["v2-funding-ft-calls-for-tenders"])
projects_router = APIRouter(prefix="/ft-funded-projects", tags=["v2-funding-ft-funded-projects"])


@calls_router.get(
    "",
    response_model=PaginatedResponse[FtCallProposalItem],
    summary="EU funding calls for proposals — Horizon Europe, Digital Europe, LIFE, EU4Health, Creative Europe, Erasmus+",
    description="""**What it does**
Returns calls for grant proposals from the EU Funding & Tenders Portal — the canonical entry point for Commission-managed grant programmes (Horizon Europe, Digital Europe, LIFE, EU4Health, Creative Europe, Erasmus+, EIC, AMIF, ISF, BMVI, JTM, etc.). Each row carries the topic_id (the EU's identifier, e.g. `HORIZON-CL5-2026-D2-01-01`), the framework programme, the type of action (RIA / IA / CSA / CoFund / etc.), the status (open / forthcoming / closed / under-evaluation), the deadline, the budget, and a body composed from title + objective + scope.

**When to use it**
For consultancies, universities, research orgs, and SMEs looking for non-procurement funding. Combine with `/api/v1/funded-projects` to see "what's been funded under this programme" → "what's currently open". Default ordering puts most recent deadlines first so partners land on actionable opportunities.

**Input**
- `framework_programme` — substring match (e.g. `Horizon Europe`, `Digital Europe`, `LIFE`).
- `status` — `open` / `forthcoming` / `closed` / `under-evaluation`.
- `type_of_action` — substring (e.g. `RIA`, `IA`, `CSA`).
- `q` — substring search on title + description.
- `deadline_from`, `deadline_to` — deadline window (use to find calls closing in your bidding-feasible range).
- `limit` (default 50, max 100), `page` (1-indexed).
- `body_threshold` — minimum body chars for `has_body=true`.

**Try it**
```
GET /api/v1/calls-for-proposals?framework_programme=Horizon&status=open
GET /api/v1/calls-for-proposals?q=AI&deadline_from=2026-06-01
```

**You get back**
A `PaginatedResponse[FtCallProposalItem]` envelope. Each item carries `topic_id`, `title`, `framework_programme`, `type_of_action`, `status`, `deadline`, `budget`, `description`, `objective`, `scope`, `expected_outcome`, `participation_eligibility`, `source_url`, `last_updated`, body fields + the 5 envelope-level datapoints (`public_url` = the F&T Portal opportunity page).

**Data freshness**
Synced once per day at 04:00 UTC (daily tier) from ec.europa.eu/info/funding-tenders/opportunities/portal/. New calls open / close throughout the day; daily sync catches them. is_test=True seed rows are filtered out at query time.""",
)
async def list_calls_for_proposals(
    request: Request,
    framework_programme: Optional[str] = Query(None),
    status: Optional[str] = Query(None, description="open | forthcoming | closed | under-evaluation"),
    type_of_action: Optional[str] = Query(None),
    q: Optional[str] = Query(None, description="Substring match on title/description"),
    deadline_from: Optional[date] = Query(None),
    deadline_to: Optional[date] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[FtCallProposalItem]:
    return await _v1.list_calls_for_proposals(request=request, framework_programme=framework_programme, status=status, type_of_action=type_of_action, q=q, deadline_from=deadline_from, deadline_to=deadline_to, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)


@calls_router.get(
    "/{topic_id:path}",
    response_model=FtCallProposalItem,
    summary="Look up one funding call for proposals by its EU topic_id",
    description="""**What it does**
Fetches a single call for proposals by its EU topic identifier. Returns the same shape as the list endpoint, with the full body composed from title + objective + scope + expected outcome.

**When to use it**
After locating a call via the list endpoint, use this for the full record — particularly when you want to embed call details in a bid-tracker or render the scope text in a UI.

**Input**
- `topic_id` (path) — the EU's identifier, e.g. `HORIZON-CL5-2026-D2-01-01`. The `:path` matcher accepts hyphens + dots verbatim, no URL-encoding needed.

**Try it**
```
GET /api/v1/calls-for-proposals/HORIZON-CL5-2026-D2-01-01
```

**You get back**
A single `FtCallProposalItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found` (also returned if the row is flagged `is_test=true`).

**Data freshness**
Same as the list endpoint — daily 04:00 UTC sync from the F&T Portal.""",
)
async def get_call_for_proposals(
    topic_id: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> FtCallProposalItem:
    return await _v1.get_call_for_proposals(topic_id=topic_id, body_threshold=body_threshold, user=user, db=db)


@tenders_router.get(
    "",
    response_model=PaginatedResponse[FtCallTenderItem],
    summary="EU public-procurement tenders from the F&T Portal — distinct from the /tenders TED view",
    description="""**What it does**
Returns calls for tenders (public procurement) published by EU institutions and agencies on the Funding & Tenders Portal. Each row carries the tender_reference, the contracting authority (which institution / agency is buying), the contract type, the status, the deadline, the budget, and a body composed from title + description.

**When to use it**
For service providers, consultancies, and contractors bidding on EU institutional procurement. This is the F&T Portal-specific view; for the broader TED (Tenders Electronic Daily) feed which covers Member State buyers as well, see `/api/v2/funding/tenders`. The two surfaces overlap for some Commission contracts but TED is the authoritative legal source.

**Input**
- `contracting_authority` — substring (e.g. `European Commission`, `Frontex`, `EMA`).
- `status` — F&T tender status enum.
- `contract_type` — substring (e.g. `services`, `supplies`, `works`).
- `q` — substring search on title + description.
- `deadline_from`, `deadline_to` — submission window.
- `limit` (default 50, max 100), `page` (1-indexed).
- `body_threshold` — minimum body chars for `has_body=true`.

**Try it**
```
GET /api/v1/calls-for-tenders?contracting_authority=Frontex&status=open
GET /api/v1/calls-for-tenders?q=consultancy&deadline_from=2026-06-01
```

**You get back**
A `PaginatedResponse[FtCallTenderItem]` envelope. Each item carries `tender_reference`, `title`, `contracting_authority`, `contract_type`, `status`, `deadline`, `budget`, `description`, `source_url`, `last_updated`, body fields + the 5 envelope-level datapoints (`public_url` = the F&T Portal tender page).

**Data freshness**
Synced once per day at 04:00 UTC (daily tier) from ec.europa.eu/info/funding-tenders/opportunities/portal/. is_test=True seed rows are filtered out at query time.""",
)
async def list_calls_for_tenders(
    request: Request,
    contracting_authority: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    contract_type: Optional[str] = Query(None),
    q: Optional[str] = Query(None),
    deadline_from: Optional[date] = Query(None),
    deadline_to: Optional[date] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[FtCallTenderItem]:
    return await _v1.list_calls_for_tenders(request=request, contracting_authority=contracting_authority, status=status, contract_type=contract_type, q=q, deadline_from=deadline_from, deadline_to=deadline_to, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)


@tenders_router.get(
    "/{tender_reference:path}",
    response_model=FtCallTenderItem,
    summary="Look up one F&T Portal tender by its tender_reference",
    description="""**What it does**
Fetches a single F&T Portal call for tenders by its EU tender_reference. Returns the same shape as the list endpoint.

**When to use it**
After locating a tender via the list endpoint, use this for the full record. The `:path` matcher accepts the reference verbatim including any slashes / dots / hyphens.

**Input**
- `tender_reference` (path) — the EU's tender identifier as published on the F&T Portal.

**Try it**
```
GET /api/v1/calls-for-tenders/<tender_reference>
```

**You get back**
A single `FtCallTenderItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — daily 04:00 UTC sync from the F&T Portal.""",
)
async def get_call_for_tenders(
    tender_reference: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> FtCallTenderItem:
    return await _v1.get_call_for_tenders(tender_reference=tender_reference, body_threshold=body_threshold, user=user, db=db)


@projects_router.get(
    "",
    response_model=PaginatedResponse[FtFundedProjectItem],
    summary="EU grant-funded projects — active + completed results (Horizon Europe, FP7, H2020, sectoral programmes)",
    description="""**What it does**
Returns EU-funded grant projects from the Funding & Tenders Portal — both active and completed projects across all framework programmes (Horizon Europe, Horizon 2020, FP7, sectoral programmes like Digital Europe, EU4Health, LIFE, Creative Europe). Each row carries the project_id (e.g. `101082345`), the title, the framework programme, the type of action, the coordinator name + country, the consortium size, the start/end dates, the EU contribution, the total cost, the objective summary, and the project portal URL.

**When to use it**
For research orgs and consultancies doing competitive intelligence on EU funding: "what has the Commission funded on AI in the last 3 years?", "which Polish coordinators have run successful Horizon projects?", "what are the typical budgets for IA actions in Cluster 5?". Combine with `/api/v1/calls-for-proposals` to see the call → project pipeline.

**Input**
- `framework_programme` — substring (e.g. `Horizon Europe`, `Horizon 2020`).
- `coordinator_country` — ISO-2 (2 chars exact).
- `type_of_action` — substring (`RIA`, `IA`, `CSA`).
- `status` — F&T project status enum.
- `q` — substring search on title + objective.
- `start_from`, `end_to` — start-date / end-date window.
- `limit` (default 50, max 100), `page` (1-indexed).
- `body_threshold` — minimum body chars for `has_body=true`.

**Try it**
```
GET /api/v1/funded-projects?framework_programme=Horizon%20Europe&coordinator_country=NL
GET /api/v1/funded-projects?q=climate&type_of_action=IA
```

**You get back**
A `PaginatedResponse[FtFundedProjectItem]` envelope. Each item carries `project_id`, `title`, `framework_programme`, `type_of_action`, `coordinator_name`, `coordinator_country`, `consortium_size`, `start_date`, `end_date`, `eu_contribution`, `total_cost`, `objective`, `status`, `source_url`, `last_updated`, body fields + the 5 envelope-level datapoints (`public_url` = the F&T Portal project page).

**Data freshness**
Synced once per week (Sunday 05:00 UTC, weekly tier) from ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/projects-results. CORDIS (the more comprehensive research-results portal) is reachable separately via `/api/v1/discover/eurio`. is_test=True seed rows are filtered out at query time.""",
)
async def list_funded_projects(
    request: Request,
    framework_programme: Optional[str] = Query(None),
    coordinator_country: Optional[str] = Query(None, min_length=2, max_length=2),
    type_of_action: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    q: Optional[str] = Query(None),
    start_from: Optional[date] = Query(None),
    end_to: Optional[date] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[FtFundedProjectItem]:
    return await _v1.list_funded_projects(request=request, framework_programme=framework_programme, coordinator_country=coordinator_country, type_of_action=type_of_action, status=status, q=q, start_from=start_from, end_to=end_to, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)


@projects_router.get(
    "/{project_id:path}",
    response_model=FtFundedProjectItem,
    summary="Look up one EU-funded project by its grant project_id (numeric)",
    description="""**What it does**
Fetches a single EU-funded project by its grant project_id. Returns the same shape as the list endpoint.

**When to use it**
After locating a project via the list endpoint, use this for the full record. For richer project metadata (deliverables, consortium members, publications), cross-reference via `/api/v1/discover/eurio/projects/{cordis_id}/consortium` etc.

**Input**
- `project_id` (path) — the EU grant project id (typically a numeric identifier, e.g. `101082345`).

**Try it**
```
GET /api/v1/funded-projects/101082345
```

**You get back**
A single `FtFundedProjectItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — weekly Sunday 05:00 UTC sync from the F&T Portal projects-results page.""",
)
async def get_funded_project(
    project_id: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> FtFundedProjectItem:
    return await _v1.get_funded_project(project_id=project_id, body_threshold=body_threshold, user=user, db=db)
