"""Funding & Tenders domain — /api/v2/funding/funding-opportunities/*.

LIVE — copy-pasted verbatim from the v1 surface (api.v1.infringements_funding); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/funding/*.

Generated by scripts/_gen_v2_funding.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import infringements_funding as _v1
from api.v1.infringements_funding import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


funding_router = APIRouter(prefix="/funding-opportunities", tags=["v2-funding-opportunities"])


@funding_router.get(
    "",
    response_model=PaginatedResponse[FundingItem],
    summary="EU funding opportunities — open + forthcoming calls across programmes (alternate view)",
    description="""**What it does**
Returns EU funding opportunities (calls for proposals) from the Funding & Tenders Portal across Horizon Europe, Digital Europe, CEF, EU4Health, Erasmus+, and other Commission programmes. Each row carries the topic_id, call_id, programme, title, short summary + description, status, type of action, deadlines, budget, source URL, target audience.

**When to use it**
Same domain as `/api/v1/calls-for-proposals` but a slightly different surface — this one is broader (includes some opportunities not in the calls-for-proposals export). For most use cases, `/api/v1/calls-for-proposals` is the recommended endpoint. This one is preserved for backwards compatibility + a different filtering surface.

**Input**
- `programme` — substring (e.g. `Horizon`, `CEF`, `Digital Europe`).
- `status` — `open` / `forthcoming` / `closed` / `under-evaluation`.
- `type_of_action` — substring.
- `q` — substring on title + short_summary.
- `deadline_from`, `deadline_to` — deadline window.
- `limit` (default 50, max 100), `page` (1-indexed).
- `body_threshold` — minimum body chars for `has_body=true`.

**Try it**
```
GET /api/v1/funding?programme=Horizon&status=open
GET /api/v1/funding?q=AI&deadline_from=2026-06-01
```

**You get back**
A `PaginatedResponse[FundingItem]` envelope. Each item carries `topic_id`, `call_id`, `programme`, `title`, `short_summary`, `description`, `status`, `type_of_action`, `deadline`, `deadline_secondary`, `indicative_budget`, `budget_currency`, `source_url`, `documents_url`, `keywords`, `target_audience`, `published_at`, `last_updated`, body fields + the 5 envelope-level datapoints.

**Data freshness**
Synced once per day at 04:00 UTC (daily tier) from ec.europa.eu/info/funding-tenders/opportunities/portal. is_test=True fixture rows are filtered out at query time.""",
)
async def list_funding_opportunities(
    request: Request,
    programme: Optional[str] = Query(None, description="Programme name (Horizon, CEF, Digital Europe, ...)"),
    status: Optional[str] = Query(None, description="open | forthcoming | closed | under-evaluation"),
    type_of_action: Optional[str] = Query(None),
    q: Optional[str] = Query(None, description="Substring match on title/short_summary"),
    deadline_from: Optional[date] = Query(None),
    deadline_to: Optional[date] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[FundingItem]:
    return await _v1.list_funding_opportunities(request=request, programme=programme, status=status, type_of_action=type_of_action, q=q, deadline_from=deadline_from, deadline_to=deadline_to, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)


@funding_router.get(
    "/{topic_id:path}",
    response_model=FundingItem,
    summary="Look up one EU funding opportunity by its topic_id",
    description="""**What it does**
Fetches a single EU funding opportunity by its topic_id. Returns the same shape as the list endpoint, with the full description + body composition.

**When to use it**
After locating an opportunity via the list endpoint, use this for the full record before drafting a bid.

**Input**
- `topic_id` (path) — the EU's topic identifier (e.g. `HORIZON-CL5-2026-D2-01-01`). The `:path` matcher accepts hyphens + dots verbatim.

**Try it**
```
GET /api/v1/funding/HORIZON-CL5-2026-D2-01-01
```

**You get back**
A single `FundingItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — daily 04:00 UTC sync from the F&T Portal.""",
)
async def get_funding_opportunity(
    topic_id: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> FundingItem:
    return await _v1.get_funding_opportunity(topic_id=topic_id, body_threshold=body_threshold, user=user, db=db)
