"""Funding & Tenders domain — /api/v2/funding/tenders/*.

LIVE — copy-pasted verbatim from the v1 surface (api.v1.w5_endpoints); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/funding/*.

Generated by scripts/_gen_v2_funding.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import w5_endpoints as _v1
from api.v1.w5_endpoints import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


tenders_router = APIRouter(prefix="/tenders", tags=["v2-funding-tenders"])


@tenders_router.get(
    "",
    response_model=PaginatedResponse[TenderItem],
    summary="EU public procurement tenders (TED — Tenders Electronic Daily)",
    description="""**What it does**
Returns public-procurement tender notices from TED (Tenders Electronic Daily) — the EU's official journal for procurement, where every supplement to the OJ for above-threshold contracts is published. Covers tenders from the Commission, EP, Council, agencies, and Member State buyers obliged to publish at EU level. Each row carries the publication number, the title + description, the buying authority, the procedure type, the CPV codes (Common Procurement Vocabulary), the estimated value, the publication date, the submission deadline, lots information, and an SME-suitability score.

**When to use it**
For consultancies / SMEs looking for EU funding opportunities — filter by `cpv_main` for your sector, set `min_value` / `max_value` for relevant contract sizes, and use `deadline_from` / `deadline_to` to scope to bidding-feasible windows. The `sme_suitability_score` (0-1) is Brubru's heuristic on how SME-friendly a tender is based on value + lots + complexity.

**Input**
- `q` — substring search on title + description + summary.
- `buyer_country` — ISO-2.
- `procedure_type` — TED procedure type code.
- `contract_nature` — `works` / `supplies` / `services`.
- `cpv_main`, `cpv_code` — CPV filter.
- `form_type` — TED form code (F02 / F03 / F14 / etc).
- `min_value`, `max_value` — estimated-value range in EUR.
- `deadline_from`, `deadline_to` — submission_deadline window.
- `published_from`, `published_to` — publication date window.
- `updated_from` — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/funding/tenders?cpv_main=72000000&min_value=50000
GET /api/v2/funding/tenders?buyer_country=BE&contract_nature=services
```

**You get back**
A `PaginatedResponse[TenderItem]` envelope. Each item carries `publication_number`, `notice_id`, `form_type`, `title`, `description`, `official_name`, `buyer_country`, `procedure_type`, `cpv_codes`, `cpv_main`, `contract_nature`, `estimated_value` + `estimated_value_currency`, `publication_date`, `submission_deadline`, `has_lots`, `lot_count`, `ted_url`, `summary`, `sme_suitability_score`, `status`, `last_synced_at`, `updated_at`.

**Data freshness**
Synced once per day at 04:00 UTC (daily tier) from ted.europa.eu — TED publishes daily by definition (the "Daily" in the name). Backed by `backend/scripts/backfill_tenders_description.py`.""",
)
async def list_tenders(
    request: Request,
    q: Optional[str] = Query(None, description="Substring on title + description + summary"),
    buyer_country: Optional[str] = Query(None, description="ISO 3166-1 alpha-2"),
    procedure_type: Optional[str] = Query(None),
    contract_nature: Optional[str] = Query(None, description="works | supplies | services"),
    cpv_main: Optional[str] = Query(None),
    cpv_code: Optional[str] = Query(None, description="Match any CPV in cpv_codes"),
    form_type: Optional[str] = Query(None),
    min_value: Optional[float] = Query(None),
    max_value: Optional[float] = Query(None),
    deadline_from: Optional[date] = Query(None, description="submission_deadline >= value"),
    deadline_to: Optional[date] = Query(None),
    published_from: Optional[date] = Query(None, description="publication_date >= value"),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[TenderItem]:
    return await _v1.list_tenders(request=request, q=q, buyer_country=buyer_country, procedure_type=procedure_type, contract_nature=contract_nature, cpv_main=cpv_main, cpv_code=cpv_code, form_type=form_type, min_value=min_value, max_value=max_value, deadline_from=deadline_from, deadline_to=deadline_to, published_from=published_from, published_to=published_to, updated_from=updated_from, limit=limit, page=page, user=user, db=db)


@tenders_router.get(
    "/{tender_id}",
    response_model=TenderItem,
    summary="Look up one TED tender by its internal numeric id",
    description="""**What it does**
Fetches a single TED tender by its Brubru-internal integer id. Returns the same shape as the list endpoint, including CPV codes + lot details + the TED URL for the official notice.

**When to use it**
After locating a tender via the list endpoint, use this to fetch the full record (with description + all CPV codes) for embedding in a bid-tracker UI.

**Input**
- `tender_id` (path) — Brubru integer id (returned in `id` from the list endpoint).

**Try it**
```
GET /api/v2/funding/tenders/12345
```

**You get back**
A single `TenderItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — daily 04:00 UTC sync from ted.europa.eu.""",
)
async def get_tender_detail(
    tender_id: int,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> TenderItem:
    return await _v1.get_tender_detail(tender_id=tender_id, user=user, db=db)
