"""Resolve an item route's path parameter to a row, whichever identifier was used.

The defect this closes
----------------------
Measured 31 August 2026 across all 452 v2 item routes: 387 navigate straight from
the `id` their collection publishes. Eighteen do not. Those eighteen are keyed on
the institution's own reference -- `P10_TA(2026)0271`, `SWD(2026) 269`,
`2020/2220(INL)` -- while their collection still publishes `id`, the internal
surrogate. So the universal REST reflex

    GET /collection  ->  take `id`  ->  GET /collection/{id}

answered 404 on all eighteen. The key was in the payload the whole time, under a
name that differs per endpoint and is documented nowhere as "the identifier".

The rule this implements
------------------------
`id` is each resource's own primary key, in its natural JSON type: a number where
the key is bigint/integer (345 endpoints), a string where it is a UUID (42).
Nothing is converted, so nothing breaks. Every item route accepts that `id`, and
continues to accept the institutional reference it accepted before.

Why the surrogate rather than the reference
-------------------------------------------
Both were measured against the data before choosing:

  * `legislative_carriages.oeil_procedure_ref` is present on 1,440 of 2,789 rows
    and repeats three times. `id` is unique and non-null on all 2,789.
  * All 5,674 parliamentary-question references and all 144 resolution refs
    contain a "/", which cannot sit in a path segment unencoded.

The surrogate wins on exactly the ground the natural key loses. The reference
stays a first-class field, and becomes a collection filter, because people cite
`P10_TA(2026)0271` and never cite a UUID.

Why one helper instead of eighteen fixes
----------------------------------------
660 routes generated by one factory share two path-parameter names and have zero
broken pairs. 76 hand-written routes use 25 names and contain all 18 breakages.
Nobody was less careful; there was simply no shared shape to conform to. Putting
the resolution in one place is the only version of this fix that stays fixed.
"""

from __future__ import annotations

import uuid as _uuid
from typing import Any, Optional, Sequence

from sqlalchemy import inspect as _sa_inspect
from sqlalchemy.orm import Session


def _pk_column(model):
    """The model's single primary-key column, or None when it is composite.

    Composite keys exist in the schema (8 tables) but none of them backs a public
    resource -- they are joins, caches and config.
    """
    pk = list(_sa_inspect(model).primary_key)
    return pk[0] if len(pk) == 1 else None


def _coerce_to_pk(column, raw: str) -> Optional[Any]:
    """Cast `raw` to the primary key's type, or None when it cannot be one.

    Guarding this matters: handing a non-UUID string to a uuid column makes
    Postgres raise a DataError rather than simply not matching, which would turn
    "this is a reference, not an id" into a 500.
    """
    try:
        python_type = column.type.python_type
    except NotImplementedError:          # exotic column type; treat as opaque
        return raw
    if python_type is _uuid.UUID:
        try:
            return _uuid.UUID(str(raw))
        except (ValueError, AttributeError, TypeError):
            return None
    if python_type is int:
        s = str(raw)
        return int(s) if s.lstrip("-").isdigit() else None
    return raw


def resolve_row(
    db: Session,
    model,
    raw: str,
    natural_keys: Sequence[str] = (),
    extra_filters: Sequence[Any] = (),
):
    """Return the row `raw` identifies, or None.

    Tries the surrogate primary key first -- that is the identifier the
    collection publishes and the one a client will reach for -- then each
    natural key in turn, so every URL that worked before still works.

    `natural_keys` are attribute names on the model, in priority order.
    `extra_filters` are appended to every query (a fund code, a body slug).
    """
    if raw is None or str(raw).strip() == "":
        return None
    raw = str(raw).strip()

    def _first(criterion):
        q = db.query(model).filter(criterion)
        for f in extra_filters:
            q = q.filter(f)
        return q.first()

    pk = _pk_column(model)
    if pk is not None:
        cast = _coerce_to_pk(pk, raw)
        if cast is not None:
            row = _first(pk == cast)
            if row is not None:
                return row

    for name in natural_keys:
        column = getattr(model, name, None)
        if column is None:
            continue
        row = _first(column == raw)
        if row is not None:
            return row
    return None


def public_id(row) -> Optional[str]:
    """The value a client should send back, as a string for URL building.

    The API keeps each resource's native JSON type in the payload; this is only
    for composing a URL, where everything is text anyway.
    """
    pk = _pk_column(type(row))
    if pk is None:
        return None
    value = getattr(row, pk.name, None)
    return None if value is None else str(value)


def self_url(request, collection_path: str, identifier: Any) -> Optional[str]:
    """The canonical URL of one item, correctly escaped.

    This is the half of the fix that removes the guessing entirely: the client
    never has to know which field is the key, nor that a reference containing a
    "/" needs encoding, because it follows a URL we built.
    """
    from urllib.parse import quote

    if identifier is None:
        return None
    base = str(request.base_url).rstrip("/") if request is not None else ""
    return f"{base}{collection_path}/{quote(str(identifier), safe='')}"
