"""Open Data domain — /api/v2/open-data/datasets/* and /api/v2/open-data/high-value-datasets/* and /api/v2/open-data/catalogues/*.

LIVE — copy-pasted verbatim from the v1 surface (api.v1.open_data); the body delegates
to the v1 handlers so there is exactly one implementation during the v1+v2
coexistence period. Only the in-description example URLs are rehomed to
/api/v2/open-data/*.

Generated by scripts/_gen_v2_open_data.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import open_data as _v1
from api.v1.open_data import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


from api.v1.open_data import _DESC  # noqa: F401 - used in decorators

datasets_router = APIRouter(prefix="/datasets", tags=["v2-open-data-datasets"])
hvd_router = APIRouter(prefix="/high-value-datasets", tags=["v2-open-data-high-value-datasets"])
catalogues_router = APIRouter(prefix="/catalogues", tags=["v2-open-data-catalogues"])


@datasets_router.get(
    "",
    response_model=PaginatedResponse[OpenDataDatasetItem],
    summary="EU open datasets — search data.europa.eu (with direct download links)",
    description=_DESC(
        "Searches the European Union open-data portal (data.europa.eu) — datasets published by EU institutions and member states, each with its publisher, catalogue, themes, formats, the High-Value-Dataset flag, and direct distribution download URLs.",
        "To find and pull EU open data on any policy topic — the single biggest EU open-data catalogue (1.9M+ datasets), with machine-readable download links per dataset.",
        "- `q` — full-text search over title / description / keywords.\n- `publisher` — substring match on the publisher.\n- `theme` — DCAT theme / category.\n- `country` — ISO country code of the publishing portal (e.g. `de`, `fr`).\n- `format` — distribution format (CSV, JSON, XML, ...).\n- `catalogue` — catalogue id.\n- `hvd` — true = only High-Value Datasets.\n- `published_from`, `published_to` — bound on the last-modified date.\n- `limit` (default 25, max 100), `page` (1-indexed).",
        "A `PaginatedResponse[OpenDataDatasetItem]`; each item carries `distributions` (download URLs), `formats`, `is_hvd`, `publisher`, `catalogue`, `themes`.",
        "GET /api/v2/open-data/datasets?q=air+quality&format=CSV",
    ),
)
async def list_datasets(
    request: Request,
    q: Optional[str] = Query(None),
    publisher: Optional[str] = Query(None),
    theme: Optional[str] = Query(None),
    country: Optional[str] = Query(None),
    format: Optional[str] = Query(None),
    catalogue: Optional[str] = Query(None),
    hvd: Optional[bool] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[OpenDataDatasetItem]:
    return await _v1.list_datasets(request=request, q=q, publisher=publisher, theme=theme, country=country, format=format, catalogue=catalogue, hvd=hvd, published_from=published_from, published_to=published_to, limit=limit, page=page, user=user, db=db)


@datasets_router.get(
    "/{item_id}",
    response_model=OpenDataDatasetItem,
    summary="One EU open dataset by id — full metadata + download links",
    description="Fetch a single data.europa.eu dataset by its Brubru UUID, with the full DCAT metadata and all distribution download URLs. 404 with `reason_code: not_found` if absent.",
)
async def get_dataset(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> OpenDataDatasetItem:
    return await _v1.get_dataset(item_id=item_id, user=user, db=db)


@hvd_router.get(
    "",
    response_model=PaginatedResponse[OpenDataDatasetItem],
    summary="EU High-Value Datasets (Open Data Directive)",
    description=_DESC(
        "Returns the High-Value Datasets — the category the EU Open Data Directive designates as having high reuse potential (geospatial, earth observation/environment, meteorological, statistics, companies, mobility) — a filtered view of the open-data catalogue.",
        "To find the EU datasets the law itself flags as the most valuable to reuse, with their download links.",
        "- `q`, `publisher`, `theme`, `country`, `format`, `catalogue` — same as the datasets endpoint.\n- `published_from`, `published_to`.\n- `limit` (default 25, max 100), `page`.",
        "A `PaginatedResponse[OpenDataDatasetItem]` of High-Value Datasets (all `is_hvd=true`).",
        "GET /api/v2/open-data/high-value-datasets?theme=geospatial",
    ),
)
async def list_high_value_datasets(
    request: Request,
    q: Optional[str] = Query(None),
    publisher: Optional[str] = Query(None),
    theme: Optional[str] = Query(None),
    country: Optional[str] = Query(None),
    format: Optional[str] = Query(None),
    catalogue: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[OpenDataDatasetItem]:
    return await _v1.list_high_value_datasets(request=request, q=q, publisher=publisher, theme=theme, country=country, format=format, catalogue=catalogue, published_from=published_from, published_to=published_to, limit=limit, page=page, user=user, db=db)


@catalogues_router.get(
    "",
    response_model=PaginatedResponse[OpenDataCatalogueItem],
    summary="EU open-data catalogues — the data.europa.eu catalogue directory",
    description=_DESC(
        "Returns the data catalogues federated by data.europa.eu — the ~90 EU institution and member-state open-data catalogues (including the EU Legal Data Space ELDS and the Public Procurement Data Space PPDS).",
        "As a reference list of the data sources data.europa.eu aggregates, to scope a dataset search by `catalogue`.",
        "- `q` — substring match on the catalogue id / title.\n- `limit` (default 50, max 100), `page`.",
        "A `PaginatedResponse[OpenDataCatalogueItem]`.",
        "GET /api/v2/open-data/catalogues?q=eurostat",
    ),
)
async def list_data_catalogues(
    request: Request,
    q: Optional[str] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[OpenDataCatalogueItem]:
    return await _v1.list_data_catalogues(request=request, q=q, limit=limit, page=page, user=user, db=db)


@catalogues_router.get(
    "/{item_id}",
    response_model=OpenDataCatalogueItem,
    summary="One EU open-data catalogue by id",
    description="Fetch a single data.europa.eu catalogue by its Brubru UUID. 404 with `reason_code: not_found` if absent.",
)
async def get_data_catalogue(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> OpenDataCatalogueItem:
    return await _v1.get_data_catalogue(item_id=item_id, user=user, db=db)
