"""One-shot generator: emit the v2 "European Council" and "Eurogroup" domain
modules by copy-pasting the v1 route decorators + signatures verbatim and
delegating the body to the v1 handlers. Same approach as _gen_v2_council.py.

Both reuse the shared council_register schema + list/detail helpers; the only
underscore names referenced in decorators/signatures are the locally-defined
``_DESC`` and ``_params``, which the underscore-detector re-imports explicitly.

Run once from backend/:  python3.12 scripts/_gen_v2_consilium_folders.py
"""
from __future__ import annotations

import ast
import pathlib
import re

V1 = pathlib.Path("api/v1")

# domain key -> config
DOMAINS = {
    "european_council": {
        "url_segment": "european-council",   # /api/v2/european-council/*
        "v1_module": "european_council",
        "out_dir": pathlib.Path("api/v2/european_council"),
        "prefix_re": re.compile(r"/api/v1/(euco-[a-z-]+)\b"),
        "routers": [
            ("conclusions_router", "/euco-conclusions", "v2-euco-conclusions",
             ["list_euco_conclusions", "get_euco_conclusion"]),
            ("meetings_router", "/euco-meetings", "v2-euco-meetings",
             ["list_euco_meetings", "get_euco_meeting"]),
            ("euro_summit_router", "/euco-euro-summit", "v2-euco-euro-summit",
             ["list_euco_euro_summit", "get_euco_euro_summit"]),
            ("strategic_agenda_router", "/euco-strategic-agenda", "v2-euco-strategic-agenda",
             ["list_euco_strategic_agenda", "get_euco_strategic_agenda"]),
            ("members_router", "/euco-members", "v2-euco-members",
             ["list_euco_members", "get_euco_member"]),
            ("about_router", "/euco-about", "v2-euco-about",
             ["list_euco_about", "get_euco_about"]),
        ],
    },
    "eurogroup": {
        "url_segment": "eurogroup",          # /api/v2/eurogroup/*
        "v1_module": "eurogroup",
        "out_dir": pathlib.Path("api/v2/eurogroup"),
        "prefix_re": re.compile(r"/api/v1/(eurogroup-[a-z-]+)\b"),
        "routers": [
            ("meetings_router", "/eurogroup-meetings", "v2-eurogroup-meetings",
             ["list_eurogroup_meetings", "get_eurogroup_meeting"]),
            ("documents_router", "/eurogroup-documents", "v2-eurogroup-documents",
             ["list_eurogroup_documents", "get_eurogroup_document"]),
            ("work_programme_router", "/eurogroup-work-programme", "v2-eurogroup-work-programme",
             ["list_eurogroup_work_programme", "get_eurogroup_work_programme"]),
            ("members_router", "/eurogroup-members", "v2-eurogroup-members",
             ["list_eurogroup_members", "get_eurogroup_member"]),
            ("about_router", "/eurogroup-about", "v2-eurogroup-about",
             ["list_eurogroup_about", "get_eurogroup_about"]),
        ],
    },
}

PREAMBLE = '''"""{title} domain — {prefixes}.

LIVE — copy-pasted verbatim from the v1 surface (api.v1.{mod}); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/{seg}/*.

Generated by scripts/_gen_v2_consilium_folders.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import {mod} as _v1
from api.v1.{mod} import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints

'''


def param_names(fn: ast.AsyncFunctionDef) -> list:
    a = fn.args
    return [p.arg for p in (a.posonlyargs + a.args + a.kwonlyargs)]


def build_module(cfg: dict) -> str:
    mod = cfg["v1_module"]
    seg = cfg["url_segment"]
    prefix_re = cfg["prefix_re"]
    src = (V1 / f"{mod}.py").read_text()
    tree = ast.parse(src)
    lines = src.splitlines()
    funcs = {n.name: n for n in ast.walk(tree) if isinstance(n, ast.AsyncFunctionDef)}
    defined = set()
    for n in tree.body:
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            defined.add(n.name)
        elif isinstance(n, ast.Assign):
            for t in n.targets:
                if isinstance(t, ast.Name):
                    defined.add(t.id)

    def rewrite(t: str) -> str:
        return prefix_re.sub(rf"/api/v2/{seg}/\1", t)

    title = "European Council" if mod == "european_council" else "Eurogroup"
    prefixes = " and ".join(f"/api/v2/{seg}{p}/*" for _, p, _, _ in cfg["routers"])
    body_chunks = []
    underscore_imports: set = set()
    for var, _prefix, _tag, fnames in cfg["routers"]:
        for fname in fnames:
            fn = funcs[fname]
            decos = []
            for d in fn.decorator_list:
                s = ast.get_source_segment(src, d)
                s = "@" + s if not s.startswith("@") else s
                decos.append(rewrite(s))   # router var unchanged (same name in v2)
            sig = "\n".join(lines[fn.lineno - 1: fn.body[0].lineno - 1])
            call = ", ".join(f"{n}={n}" for n in param_names(fn))
            blob = "\n".join(decos) + "\n" + sig
            for tok in set(re.findall(r"\b_[A-Za-z0-9_]+\b", blob)):
                if tok in defined:
                    underscore_imports.add(tok)
            body_chunks.append("\n".join(decos))
            body_chunks.append(sig)
            body_chunks.append(f"    return await _v1.{fname}({call})")
            body_chunks.append("")
            body_chunks.append("")

    out = [PREAMBLE.format(title=title, prefixes=prefixes, mod=mod, seg=seg)]
    if underscore_imports:
        out.append(f"from api.v1.{mod} import {', '.join(sorted(underscore_imports))}  # noqa: F401 - used in decorators")
        out.append("")
    for var, prefix, tag, _ in cfg["routers"]:
        out.append(f'{var} = APIRouter(prefix="{prefix}", tags=["{tag}"])')
    out.append("")
    out.append("")
    out.extend(body_chunks)
    return "\n".join(out).rstrip() + "\n"


def main():
    for key, cfg in DOMAINS.items():
        cfg["out_dir"].mkdir(parents=True, exist_ok=True)
        (cfg["out_dir"] / f"{cfg['v1_module']}.py").write_text(build_module(cfg))
        print(f"[OK] wrote {cfg['out_dir']}/{cfg['v1_module']}.py")


if __name__ == "__main__":
    main()
