"""One-shot generator: emit the v2 "European Commission" domain modules by
copy-pasting the v1 Commission route decorators + signatures verbatim and
delegating the body to the v1 handler (single source of truth during v1+v2
coexistence). Same approach as scripts/_gen_v2_parliament.py.

Section A only (16 core Commission routes), excluding multi-institution
endpoints. Two wrinkles vs the EP generator:
- the commissioners source spans TWO v1 modules (the *list* lives in
  api.v1.metadata, the detail + agenda in api.v1.commissioners);
- metadata's list_commissioners is decorated at the absolute path
  "/commissioners" (its router has no prefix), so its decorator path is
  overridden to "" to sit under the /commissioners-prefixed v2 router.

Only the 7 Commission-domain `/api/v1/<seg>` example URLs are rewritten to
`/api/v2/commission/<seg>`; cross-domain refs (funding, acts, metadata
siblings, parliamentary-questions, specialised/*) are left pointing at v1.

Run once from backend/:  python3.12 scripts/_gen_v2_commission.py
"""
from __future__ import annotations

import ast
import pathlib
import re

V1 = pathlib.Path("api/v1")
OUT = pathlib.Path("api/v2/commission")

# Longest-first where prefixes overlap (commission-register-documents before
# commission-register) so the alternation matches the longer segment first.
EC_SEGMENTS = (
    "commissioners", "commission-register-documents", "commission-register",
    "meetings", "rsb-opinions", "infringements", "consultations",
    "tris-notifications",
)
_URL_RE = re.compile(r"/api/v1/(" + "|".join(EC_SEGMENTS) + r")\b")


def rewrite_urls(text: str) -> str:
    return _URL_RE.sub(r"/api/v2/commission/\1", text)


# output file -> {prefix, tag, groups: [(v1_module, [(func, path_override|None)])]}
OUTPUTS = {
    "commissioners": {
        "prefix": "/commissioners", "tag": "v2-commission-commissioners",
        "groups": [
            ("metadata", [("list_commissioners", "")]),
            ("commissioners", [("get_profile", None), ("get_agenda", None)]),
        ],
    },
    "commission_register": {
        "prefix": "/commission-register-documents", "tag": "v2-commission-commission-register",
        "groups": [
            ("commission_register", [
                ("list_commission_register_documents", None),
                ("get_commission_register_detail", None),
            ]),
        ],
    },
    "meetings": {
        "prefix": "/meetings", "tag": "v2-commission-meetings",
        "groups": [("w4_endpoints", [("list_meetings", None), ("get_meeting_detail", None)])],
    },
    "rsb_opinions": {
        "prefix": "/rsb-opinions", "tag": "v2-commission-rsb-opinions",
        "groups": [("w4_endpoints", [("list_rsb_opinions", None), ("get_rsb_detail", None)])],
    },
    "infringements": {
        "prefix": "/infringements", "tag": "v2-commission-infringements",
        "groups": [("infringements_funding", [("list_infringements", None), ("get_infringement", None)])],
    },
    "consultations": {
        "prefix": "/consultations", "tag": "v2-commission-consultations",
        "groups": [("consultations", [
            ("list_consultations", None),
            ("get_consultation_detail", None),
            ("get_feedback_by_initiative", None),
        ])],
    },
    "tris_notifications": {
        "prefix": "/tris-notifications", "tag": "v2-commission-tris-notifications",
        "groups": [("w4_endpoints", [("list_tris_notifications", None), ("get_tris_detail", None)])],
    },
}

PREAMBLE_HEAD = '''"""European Parliament-style copy of the v1 European Commission surface — {prefix}/*.

LIVE — copy-pasted verbatim from the v1 Commission surface; the body delegates
to the v1 handler so there is exactly one implementation during the v1+v2
coexistence period. Summaries, descriptions and signatures are identical to v1;
only the in-description example URLs are rehomed to /api/v2/commission/*.

Generated by scripts/_gen_v2_commission.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
'''


def param_names(fn: ast.AsyncFunctionDef) -> list[str]:
    a = fn.args
    return [p.arg for p in (a.posonlyargs + a.args + a.kwonlyargs)]


def parse_module(mod: str):
    src = (V1 / f"{mod}.py").read_text()
    tree = ast.parse(src)
    funcs = {n.name: n for n in ast.walk(tree) if isinstance(n, ast.AsyncFunctionDef)}
    # top-level defined names (classes + module assignments) — needed to know
    # which underscore-prefixed names `import *` will skip and must be imported.
    defined = set()
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            defined.add(node.name)
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name):
                    defined.add(t.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            defined.add(node.target.id)
    return src, src.splitlines(), funcs, defined


def override_path(deco: str, new_path: str) -> str:
    # replace the first quoted string after `.get(` with new_path
    return re.sub(r'(\.get\(\s*)(["\'])[^"\']*\2', rf'\1"{new_path}"', deco, count=1)


def build_module(name: str, conf: dict) -> str:
    mods = []
    for m, _ in conf["groups"]:
        if m not in mods:
            mods.append(m)

    cache = {m: parse_module(m) for m in mods}

    # Build the route bodies first so we can detect which underscore-prefixed
    # names (skipped by `import *`) must be explicitly imported.
    bodies = []
    underscore_imports: dict[str, set] = {m: set() for m in mods}
    for mod, funcs_spec in conf["groups"]:
        src, lines, funcs, defined = cache[mod]
        for fname, path_ovr in funcs_spec:
            fn = funcs[fname]
            decos = []
            for d in fn.decorator_list:
                seg = ast.get_source_segment(src, d)
                seg = "@" + seg if not seg.startswith("@") else seg
                seg = re.sub(r"@\w+\.get\(", "@router.get(", seg)  # normalise router var
                if path_ovr is not None:
                    seg = override_path(seg, path_ovr)
                decos.append(rewrite_urls(seg))
            sig = "\n".join(lines[fn.lineno - 1: fn.body[0].lineno - 1])
            call = ", ".join(f"{n}={n}" for n in param_names(fn))
            chunk = "\n".join(decos) + "\n" + sig + f"\n    return await _v1_{mod}.{fname}({call})"
            for tok in set(re.findall(r"\b_[A-Za-z0-9_]+\b", "\n".join(decos) + "\n" + sig)):
                if tok in defined:
                    underscore_imports[mod].add(tok)
            bodies.append(chunk)

    out = [PREAMBLE_HEAD.format(prefix="/api/v2/commission" + conf["prefix"])]
    for m in mods:
        out.append(f"from api.v1 import {m} as _v1_{m}")
    for m in mods:
        out.append(f"from api.v1.{m} import *  # noqa: F401,F403 - reproduce v1 namespace for get_type_hints")
        if underscore_imports[m]:
            names = ", ".join(sorted(underscore_imports[m]))
            out.append(f"from api.v1.{m} import {names}  # private names skipped by import *")
    out.append("")
    out.append(f'router = APIRouter(prefix="{conf["prefix"]}", tags=["{conf["tag"]}"])')
    out.append("")
    out.append("")
    for chunk in bodies:
        out.append(chunk)
        out.append("")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, conf in OUTPUTS.items():
        (OUT / f"{name}.py").write_text(build_module(name, conf))
        print(f"[OK] wrote api/v2/commission/{name}.py")


if __name__ == "__main__":
    main()
