"""One-shot generator: emit the v2 "Council of the EU" domain module by
copy-pasting the v1 Council route decorators + signatures verbatim and
delegating the body to the v1 handlers. Same approach as the EP/Commission
generators.

Sources mirrored (all in api.v1.council_documents):
  - council-documents      list + detail
  - council-configurations the 10 configurations (+ Eurogroup) reference list

Only the /api/v1/council-documents and /api/v1/council-configurations example
URLs are rehomed to /api/v2/council/*.

Run once from backend/:  python3.12 scripts/_gen_v2_council.py
"""
from __future__ import annotations

import ast
import pathlib
import re

V1 = pathlib.Path("api/v1")
OUT = pathlib.Path("api/v2/council")

_URL_RE = re.compile(r"/api/v1/(council-[a-z-]+)\b")


def rewrite_urls(text: str) -> str:
    return _URL_RE.sub(r"/api/v2/council/\1", text)


# output file -> list of (v1_router_var, v2_router_var, prefix, tag, [func_names])
OUTPUTS = {
    "council_documents": [
        ("router", "router", "/council-documents", "v2-council-council-documents",
         ["list_council_documents", "get_council_document_detail"]),
        ("configurations_router", "configurations_router", "/council-configurations", "v2-council-configurations",
         ["list_council_configurations"]),
    ],
    "council_register": [
        ("meetings_router", "meetings_router", "/council-meetings", "v2-council-meetings",
         ["list_council_meetings", "get_council_meeting"]),
        ("votes_router", "votes_router", "/council-voting-results", "v2-council-voting-results",
         ["list_council_voting_results", "get_council_voting_result"]),
        ("register_router", "register_router", "/council-register", "v2-council-register",
         ["list_council_register", "get_council_register_document"]),
        ("oj_router", "oj_router", "/council-oj-agendas", "v2-council-oj-agendas",
         ["list_council_oj_agendas", "get_council_oj_agenda"]),
        ("prep_router", "prep_router", "/council-preparatory-bodies", "v2-council-preparatory-bodies",
         ["list_council_preparatory_bodies", "get_council_preparatory_body"]),
        ("press_router", "press_router", "/council-press-releases", "v2-council-press-releases",
         ["list_council_press_releases", "get_council_press_release"]),
        ("research_router", "research_router", "/council-research-papers", "v2-council-research-papers",
         ["list_council_research_papers", "get_council_research_paper"]),
        ("treaties_router", "treaties_router", "/council-treaties-agreements", "v2-council-treaties-agreements",
         ["list_council_treaties_agreements", "get_council_treaty_agreement"]),
    ],
}

PREAMBLE = '''"""Council of the EU domain — {prefixes}.

LIVE — copy-pasted verbatim from the v1 Council surface (api.v1.{mod}); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/council/*.

Generated by scripts/_gen_v2_council.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import {mod} as _v1
from api.v1.{mod} import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints

'''


def param_names(fn: ast.AsyncFunctionDef) -> list[str]:
    a = fn.args
    return [p.arg for p in (a.posonlyargs + a.args + a.kwonlyargs)]


def build_module(mod: str, routers: list) -> str:
    src = (V1 / f"{mod}.py").read_text()
    tree = ast.parse(src)
    lines = src.splitlines()
    funcs = {n.name: n for n in ast.walk(tree) if isinstance(n, ast.AsyncFunctionDef)}
    # Module-level names (for detecting underscore helpers referenced in
    # decorators/signatures, which `import *` would skip — e.g. _DESC).
    defined = set()
    for n in tree.body:
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            defined.add(n.name)
        elif isinstance(n, ast.Assign):
            for t in n.targets:
                if isinstance(t, ast.Name):
                    defined.add(t.id)

    prefixes = " and ".join(f"/api/v2/council{p}/*" for _, _, p, _, _ in routers)
    body_chunks = []
    underscore_imports: set = set()
    for v1var, v2var, _prefix, _tag, fnames in routers:
        for fname in fnames:
            fn = funcs[fname]
            decos = []
            for d in fn.decorator_list:
                seg = ast.get_source_segment(src, d)
                seg = "@" + seg if not seg.startswith("@") else seg
                seg = re.sub(rf"@{v1var}\.", f"@{v2var}.", seg)
                decos.append(rewrite_urls(seg))
            sig = "\n".join(lines[fn.lineno - 1: fn.body[0].lineno - 1])
            call = ", ".join(f"{n}={n}" for n in param_names(fn))
            blob = "\n".join(decos) + "\n" + sig
            for tok in set(re.findall(r"\b_[A-Za-z0-9_]+\b", blob)):
                if tok in defined:
                    underscore_imports.add(tok)
            body_chunks.append("\n".join(decos))
            body_chunks.append(sig)
            body_chunks.append(f"    return await _v1.{fname}({call})")
            body_chunks.append("")
            body_chunks.append("")

    out = [PREAMBLE.format(prefixes=prefixes, mod=mod)]
    if underscore_imports:
        out.append(f"from api.v1.{mod} import {', '.join(sorted(underscore_imports))}  # noqa: F401 - used in decorators")
        out.append("")
    for _v1var, v2var, prefix, tag, _ in routers:
        out.append(f'{v2var} = APIRouter(prefix="{prefix}", tags=["{tag}"])')
    out.append("")
    out.append("")
    out.extend(body_chunks)
    return "\n".join(out).rstrip() + "\n"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for mod, routers in OUTPUTS.items():
        (OUT / f"{mod}.py").write_text(build_module(mod, routers))
        print(f"[OK] wrote api/v2/council/{mod}.py")


if __name__ == "__main__":
    main()
