"""Generate the v2 "General Publications" domain (single router, list+detail)."""
from __future__ import annotations
import ast, pathlib, re
V1 = pathlib.Path("api/v1"); OUT = pathlib.Path("api/v2/general_publications")
_URL_RE = re.compile(r"/api/v1/(general-publications)")
def rewrite(t): return _URL_RE.sub(r"/api/v2/\1", t)
FUNCS = ["list_general_publications", "get_general_publication"]
PRE = '''"""General Publications domain — /api/v2/general-publications/*.

LIVE — copy-pasted from api.v1.general_publications; body delegates to the v1
handlers. Generated by scripts/_gen_v2_general_publications.py — do not hand-edit.
"""
from __future__ import annotations
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401
from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401
from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import general_publications as _v1
from api.v1.general_publications import *  # noqa: F401,F403
'''
def pnames(fn):
    a=fn.args; return [p.arg for p in (a.posonlyargs+a.args+a.kwonlyargs)]
src=(V1/"general_publications.py").read_text(); tree=ast.parse(src); lines=src.splitlines()
funcs={n.name:n for n in ast.walk(tree) if isinstance(n,ast.AsyncFunctionDef)}
out=[PRE, '', 'router = APIRouter(prefix="/general-publications")', '', '']
for fname in FUNCS:
    fn=funcs[fname]; decos=[]
    for d in fn.decorator_list:
        seg=ast.get_source_segment(src,d); seg="@"+seg if not seg.startswith("@") else seg
        decos.append(rewrite(seg))
    sig="\n".join(lines[fn.lineno-1:fn.body[0].lineno-1])
    call=", ".join(f"{n}={n}" for n in pnames(fn))
    out += ["\n".join(decos), sig, f"    return await _v1.{fname}({call})", "", ""]
OUT.mkdir(parents=True, exist_ok=True)
(OUT/"general_publications.py").write_text("\n".join(out).rstrip()+"\n")
print("[OK] wrote api/v2/general_publications/general_publications.py")
