"""One-shot generator: emit the v2 "Funding & Tenders" domain modules by
copy-pasting the v1 route decorators + signatures verbatim and delegating the
body to the v1 handlers. Same approach as scripts/_gen_v2_council.py.

This domain pulls from THREE v1 modules (only the funding/tenders routers, not
the infringements/research/officials routers that live in those same files), so
the OUTPUTS map decouples the output filename from the source v1 module.

Sources mirrored:
  - funding-opportunities  (infringements_funding.funding_router)
  - ft-calls-for-proposals (funding_tenders_collections.calls_router)
  - ft-calls-for-tenders   (funding_tenders_collections.tenders_router)
  - ft-funded-projects     (funding_tenders_collections.projects_router)
  - tenders                (w5_endpoints.tenders_router)  -- TED

Run once from backend/:  python3.12 scripts/_gen_v2_funding.py
"""
from __future__ import annotations

import ast
import pathlib
import re

V1 = pathlib.Path("api/v1")
OUT = pathlib.Path("api/v2/funding")

_SEGS = ("funding-opportunities", "ft-calls-for-proposals", "ft-calls-for-tenders",
         "ft-funded-projects", "tenders")
_URL_RE = re.compile(r"/api/v1/(" + "|".join(_SEGS) + r")\b")


def rewrite_urls(text: str) -> str:
    return _URL_RE.sub(r"/api/v2/funding/\1", text)


# output filename -> (v1_module, [(router_var, prefix, tag, [func_names])])
OUTPUTS = {
    "funding_opportunities": ("infringements_funding", [
        ("funding_router", "/funding-opportunities", "v2-funding-opportunities",
         ["list_funding_opportunities", "get_funding_opportunity"]),
    ]),
    "funding_tenders": ("funding_tenders_collections", [
        ("calls_router", "/ft-calls-for-proposals", "v2-funding-ft-calls-for-proposals",
         ["list_calls_for_proposals", "get_call_for_proposals"]),
        ("tenders_router", "/ft-calls-for-tenders", "v2-funding-ft-calls-for-tenders",
         ["list_calls_for_tenders", "get_call_for_tenders"]),
        ("projects_router", "/ft-funded-projects", "v2-funding-ft-funded-projects",
         ["list_funded_projects", "get_funded_project"]),
    ]),
    "ted_tenders": ("w5_endpoints", [
        ("tenders_router", "/tenders", "v2-funding-tenders",
         ["list_tenders", "get_tender_detail"]),
    ]),
}

PREAMBLE = '''"""Funding & Tenders domain — {prefixes}.

LIVE — copy-pasted verbatim from the v1 surface (api.v1.{mod}); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/funding/*.

Generated by scripts/_gen_v2_funding.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import {mod} as _v1
from api.v1.{mod} import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints

'''


def param_names(fn: ast.AsyncFunctionDef) -> list:
    a = fn.args
    return [p.arg for p in (a.posonlyargs + a.args + a.kwonlyargs)]


def build_module(mod: str, routers: list) -> str:
    src = (V1 / f"{mod}.py").read_text()
    tree = ast.parse(src)
    lines = src.splitlines()
    funcs = {n.name: n for n in ast.walk(tree) if isinstance(n, ast.AsyncFunctionDef)}
    defined = set()
    for n in tree.body:
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            defined.add(n.name)
        elif isinstance(n, ast.Assign):
            for t in n.targets:
                if isinstance(t, ast.Name):
                    defined.add(t.id)

    prefixes = " and ".join(f"/api/v2/funding{p}/*" for _, p, _, _ in routers)
    body_chunks = []
    underscore_imports: set = set()
    for var, _prefix, _tag, fnames in routers:
        for fname in fnames:
            fn = funcs[fname]
            decos = []
            for d in fn.decorator_list:
                seg = ast.get_source_segment(src, d)
                seg = "@" + seg if not seg.startswith("@") else seg
                decos.append(rewrite_urls(seg))   # router var unchanged (same name in v2)
            sig = "\n".join(lines[fn.lineno - 1: fn.body[0].lineno - 1])
            call = ", ".join(f"{n}={n}" for n in param_names(fn))
            blob = "\n".join(decos) + "\n" + sig
            for tok in set(re.findall(r"\b_[A-Za-z0-9_]+\b", blob)):
                if tok in defined:
                    underscore_imports.add(tok)
            body_chunks.append("\n".join(decos))
            body_chunks.append(sig)
            body_chunks.append(f"    return await _v1.{fname}({call})")
            body_chunks.append("")
            body_chunks.append("")

    out = [PREAMBLE.format(prefixes=prefixes, mod=mod)]
    if underscore_imports:
        out.append(f"from api.v1.{mod} import {', '.join(sorted(underscore_imports))}  # noqa: F401 - used in decorators")
        out.append("")
    for var, prefix, tag, _ in routers:
        out.append(f'{var} = APIRouter(prefix="{prefix}", tags=["{tag}"])')
    out.append("")
    out.append("")
    out.extend(body_chunks)
    return "\n".join(out).rstrip() + "\n"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for out_file, (mod, routers) in OUTPUTS.items():
        (OUT / f"{out_file}.py").write_text(build_module(mod, routers))
        print(f"[OK] wrote api/v2/funding/{out_file}.py")


if __name__ == "__main__":
    main()
