"""One-shot generator: emit the v2 "European Parliament" domain modules by
copy-pasting the v1 EP route decorators + signatures verbatim and delegating
the body to the v1 handler (single source of truth during v1+v2 coexistence).

Faithful to the established api/v2/legislative/secondary_acts.py pattern:
- decorator (summary + 5-section description + response_model) copied verbatim
- signature copied verbatim so FastAPI re-exposes identical query params
- body replaced with `return await _v1.<func>(<kwargs>)`
- only the 13 EP-domain `/api/v1/<seg>` example URLs are rewritten to
  `/api/v2/parliament/<seg>`; cross-domain refs (publications, procedures,
  press-releases, calendar, commission-register) are left pointing at v1.

Run once from backend/:  python3.12 scripts/_gen_v2_parliament.py
The generated files are reviewed + committed; this script is disposable.
"""
from __future__ import annotations

import ast
import pathlib
import re

V1 = pathlib.Path("api/v1")
OUT = pathlib.Path("api/v2/parliament")

EP_SEGMENTS = (
    "meps", "amendments", "votes", "ep-documents", "reports", "opinions",
    "committees", "texts-adopted", "texts-submitted", "resolutions", "eprs",
    "webstreams", "parliamentary-questions",
)
_URL_RE = re.compile(r"/api/v1/(" + "|".join(EP_SEGMENTS) + r")\b")


def rewrite_urls(text: str) -> str:
    return _URL_RE.sub(r"/api/v2/parliament/\1", text)


# module file -> list of (v1_router_var, v2_router_var, prefix, tag, [func_names])
SPEC = {
    "meps": [
        ("router", "router", "/meps", "v2-parliament-meps",
         ["list_meps", "get_mep"]),
    ],
    "ep_entities": [
        ("amendments_router", "amendments_router", "/amendments", "v2-parliament-amendments",
         ["list_amendments", "get_amendment_detail"]),
        ("votes_router", "votes_router", "/votes", "v2-parliament-votes",
         ["list_votes", "get_vote_detail", "list_member_votes"]),
        ("ep_documents_router", "ep_documents_router", "/ep-documents", "v2-parliament-ep-documents",
         ["list_ep_documents"]),
        ("reports_router", "reports_router", "/reports", "v2-parliament-reports",
         ["list_reports"]),
        ("opinions_router", "opinions_router", "/opinions", "v2-parliament-opinions",
         ["list_opinions"]),
    ],
    "committees": [
        ("router", "router", "/committees", "v2-parliament-committees",
         ["list_committee_work", "list_committee_minutes"]),
    ],
    "texts_adopted": [
        ("texts_adopted_router", "texts_adopted_router", "/texts-adopted", "v2-parliament-texts-adopted",
         ["list_texts_adopted", "get_text_adopted_detail"]),
        ("texts_submitted_router", "texts_submitted_router", "/texts-submitted", "v2-parliament-texts-submitted",
         ["list_texts_submitted"]),
    ],
    "resolutions": [
        ("router", "router", "/resolutions", "v2-parliament-resolutions",
         ["list_resolutions", "get_resolution_detail"]),
    ],
    "eprs": [
        ("router", "router", "/eprs", "v2-parliament-eprs",
         ["list_eprs", "get_eprs_detail"]),
    ],
    "webstreams": [
        ("router", "router", "/webstreams", "v2-parliament-webstreams",
         ["list_webstreams", "get_webstream_detail", "get_webstreams_for_procedure"]),
    ],
    "w4_endpoints": [
        ("parl_q_router", "parl_q_router", "/parliamentary-questions", "v2-parliament-parliamentary-questions",
         ["list_parliamentary_questions", "get_parl_question_detail"]),
    ],
}

# output filename per v1 module (mirror v1 names; w4 -> parliamentary_questions)
OUT_NAME = {
    "meps": "meps",
    "ep_entities": "ep_entities",
    "committees": "committees",
    "texts_adopted": "texts_adopted",
    "resolutions": "resolutions",
    "eprs": "eprs",
    "webstreams": "webstreams",
    "w4_endpoints": "parliamentary_questions",
}

PREAMBLE = '''"""European Parliament domain — {paths}.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.{mod}); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import {mod} as _v1
from api.v1.{mod} import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints

'''


def param_names(fn: ast.AsyncFunctionDef) -> list[str]:
    a = fn.args
    names = [p.arg for p in (a.posonlyargs + a.args + a.kwonlyargs)]
    return names


def build_module(mod: str, routers: list) -> str:
    src = (V1 / f"{mod}.py").read_text()
    tree = ast.parse(src)
    lines = src.splitlines()
    funcs = {n.name: n for n in ast.walk(tree)
             if isinstance(n, ast.AsyncFunctionDef)}

    prefixes = " and ".join(f"/api/v2/parliament{p}/*" for _, _, p, _, _ in routers)
    out = [PREAMBLE.format(paths=prefixes, mod=mod)]

    # router declarations (after import *, so they shadow the v1 ones)
    for _v1var, v2var, prefix, tag, _ in routers:
        out.append(f'{v2var} = APIRouter(prefix="{prefix}", tags=["{tag}"])\n')
    out.append("")

    for v1var, v2var, _prefix, _tag, fnames in routers:
        for fname in fnames:
            fn = funcs[fname]
            # decorators (verbatim), rename router var + rewrite EP URLs
            decos = []
            for d in fn.decorator_list:
                seg = ast.get_source_segment(src, d)
                seg = "@" + seg if not seg.startswith("@") else seg
                if v1var != v2var:
                    seg = re.sub(rf"@{v1var}\.", f"@{v2var}.", seg)
                decos.append(rewrite_urls(seg))
            # signature: from `async def` line to line before first body stmt
            sig_start = fn.lineno - 1
            sig_end = fn.body[0].lineno - 1  # exclusive
            signature = "\n".join(lines[sig_start:sig_end])
            # delegating body
            names = param_names(fn)
            call_args = ", ".join(f"{n}={n}" for n in names)
            body = f"    return await _v1.{fname}({call_args})"
            out.append("\n".join(decos))
            out.append(signature)
            out.append(body)
            out.append("")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for mod, routers in SPEC.items():
        code = build_module(mod, routers)
        (OUT / f"{OUT_NAME[mod]}.py").write_text(code)
        print(f"[OK] wrote api/v2/parliament/{OUT_NAME[mod]}.py")


if __name__ == "__main__":
    main()
