"""
Load Demo EU Data

Populates vector database with real EU legislation examples for testing.
This provides immediate functionality while scrapers are being updated.

Contains:
- AI Act (Regulation 2024/1689)
- GDPR (Regulation 2016/679)
- Digital Services Act (Regulation 2022/2065)
- Digital Markets Act (Regulation 2022/1925)
- And more key EU legislation

Usage:
    python3.12 -m backend.scripts.load_demo_data
"""

import asyncio
import sys
from datetime import datetime
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

sys.path.insert(0, '/Users/victorsole/Documents/GitHub/brubru')

from backend.services.vector_db.vector_store import get_vector_store
from backend.services.vector_db.embeddings_service import get_embeddings_service


# Real EU Legislation Data
DEMO_LEGISLATION = [
    {
        "celex": "32024R1689",
        "title": "Regulation (EU) 2024/1689 on Artificial Intelligence (AI Act)",
        "document_type": "regulation",
        "date": "2024-06-13",
        "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
        "summary": """The AI Act establishes harmonized rules on artificial intelligence.
        It prohibits certain AI practices, sets requirements for high-risk AI systems,
        and imposes obligations on general-purpose AI models. The regulation entered into
        force on 1 August 2024 with phased implementation: prohibitions effective from
        2 February 2025, general-purpose AI obligations from 2 August 2025, and full
        compliance for high-risk systems by 2 August 2027.""",
        "subjects": ["artificial intelligence", "AI regulation", "digital policy", "fundamental rights"]
    },
    {
        "celex": "32016R0679",
        "title": "Regulation (EU) 2016/679 on the protection of natural persons (GDPR)",
        "document_type": "regulation",
        "date": "2016-04-27",
        "url": "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
        "summary": """The General Data Protection Regulation (GDPR) establishes rules on the
        protection of natural persons with regard to the processing of personal data and
        rules relating to the free movement of personal data. It applies since 25 May 2018
        and grants individuals rights including access, rectification, erasure, and data
        portability. Organizations must implement privacy by design, conduct impact assessments
        for high-risk processing, and may face fines up to €20 million or 4% of global turnover.""",
        "subjects": ["data protection", "privacy", "personal data", "fundamental rights", "GDPR"]
    },
    {
        "celex": "32022R2065",
        "title": "Regulation (EU) 2022/2065 on a Single Market For Digital Services (Digital Services Act)",
        "document_type": "regulation",
        "date": "2022-10-19",
        "url": "https://eur-lex.europa.eu/eli/reg/2022/2065/oj",
        "summary": """The Digital Services Act (DSA) establishes harmonized rules on the provision
        of intermediary services in the internal market. It creates due diligence obligations for
        digital services, including measures to counter illegal content, transparent content moderation,
        and user protection. Very Large Online Platforms (VLOPs) face additional obligations including
        systemic risk assessments. The DSA applies since 17 February 2024.""",
        "subjects": ["digital services", "online platforms", "content moderation", "illegal content", "DSA"]
    },
    {
        "celex": "32022R1925",
        "title": "Regulation (EU) 2022/1925 on contestable and fair markets in the digital sector (Digital Markets Act)",
        "document_type": "regulation",
        "date": "2022-09-14",
        "url": "https://eur-lex.europa.eu/eli/reg/2022/1925/oj",
        "summary": """The Digital Markets Act (DMA) ensures contestable and fair markets in the
        digital sector by regulating gatekeepers. It designates large platforms as gatekeepers
        based on market position and impact, imposing obligations like interoperability, data
        portability, and prohibitions on self-preferencing. The DMA applies since 2 May 2023,
        with first gatekeeper designations in September 2023 covering Alphabet, Amazon, Apple,
        ByteDance, Meta, and Microsoft.""",
        "subjects": ["digital markets", "gatekeepers", "competition", "big tech", "DMA"]
    },
    {
        "celex": "32023R2854",
        "title": "Regulation (EU) 2023/2854 on harmonised rules on fair access to and use of data (Data Act)",
        "document_type": "regulation",
        "date": "2023-12-13",
        "url": "https://eur-lex.europa.eu/eli/reg/2023/2854/oj",
        "summary": """The Data Act establishes rules on fair access to and use of data, including
        IoT and connected devices data. It grants users rights to access data generated by products,
        enables data sharing between businesses, allows switching between cloud services, and sets
        conditions for public sector data access. The regulation applies from 12 September 2025.""",
        "subjects": ["data sharing", "IoT", "connected devices", "cloud switching", "data economy"]
    },
    {
        "celex": "32022R0868",
        "title": "Regulation (EU) 2022/868 on European data governance (Data Governance Act)",
        "document_type": "regulation",
        "date": "2022-05-30",
        "url": "https://eur-lex.europa.eu/eli/reg/2022/868/oj",
        "summary": """The Data Governance Act fosters data sharing by increasing trust in data
        intermediaries and strengthening data-sharing mechanisms. It establishes conditions for
        public sector body data reuse, creates a notification framework for data intermediation
        services, and promotes data altruism organizations. The DGA applies since 24 September 2023.""",
        "subjects": ["data governance", "data sharing", "data intermediation", "data altruism"]
    },
    {
        "celex": "32024R0903",
        "title": "Regulation (EU) 2024/903 establishing a framework for interoperability (Interoperable Europe Act)",
        "document_type": "regulation",
        "date": "2024-03-13",
        "url": "https://eur-lex.europa.eu/eli/reg/2024/903/oj",
        "summary": """The Interoperable Europe Act establishes a framework to improve interoperability
        of digital public services across the EU. It creates mandatory interoperability assessments
        for new IT systems, establishes the European Interoperability Framework, and promotes reusable
        IT solutions. The regulation applies from 27 March 2024.""",
        "subjects": ["interoperability", "digital public services", "IT systems", "cross-border cooperation"]
    },
    {
        "celex": "32022R2560",
        "title": "Regulation (EU) 2022/2560 on foreign subsidies distorting the internal market",
        "document_type": "regulation",
        "date": "2022-12-14",
        "url": "https://eur-lex.europa.eu/eli/reg/2022/2560/oj",
        "summary": """The Foreign Subsidies Regulation addresses distortions caused by foreign
        subsidies in the EU internal market. It requires notification of foreign financial
        contributions in M&A transactions above €500 million and public procurement above €250 million.
        The Commission can investigate and impose remedies. The regulation applies since 12 July 2023.""",
        "subjects": ["foreign subsidies", "competition", "M&A", "public procurement", "trade"]
    },
    {
        "celex": "32023R1114",
        "title": "Regulation (EU) 2023/1114 on markets in crypto-assets (MiCA)",
        "document_type": "regulation",
        "date": "2023-05-31",
        "url": "https://eur-lex.europa.eu/eli/reg/2023/1114/oj",
        "summary": """The Markets in Crypto-Assets Regulation (MiCA) creates an EU-wide regulatory
        framework for crypto-assets not covered by existing financial services legislation. It
        establishes authorization requirements for crypto-asset service providers, rules for
        stablecoins, and transparency requirements for issuers. MiCA applies progressively from
        June 2024, with full application by December 2024.""",
        "subjects": ["crypto-assets", "cryptocurrencies", "stablecoins", "blockchain", "MiCA"]
    },
    {
        "celex": "32024R1183",
        "title": "Regulation (EU) 2024/1183 on deforestation-free products",
        "document_type": "regulation",
        "date": "2024-04-17",
        "url": "https://eur-lex.europa.eu/eli/reg/2024/1183/oj",
        "summary": """The Deforestation Regulation prohibits placing products on the EU market
        if they are produced on land subject to deforestation after December 2020. It covers
        cattle, cocoa, coffee, palm oil, soya, wood, rubber, and derived products. Operators
        must conduct due diligence including geolocation data. The regulation applies from
        30 December 2024.""",
        "subjects": ["deforestation", "sustainability", "supply chain", "due diligence", "commodities"]
    }
]


DEMO_MEPS = [
    {
        "id": "mep_1",
        "name": "Ursula von der Leyen",
        "country": "Germany",
        "political_group": "EPP - European People's Party",
        "committees": ["President of the European Commission"],
        "email": "ursula.vonDERLEYEN@ec.europa.eu"
    },
    {
        "id": "mep_2",
        "name": "Roberta Metsola",
        "country": "Malta",
        "political_group": "EPP - European People's Party",
        "committees": ["President of the European Parliament"],
        "email": "roberta.METSOLA@europarl.europa.eu"
    },
    {
        "id": "mep_3",
        "name": "Brando Benifei",
        "country": "Italy",
        "political_group": "S&D - Socialists and Democrats",
        "committees": ["AIDA - Artificial Intelligence in the Digital Age", "IMCO - Internal Market and Consumer Protection"],
        "email": "brando.BENIFEI@europarl.europa.eu"
    },
    {
        "id": "mep_4",
        "name": "Dragoș Tudorache",
        "country": "Romania",
        "political_group": "Renew Europe",
        "committees": ["LIBE - Civil Liberties, Justice and Home Affairs", "AIDA - Artificial Intelligence"],
        "email": "dragos.TUDORACHE@europarl.europa.eu"
    },
]


DEMO_PROCEDURES = [
    {
        "reference": "2021/0106(COD)",
        "title": "Artificial Intelligence Act",
        "type": "Ordinary legislative procedure",
        "stage": "Adopted",
        "description": """Legislative procedure for the AI Act. Proposal by European Commission
        in April 2021, amended by European Parliament and Council through extensive trilogues,
        finally adopted in June 2024. The procedure involved the LIBE and IMCO committees as
        co-leads, with opinions from ITRE, CULT, JURI, and others."""
    },
    {
        "reference": "2020/0361(COD)",
        "title": "Digital Services Act",
        "type": "Ordinary legislative procedure",
        "stage": "Adopted",
        "description": """Legislative procedure for the Digital Services Act, part of the
        Digital Services Act Package. Proposed December 2020, adopted October 2022. Led by
        IMCO committee with opinions from LIBE, CULT, ITRE, and JURI."""
    },
    {
        "reference": "2020/0374(COD)",
        "title": "Digital Markets Act",
        "type": "Ordinary legislative procedure",
        "stage": "Adopted",
        "description": """Legislative procedure for the Digital Markets Act regulating
        gatekeepers in digital markets. Proposed December 2020, adopted September 2022.
        Led by ECON committee with opinions from IMCO, ITRE, and LIBE."""
    },
]


DEMO_RSS_ENTRIES = [
    {
        "title": "AI Act enters into force: First-ever comprehensive regulation of artificial intelligence",
        "link": "https://www.europarl.europa.eu/news/en/press-room/20240726IPR24749",
        "published": "2024-08-01",
        "source": "European Parliament",
        "summary": """The AI Act, the world's first comprehensive regulation on artificial
        intelligence, entered into force on 1 August 2024. The regulation will be gradually
        implemented with a ban on certain AI systems from February 2025."""
    },
    {
        "title": "Von der Leyen presents new Commission for 2024-2029",
        "link": "https://www.europarl.europa.eu/news/en/press-room/20240906IPR24749",
        "published": "2024-09-17",
        "source": "European Parliament",
        "summary": """Commission President Ursula von der Leyen presented her team for the
        2024-2029 term, including new portfolios for digital, tech sovereignty, and
        defence preparedness."""
    },
]


async def main():
    """Load demo data into vector database"""
    logger.info("=" * 80)
    logger.info("📚 Loading Demo EU Data")
    logger.info("=" * 80)

    vector_store = get_vector_store()
    embeddings_service = get_embeddings_service()

    # 1. Load Legislation
    logger.info(f"\n📜 Loading {len(DEMO_LEGISLATION)} legislative documents...")

    leg_texts = []
    leg_documents = []

    for doc in DEMO_LEGISLATION:
        text = f"{doc['title']} {doc['summary']}"
        leg_texts.append(text)
        leg_documents.append({
            'id': doc['celex'],
            'text': text,
            'metadata': {
                'celex': doc['celex'],
                'document_type': doc['document_type'],
                'title': doc['title'],
                'date': doc['date'],
                'url': doc['url'],
            }
        })

    logger.info("🔄 Generating embeddings for legislation...")
    leg_embeddings = await embeddings_service.generate_batch_embeddings(leg_texts)

    logger.info("💾 Storing in ChromaDB...")
    vector_store.add_legislation(
        documents=leg_documents,
        embeddings=leg_embeddings
    )
    logger.info(f"✅ Loaded {len(DEMO_LEGISLATION)} legislative documents")

    # 2. Load MEPs
    logger.info(f"\n👥 Loading {len(DEMO_MEPS)} MEP profiles...")

    mep_texts = []
    mep_profiles = []

    for mep in DEMO_MEPS:
        text = f"{mep['name']} {mep['country']} {mep['political_group']} {' '.join(mep['committees'])}"
        mep_texts.append(text)
        mep_profiles.append({
            'id': mep['id'],
            'text': text,
            'metadata': {
                'name': mep['name'],
                'country': mep['country'],
                'political_group': mep['political_group'],
                'committees': ','.join(mep['committees']),
            }
        })

    logger.info("🔄 Generating embeddings for MEPs...")
    mep_embeddings = await embeddings_service.generate_batch_embeddings(mep_texts)

    logger.info("💾 Storing in ChromaDB...")
    vector_store.add_mep_profiles(
        profiles=mep_profiles,
        embeddings=mep_embeddings
    )
    logger.info(f"✅ Loaded {len(DEMO_MEPS)} MEP profiles")

    # 3. Load Procedures
    logger.info(f"\n⚖️  Loading {len(DEMO_PROCEDURES)} legislative procedures...")

    proc_texts = []
    proc_procedures = []

    for proc in DEMO_PROCEDURES:
        text = f"{proc['title']} {proc['reference']} {proc['description']}"
        proc_texts.append(text)
        proc_procedures.append({
            'id': proc['reference'],
            'text': text,
            'metadata': {
                'reference': proc['reference'],
                'title': proc['title'],
                'stage': proc['stage'],
                'type': proc['type'],
            }
        })

    logger.info("🔄 Generating embeddings for procedures...")
    proc_embeddings = await embeddings_service.generate_batch_embeddings(proc_texts)

    logger.info("💾 Storing in ChromaDB...")
    vector_store.add_procedures(
        procedures=proc_procedures,
        embeddings=proc_embeddings
    )
    logger.info(f"✅ Loaded {len(DEMO_PROCEDURES)} procedures")

    # 4. Load RSS Entries
    logger.info(f"\n📰 Loading {len(DEMO_RSS_ENTRIES)} RSS entries...")

    rss_texts = []
    rss_entries_list = []

    for i, entry in enumerate(DEMO_RSS_ENTRIES):
        text = f"{entry['title']} {entry['summary']}"
        rss_texts.append(text)
        rss_entries_list.append({
            'id': f"rss_{i}",
            'text': text,
            'metadata': {
                'title': entry['title'],
                'link': entry['link'],
                'published': entry['published'],
                'source': entry['source'],
            }
        })

    logger.info("🔄 Generating embeddings for RSS entries...")
    rss_embeddings = await embeddings_service.generate_batch_embeddings(rss_texts)

    logger.info("💾 Storing in ChromaDB...")
    vector_store.add_rss_entries(
        entries=rss_entries_list,
        embeddings=rss_embeddings
    )
    logger.info(f"✅ Loaded {len(DEMO_RSS_ENTRIES)} RSS entries")

    # Summary
    logger.info("\n" + "=" * 80)
    logger.info("✅ DEMO DATA LOADED SUCCESSFULLY")
    logger.info("=" * 80)

    total = len(DEMO_LEGISLATION) + len(DEMO_MEPS) + len(DEMO_PROCEDURES) + len(DEMO_RSS_ENTRIES)
    logger.info(f"Total items: {total}")
    logger.info(f"  - {len(DEMO_LEGISLATION)} legislative documents (AI Act, GDPR, DSA, DMA, etc.)")
    logger.info(f"  - {len(DEMO_MEPS)} MEP profiles")
    logger.info(f"  - {len(DEMO_PROCEDURES)} legislative procedures")
    logger.info(f"  - {len(DEMO_RSS_ENTRIES)} RSS entries")

    # Show stats
    stats = vector_store.get_all_stats()
    logger.info("\n📊 Vector Store Statistics:")
    for collection_name, collection_stats in stats['collections'].items():
        logger.info(f"  {collection_name}: {collection_stats['count']} documents")

    logger.info("\n🎯 Next step: Ask the chat 'What's the status of the AI Act?'")
    logger.info("=" * 80)


if __name__ == "__main__":
    asyncio.run(main())
