"""
Add two Brubru-generated documents to the EFPIA demo account
(public-affairs@efpia.eu) Documents tab, to showcase the Document Generator in
the 28 May 2026 pitch:

  1. A position paper on the pharmaceutical legislation revision.
  2. An MEP briefing on the Critical Medicines Act.

Both use the canonical uploaded pattern (document_type='uploaded' with the
semantic type in doc_metadata.original_document_type, generated_by marker) per
memory/feedback_raw_insert_orm_defaults.md, and validate before commit.

Usage:
    cd backend && python3.12 scripts/seed_efpia_demo_generated_docs.py            # dry-run
    cd backend && python3.12 scripts/seed_efpia_demo_generated_docs.py --apply    # write DB
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import uuid

sys.path.insert(0, "/Users/victorsole/Documents/GitHub/brubru/backend")
sys.path.insert(0, "/Users/victorsole/Documents/GitHub/brubru")

from sqlalchemy import text
from dotenv import load_dotenv

load_dotenv("/Users/victorsole/Documents/GitHub/brubru/.env")

from core.database import SessionLocal, engine

engine.echo = False
logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)
for noisy in ("sqlalchemy.engine", "sqlalchemy.engine.Engine", "sqlalchemy.pool"):
    logging.getLogger(noisy).setLevel(logging.WARNING)

DEMO_EMAIL = "public-affairs@efpia.eu"

DOCUMENTS = [
    {
        "title": "Position paper: safeguarding Europe's medicines innovation in the pharmaceutical legislation revision",
        "original_document_type": "position_paper",
        "policy_areas": ["Pharmaceutical Legislation", "Access to Medicines"],
        "tags": ["efpia", "position-paper", "pharma-reform", "brubru-generated"],
        "procedure_reference": "2023/0131(COD)",
        "executive_summary": (
            "EFPIA position on the revision of the EU general pharmaceutical legislation. The "
            "package as provisionally agreed weakens the innovation incentives Europe needs to "
            "remain a global life-sciences hub. This paper sets out eight constructive proposals "
            "that protect patient access without dismantling the research base. Generated by the "
            "Brubru Document Generator on 27 May 2026 from EFPIA published positions."
        ),
        "content": (
            "# Position paper: safeguarding Europe's medicines innovation in the pharmaceutical legislation revision\n\n"
            "_Generated by the Brubru Document Generator, 27 May 2026. Draft for EFPIA Public Affairs review._\n\n"
            "## 1. Why this matters now\n\n"
            "Europe's research-based pharmaceutical industry invests more than EUR 55 billion a year in "
            "research and development in Europe and supports around 950,000 jobs, including some 130,000 "
            "in research. The revision of the general pharmaceutical legislation is the most consequential "
            "rewrite of the framework in two decades. As provisionally agreed, it reduces regulatory data "
            "protection and ties recovery of protection to launch in all Member States within a tight "
            "window that national pricing and reimbursement timelines make practically impossible to meet.\n\n"
            "## 2. The evidence on patient access\n\n"
            "EFPIA's W.A.I.T. Indicator 2025 shows the real problem is not the strength of European "
            "innovation incentives but the speed of national access: a median of 532 days from approval to "
            "patient availability, and 49 percent of new medicines not available across Europe, ranging "
            "from rapid access in the north and west to well over a thousand days in parts of the south and "
            "east. The legislation should target that bottleneck directly rather than penalising the "
            "innovator.\n\n"
            "## 3. Eight constructive proposals\n\n"
            "1. Regulatory optimisation and expedited pathways for high unmet need, with EMA capacity to "
            "match.\n"
            "2. Strengthen, not cut, the baseline of research and development incentives, decoupled from "
            "launch sequencing.\n"
            "3. Tackle access barriers through binding assessment and reimbursement timelines rather than a "
            "launch-in-all-Member-States trigger.\n"
            "4. A patient-centred, litigation-resistant definition of unmet medical need.\n"
            "5. Proportionate supply-chain obligations: shortage notification yes, responsibility-shifting "
            "onto marketing-authorisation holders no.\n"
            "6. Proportionate environmental requirements aligned with established practice, avoiding "
            "duplicative reporting.\n"
            "7. A meaningful and transferable antimicrobial-resistance incentive; a sub-economic voucher "
            "will not fix the pipeline gap.\n"
            "8. Simplified orphan and paediatric incentives that cut administrative burden while keeping the "
            "operational mix.\n\n"
            "## 4. The ask\n\n"
            "EFPIA asks co-legislators to use the implementing and delegated acts, and the formal-adoption "
            "window, to restore a globally competitive incentive framework while delivering faster, fairer "
            "patient access. The two goals are complementary, not opposed.\n"
        ),
    },
    {
        "title": "MEP briefing: the Critical Medicines Act and what it means for European patients",
        "original_document_type": "mep_briefing",
        "policy_areas": ["Critical Medicines and Shortages", "Access to Medicines", "Pharmaceutical Legislation"],
        "tags": ["efpia", "mep-briefing", "critical-medicines-act", "brubru-generated"],
        "executive_summary": (
            "A two-minute briefing for a Member of the European Parliament on the Critical Medicines Act: "
            "what it does, where the file stands, and EFPIA's five priorities for a workable implementation. "
            "Generated by the Brubru Document Generator on 27 May 2026."
        ),
        "content": (
            "# MEP briefing: the Critical Medicines Act\n\n"
            "_Generated by the Brubru Document Generator, 27 May 2026. One-page briefing for a meeting with an MEP._\n\n"
            "## What it is\n\n"
            "The Critical Medicines Act is the EU's response to persistent shortages of essential medicines. "
            "It aims to strengthen and diversify supply, support European manufacturing of critical molecules, "
            "and give the Union tools to anticipate and manage shortages. A provisional political agreement "
            "was reached in May 2026, with the rapporteur Tomislav Sokol of the EPP.\n\n"
            "## Why EFPIA supports the objective\n\n"
            "No patient should go without an essential medicine. EFPIA members are part of the solution: the "
            "industry supports measures that improve supply security, provided they are evidence-based and do "
            "not duplicate the obligations already created by the pharmaceutical legislation revision.\n\n"
            "## EFPIA's five priorities for implementation\n\n"
            "1. Target genuinely critical molecules, using a clear and stable criticality methodology.\n"
            "2. Make security-of-supply incentives, not only obligations, the core of the instrument.\n"
            "3. Use procurement and Important Projects of Common European Interest to rebuild European "
            "manufacturing capacity for critical inputs.\n"
            "4. Keep reporting requirements proportionate and aligned with existing shortage-notification "
            "duties, avoiding a second parallel regime.\n"
            "5. Coordinate with the EMA and the Medicines Shortages Steering Group so that data flows once and "
            "is used many times.\n\n"
            "## The one line to remember\n\n"
            "The Critical Medicines Act will work if it pairs obligations with real incentives to make and "
            "hold stock of essential medicines in Europe. EFPIA stands ready to help make that the case.\n"
        ),
    },
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()
    apply = args.apply

    logger.info("=" * 78)
    logger.info(f"Add Brubru-generated docs to {DEMO_EMAIL} - {'APPLY' if apply else 'DRY RUN'}")
    logger.info("=" * 78)

    db = SessionLocal()
    try:
        user_id = db.execute(text("SELECT id::text FROM users WHERE email=:e"), {"e": DEMO_EMAIL}).scalar()
        if not user_id:
            raise RuntimeError(f"Demo user {DEMO_EMAIL} not found.")

        for d in DOCUMENTS:
            exists = db.execute(
                text("SELECT 1 FROM user_documents WHERE user_id=:u AND title=:t"),
                {"u": user_id, "t": d["title"]},
            ).first()
            if exists:
                logger.info(f"  [doc] SKIP '{d['title'][:60]}'")
                continue
            meta = {
                "original_document_type": d["original_document_type"],
                "generated_by": "brubru_document_generator",
                "generated_at": "2026-05-27",
            }
            if apply:
                db.execute(
                    text(
                        """
                        INSERT INTO user_documents (
                            id, user_id, document_type, title, content,
                            procedure_reference, policy_areas, tags, executive_summary,
                            doc_metadata, include_in_ai_context, is_private,
                            version, view_count, is_featured, created_at, updated_at
                        ) VALUES (
                            :id, :u, 'uploaded', :title, :content,
                            :proc, :areas, :tags, :exec_sum,
                            CAST(:meta AS jsonb), true, true,
                            1, 0, true, NOW(), NOW()
                        )
                        """
                    ),
                    {
                        "id": str(uuid.uuid4()),
                        "u": user_id,
                        "title": d["title"],
                        "content": d["content"],
                        "proc": d.get("procedure_reference"),
                        "areas": d["policy_areas"],
                        "tags": d["tags"],
                        "exec_sum": d["executive_summary"],
                        "meta": json.dumps(meta),
                    },
                )
                logger.info(f"  [doc] CREATE [{d['original_document_type']:<14}] '{d['title'][:58]}'")
            else:
                logger.info(f"  [doc] WOULD CREATE [{d['original_document_type']:<14}] '{d['title'][:58]}'")

        if apply:
            from scripts._validate_user_documents import validate_user_documents_for
            n = validate_user_documents_for(db, user_id)
            logger.info(f"  [validate] {n} user_documents rows round-trip cleanly")
            db.commit()
            logger.info("\n[OK] committed.")
        else:
            db.rollback()
            logger.info("\n[OK] dry-run only.")
    except Exception as e:
        db.rollback()
        logger.exception(f"FAILED: {e}")
        sys.exit(1)
    finally:
        db.close()


if __name__ == "__main__":
    main()
