#!/usr/bin/env python3
"""
Phase 4 of docs/applications/euvoc.md — CDM ontology snapshot.

Greps the codebase for every `cdm:*` predicate Brubru's SPARQL clients
actually use, queries the live Cellar SPARQL endpoint to confirm each
predicate has a non-zero usage count, and writes the result to
`docs/ontologies/cdm/cdm-brubru-subset.ttl`.

Run:
    python3.12 backend/scripts/snapshot_cdm.py

The drift test (`backend/tests/test_ontology_drift.py`) reads this
snapshot and fails CI when a new cdm: predicate is introduced without
refreshing the snapshot.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "backend"))

from services.api_clients.base_sparql_client import BaseSPARQLClient  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("snapshot-cdm")

SNAPSHOT_PATH = ROOT / "docs" / "ontologies" / "cdm" / "cdm-brubru-subset.ttl"
SPARQL_ENDPOINT = "https://publications.europa.eu/webapi/rdf/sparql"

CDM_NS = "http://publications.europa.eu/ontology/cdm#"

# Predicate names harvested through grep often include partial / stub
# matches when a constant ends with `_`. Filter those out.
_VALID_PREDICATE_RE = re.compile(r"^[a-z][a-zA-Z_\-]+$")
# Predicates that are obvious stubs/comments — never real CDM predicates.
_STUB_PREDICATES = {"act_consolidated_", "resource_legal_", "event_legal_"}


def harvest_predicates() -> List[str]:
    """Use grep to harvest every cdm:foo predicate referenced under backend/."""
    cmd = [
        "grep", "-rEho",
        r"cdm:[a-zA-Z_-]+",
        str(ROOT / "backend" / "services"),
        str(ROOT / "backend" / "api"),
        str(ROOT / "backend" / "scripts"),
    ]
    out = subprocess.run(cmd, check=False, capture_output=True, text=True).stdout
    raw = sorted({ln.strip() for ln in out.splitlines() if ln.strip()})
    cleaned: List[str] = []
    for p in raw:
        local = p[len("cdm:"):]
        if local in _STUB_PREDICATES:
            continue
        if not _VALID_PREDICATE_RE.match(local):
            continue
        cleaned.append(local)
    return cleaned


async def _live_usage(predicate_local: str, client: BaseSPARQLClient) -> int:
    """Count how many triples in the live Cellar use this predicate."""
    q = f"""
        SELECT (COUNT(*) AS ?n) WHERE {{
            ?s <{CDM_NS}{predicate_local}> ?o .
        }}
        LIMIT 1
    """
    try:
        rows = await client.select(q)
        if rows and rows[0].get("n"):
            return int(rows[0]["n"])
    except Exception as e:  # noqa: BLE001
        log.warning("  live usage lookup failed for cdm:%s: %s", predicate_local, e)
    return 0


async def main(skip_live: bool) -> int:
    predicates = harvest_predicates()
    log.info(f"Harvested {len(predicates)} valid cdm: predicates")

    # Live usage counts (skipped via --offline)
    usage: Dict[str, int] = {p: 0 for p in predicates}
    if not skip_live:
        client = BaseSPARQLClient(SPARQL_ENDPOINT, timeout=120)
        try:
            for p in predicates:
                usage[p] = await _live_usage(p, client)
                log.info(f"  cdm:{p:50s}  usage={usage[p]}")
        finally:
            await client.close()

    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)

    now_iso = datetime.now(timezone.utc).isoformat()
    lines = [
        "@prefix cdm:     <http://publications.europa.eu/ontology/cdm#> .",
        "@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix dct:     <http://purl.org/dc/terms/> .",
        "@prefix brubru:  <https://brubru.beresol.eu/ns#> .",
        "@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .",
        "",
        "<https://brubru.beresol.eu/ns/cdm-snapshot> a brubru:OntologySnapshot ;",
        f'    dct:title "CDM ontology subset used by Brubru"@en ;',
        f"    dct:source <{SPARQL_ENDPOINT}> ;",
        f'    dct:date "{now_iso}"^^xsd:dateTime ;',
        f"    brubru:predicateCount {len(predicates)} ;",
        '    rdfs:comment "Snapshot generated by backend/scripts/snapshot_cdm.py. The drift test (test_ontology_drift.py) compares this list against the current codebase grep — any new cdm: predicate not listed here forces an explicit snapshot refresh."@en .',
        "",
        "# ----- predicates -----",
    ]
    for p in predicates:
        lines.append(f"cdm:{p}")
        lines.append(f"    a rdf:Property ;")
        lines.append(f'    rdfs:label "{p}"@en ;')
        lines.append(f"    brubru:liveUsageCount {usage[p]} ;")
        lines.append(f"    brubru:snapshotDate \"{now_iso}\"^^xsd:dateTime .")
        lines.append("")

    SNAPSHOT_PATH.write_text("\n".join(lines))
    log.info(f"Snapshot written: {SNAPSHOT_PATH.relative_to(ROOT)} ({SNAPSHOT_PATH.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--offline", action="store_true", help="Skip live SPARQL usage counts")
    args = parser.parse_args()
    sys.exit(asyncio.run(main(args.offline)))
