#!/usr/bin/env python3.12
"""D1d: Digital Networks Act deep-dive, single-file i18n.

The page's timeline stopped at the LIBE draft opinion of 24 June 2026, marked
active. The only documents whose FIRST appearance in `ep_emeeting_documents`
falls after that are five IMCO amendments, PE791.040 to PE791.044, tabled
TODAY, 10 September 2026.

Nothing is claimed about their contents: the europarl meetdocs host answered
HTTP 202 with a zero-byte body while this ran, which is the WAF signature, so
the PDFs could not be read. Committee, date, kind and reference come from
Brubru's own store.

This deep-dive follows the single-file i18n standard, so the item is added ONCE
with data-i18n keys and the five language strings go into `translations`; the
per-language HTML is regenerated by snapshot_deep_dives.mjs at build time.
"""
import argparse
import pathlib
import re
import sys

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
PAGE = _REPO_ROOT / "frontend" / "public" / "digital-networks-act" / "index.html"
MARK = 'data-brubru-update="2026-09-10"'
OEIL = "https://oeil.europarl.europa.eu/oeil/en/procedure-file?reference=2026/0013(COD)"

EN_DATE = "Thursday 10 September 2026"
EN_TEXT = (
    "<strong>IMCO tables five amendments.</strong> The internal market committee tabled "
    "amendments PE791.040 to PE791.044 on the Digital Networks Act, alongside its draft "
    "opinion. The lead committee ITRE has still not tabled its draft report; the file "
    f'remains in committee per <a href="{OEIL}" target="_blank" class="doc-link">OEIL</a>.'
)

TR = {
 "es": ("Jueves 10 de septiembre de 2026",
   "<strong>IMCO presenta cinco enmiendas.</strong> La comisi&oacute;n de mercado interior present&oacute; las enmiendas PE791.040 a PE791.044 sobre la Ley de Redes Digitales, junto con su proyecto de opini&oacute;n. La comisi&oacute;n competente ITRE sigue sin presentar su proyecto de informe; el expediente permanece en comisi&oacute;n."),
 "ca": ("Dijous 10 de setembre de 2026",
   "<strong>IMCO presenta cinc esmenes.</strong> La comissi&oacute; de mercat interior va presentar les esmenes PE791.040 a PE791.044 sobre la Llei de Xarxes Digitals, juntament amb el seu projecte d'opini&oacute;. La comissi&oacute; competent ITRE encara no ha presentat el seu projecte d'informe; l'expedient continua en comissi&oacute;."),
 "fr": ("Jeudi 10 septembre 2026",
   "<strong>La commission IMCO d&eacute;pose cinq amendements.</strong> La commission du march&eacute; int&eacute;rieur a d&eacute;pos&eacute; les amendements PE791.040 &agrave; PE791.044 sur l'acte sur les r&eacute;seaux num&eacute;riques, avec son projet d'avis. La commission comp&eacute;tente au fond ITRE n'a toujours pas d&eacute;pos&eacute; son projet de rapport ; le dossier reste en commission."),
 "it": ("Gioved&igrave; 10 settembre 2026",
   "<strong>IMCO deposita cinque emendamenti.</strong> La commissione mercato interno ha depositato gli emendamenti da PE791.040 a PE791.044 sulla legge sulle reti digitali, insieme al proprio progetto di parere. La commissione competente ITRE non ha ancora depositato il progetto di relazione; il fascicolo resta in commissione."),
 "nl": ("Donderdag 10 september 2026",
   "<strong>IMCO dient vijf amendementen in.</strong> De commissie interne markt diende de amendementen PE791.040 tot en met PE791.044 op de wet digitale netwerken in, samen met haar ontwerpadvies. De bevoegde commissie ITRE heeft haar ontwerpverslag nog niet ingediend; het dossier blijft in commissie."),
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    text = PAGE.read_text(encoding="utf-8")
    if MARK in text:
        print("  [skip] already updated")
        return 0

    # 1. demote the current active item, add the new one after it
    old_active = '<div class="timeline__item active">'
    if old_active not in text:
        raise SystemExit("[ERROR] no active timeline item found")
    new = text.replace(old_active, '<div class="timeline__item done">', 1)

    item = (f'\n        <div class="timeline__item active" {MARK}>'
            f'<div class="timeline__date" data-i18n="tl_d9_date">{EN_DATE}</div>'
            f'<div class="timeline__text" data-i18n="tl_d9">{EN_TEXT}</div></div>')
    # insert immediately after the (now done) item that used to be active
    i = new.index('<div class="timeline__item done">', new.index('tl_d8_date') - 400)
    end = new.index("</div></div>", i) + len("</div></div>")
    new = new[:end] + item + new[end:]

    # 2. one translation pair per language, inserted beside that language's tl_d8
    added = 0
    for lang, (d, t) in TR.items():
        m = re.search(r"\n\s{2,4}" + lang + r":\s*\{", new)
        if not m:
            print(f"  [warn] no {lang} block"); continue
        block_start = m.end()
        key = re.search(r"tl_d8:\s*'", new[block_start:block_start + 200000])
        if not key:
            print(f"  [warn] {lang}: no tl_d8 anchor"); continue
        at = block_start + key.start()
        # Escape apostrophes: these go inside SINGLE-quoted JS strings, and an
        # unescaped one ends the string. The first run of this script wrote
        # Catalan "d'opinio" and French "l'acte" raw, and check_deep_dives.mjs
        # failed with "translations object does not parse: Unexpected identifier".
        # The gate caught it; a silent break here would have taken every
        # non-English rendering of the page down at build time.
        esc = lambda v: v.replace("\\", "\\\\").replace("'", "\\'")
        new = new[:at] + f"tl_d9_date: '{esc(d)}', tl_d9: '{esc(t)}', " + new[at:]
        added += 1

    if new == text:
        print("  [warn] nothing changed"); return 1
    print(f"  [edit] index.html (+{len(new)-len(text)} chars, {added}/5 languages)")
    if args.apply:
        PAGE.write_text(new, encoding="utf-8")
    print(f"\n{'APPLIED' if args.apply else 'DRY RUN'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
