"""European Parliament-style copy of the v1 European Commission surface — /api/v2/commission/commission-register-documents/*.

LIVE — copy-pasted verbatim from the v1 Commission surface; the body delegates
to the v1 handler so there is exactly one implementation during the v1+v2
coexistence period. Summaries, descriptions and signatures are identical to v1;
only the in-description example URLs are rehomed to /api/v2/commission/*.

Generated by scripts/_gen_v2_commission.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401

from api.v1 import commission_register as _v1_commission_register
from api.v1.commission_register import *  # noqa: F401,F403 - reproduce v1 namespace for get_type_hints

router = APIRouter(prefix="/commission-register-documents", tags=["v2-commission-commission-register"])


@router.get(
    "",
    response_model=PaginatedResponse[CommissionRegisterItem],
    summary="Commission Transparency Register — College agendas, minutes, COM proposals, SWD, impact assessments",
    description="""**What it does**
Returns documents from the Commission Transparency Register — College of Commissioners agendas (tentative + final), College minutes (PV), Commission proposals (COM), staff working documents (SWD), inter-service consultations (SEC), joint proposals (JOIN), and Regulatory Scrutiny Board opinions on impact assessments. Each row exposes the direct PDF URL where available, falling back to the Cellar resolver for adopted acts with a CELEX (returns the canonical EN PDF).

**When to use it**
The single most useful surface for College-of-Commissioners tracking. Filter by `document_register_category=TENTAT_AGENDA_COM_MEETING` to see the upcoming tentative College agendas (which signal what's about to be adopted); by `PV` to see the post-meeting minutes (which confirm what WAS adopted); by `OPIN_IMPACT_ASSESS` to see RSB scrutiny on the file before it lands.

**Input**
- `q` — substring on title + reference.
- `doc_type` — `COM` / `SWD` / `SEC` / `C` / `JOIN` / `OJ` / `PV`.
- `document_register_category` — `AGENDA_COM_MEETING` / `TENTAT_AGENDA_COM_MEETING` / `PV` / `OPIN_IMPACT_ASSESS` / `IMPACT_ASSESS` / `OJ`.
- `dg_responsible` — DG code.
- `procedure_ref` — OEIL reference for cross-linked documents.
- `celex` — legal identifier cross-link.
- `has_pdf` — boolean; restrict to rows with a PDF URL.
- `published_from`, `published_to` (and `published_end` alias).
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/commission/commission-register?document_register_category=TENTAT_AGENDA_COM_MEETING
GET /api/v2/commission/commission-register?q=AI%20Act&doc_type=COM
```

**You get back**
A `PaginatedResponse[CommissionRegisterItem]` envelope. Each item carries reference, title, doc_type, register category, DG, procedure_ref, celex, pdf_url, source_url, dates, and the 5 envelope-level datapoints.

**Data freshness**
Synced every 6 hours (00:00 / 06:00 / 12:00 / 18:00 UTC, hot tier) from ec.europa.eu/transparency/documents-register/. Critical for College tracking — Secretariat-General updates the tentative agenda continuously, and PV minutes appear within days of each College meeting.""",
)
async def list_commission_register_documents(
    request: Request,
    q: Optional[str] = Query(None, description="Substring on title + reference"),
    doc_type: Optional[str] = Query(None, description="COM | SWD | SEC | C | JOIN | OJ | PV"),
    document_register_category: Optional[str] = Query(None, description="AGENDA_COM_MEETING | TENTAT_AGENDA_COM_MEETING | PV | OPIN_IMPACT_ASSESS | IMPACT_ASSESS | OJ"),
    dg_responsible: Optional[str] = Query(None),
    procedure_ref: Optional[str] = Query(None),
    celex: Optional[str] = Query(None),
    has_pdf: Optional[bool] = Query(None, description="If true, only rows with a PDF URL"),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    published_end: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    updated_end: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CommissionRegisterItem]:
    return await _v1_commission_register.list_commission_register_documents(request=request, q=q, doc_type=doc_type, document_register_category=document_register_category, dg_responsible=dg_responsible, procedure_ref=procedure_ref, celex=celex, has_pdf=has_pdf, published_from=published_from, published_to=published_to, published_end=published_end, updated_from=updated_from, updated_to=updated_to, updated_end=updated_end, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)


@router.get(
    "/{reference:path}",
    response_model=CommissionRegisterItem,
    summary="Look up one Commission Register document by its reference (e.g. COM(2025) 87)",
    description="""**What it does**
Fetches a single document from the Commission Transparency Register by its reference (COM, SWD, SEC, JOIN, OJ, or PV number). Returns the same shape as the list endpoint, including the direct PDF URL when available.

**When to use it**
After locating a document via the list endpoint, use this for the deep-link. Common pattern: chat user asks about "COM(2025)87", you call this, get back the PDF URL + body, and embed it in the answer.

**Input**
- `reference` (path) — Commission document reference (e.g. `COM(2025) 87`, `SWD(2024) 123`, `SEC(2026) 2564`, `OJ(2026) 2565`, `PV(2026) 2562`). The `:path` matcher accepts parentheses + spaces verbatim — no URL-encoding needed.

**Try it**
```
GET /api/v2/commission/commission-register/COM(2025) 87
GET /api/v2/commission/commission-register/SEC(2026) 2564
```

**You get back**
A single `CommissionRegisterItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — synced every 6 hours from ec.europa.eu/transparency/documents-register/.""",
)
async def get_commission_register_detail(
    reference: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CommissionRegisterItem:
    return await _v1_commission_register.get_commission_register_detail(reference=reference, body_threshold=body_threshold, user=user, db=db)
