"""European Parliament-style copy of the v1 European Commission surface — /api/v2/commission/commissioners/*.

LIVE — copy-pasted verbatim from the v1 Commission surface; the body delegates
to the v1 handler so there is exactly one implementation during the v1+v2
coexistence period. Summaries, descriptions and signatures are identical to v1;
only the in-description example URLs are rehomed to /api/v2/commission/*.

Generated by scripts/_gen_v2_commission.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401

from api.v1 import metadata as _v1_metadata
from api.v1 import commissioners as _v1_commissioners
from api.v1.metadata import *  # noqa: F401,F403 - reproduce v1 namespace for get_type_hints
from api.v1.metadata import _GenericListResponse  # private names skipped by import *
from api.v1.commissioners import *  # noqa: F401,F403 - reproduce v1 namespace for get_type_hints

router = APIRouter(prefix="/commissioners", tags=["v2-commission-commissioners"])


@router.get(
    "",
    response_model=_GenericListResponse,
    summary="College of Commissioners with portfolios + meeting-agenda URLs (live)",
    description="""**What it does**
Returns all 27 members of the Von der Leyen II College — for each commissioner: a stable slug, full name, portfolio title, country, the bio page on commission.europa.eu, and three working URLs to their meeting agenda: a filtered view of the unified calendar (per-commissioner), the always-working unified-calendar entry point, and a slot for a PDF agenda (most commissioners don't publish one).

**When to use it**
To drive a commissioner dropdown in a UI, fetch a specific commissioner's meeting calendar, or label which commissioner owns a given policy file. The slugs are reused as the `commissioner_slug` filter on `/api/v1/publications`, `/api/v1/calendar`, and `/api/v2/commission/commissioners/{slug}/agenda`.

**Input**
No parameters. Requires an `X-API-Key` header.

**Try it**
```
GET /api/v2/commission/commissioners
```

**You get back**
A `_GenericListResponse` with `total: 27` and `data` (alphabetical by name) — each item has `slug`, `name`, `portfolio`, `country` (ISO-2 lowercase), `bio_url`, `agenda_url` (filtered unified-calendar URL when leader_id known), `agenda_pdf_url`, `unified_calendar_url`. The 5 envelope-level datapoints are null because this is a reference enumeration.

**Data freshness**
Reads from `backend/data/commissioners.json` (hand-curated) + on-demand bio-page hydration to resolve each commissioner's `leader_id` for the filtered-calendar URL (24h cached client-side). Reshuffles or portfolio changes apply on Brubru redeploy after manual JSON update. Typically refreshed weekly via the Friday sweep.""",
)
async def list_commissioners(user: User = Depends(api_user_with_rate_limit)) -> _GenericListResponse:
    return await _v1_metadata.list_commissioners(user=user)


@router.get(
    "/{slug}",
    response_model=CommissionerProfileOut,
    summary="Look up one Commissioner profile by slug — bio + portfolio + agenda URLs",
    description="""**What it does**
Profile-only view of one Commission College member. Returns the same shape as a row from `GET /commissioners` — name, portfolio, country, bio URL, plus three working URLs to their meeting agenda (filtered unified-calendar URL, agenda PDF, unified-calendar entry point). Does NOT return the agenda items themselves — for that, call `GET /commissioners/{slug}/agenda`.

**When to use it**
After locating a commissioner via the list endpoint, use this for the profile-only view (no agenda fetch overhead). Useful when embedding a commissioner card without needing the full meeting list.

**Input**
- `slug` (path) — commissioner slug (stable kebab-case form of their name).

**Try it**
```
GET /api/v2/commission/commissioners/von-der-leyen
GET /api/v2/commission/commissioners/ribera
```

**You get back**
A single `CommissionerProfileOut` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Reads from `backend/data/commissioners.json` (hand-curated) + on-demand bio-page hydration (24h client cache). Refreshed on Brubru redeploy after manual JSON updates.""",
)
async def get_profile(
    request: Request,
    slug: str,
    user: User = Depends(api_user_with_rate_limit),
) -> CommissionerProfileOut:
    return await _v1_commissioners.get_profile(request=request, slug=slug, user=user)


@router.get(
    "/{name}/agenda",
    response_model=PaginatedResponse[AgendaItemOut],
    summary="Calendar events for one Commissioner — meetings, speeches, College sessions",
    description="""**What it does**
Returns the live calendar of meeting events for one Commission College member — meetings with lobbyists / industry / NGOs, public speeches, College sessions, summit attendance. Name resolution is accent-insensitive and accepts the full name, the slug, or known nicknames (e.g. `ribera` → Teresa Ribera).

**When to use it**
For lobbying-transparency work: "who did Ribera meet last month?", "what speeches did the President give in May?", or "show me Hoekstra's upcoming public events". Combined with `/api/v2/commission/meetings`, gives you a full picture of a Commissioner's engagement.

**Input**
- `name` (path) — full name, slug, or nickname (accent-insensitive).
- `date_from`, `date_to` — date filter on agenda items.
- `limit` (default 50, max 200), `page` (1-indexed).

**Try it**
```
GET /api/v2/commission/commissioners/ribera/agenda?date_from=2026-05-01
GET /api/v2/commission/commissioners/Von der Leyen/agenda
```

**You get back**
A `PaginatedResponse[AgendaItemOut]` envelope. Each item carries the meeting date/time, title, location, type (meeting / speech / college session), and participants where available.

**Data freshness**
Live pull from the Commission's calendar items page (commission.europa.eu/about/organisation/college-commissioners/calendar-items-president-and-commissioners_en), with a 24h client cache per commissioner. Commissioners' agendas are updated by their Cabinet within hours of confirmation.""",
)
async def get_agenda(
    request: Request,
    name: str,
    date_from: Optional[date] = Query(None),
    date_to: Optional[date] = Query(None),
    limit: int = Query(50, ge=1, le=200),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[AgendaItemOut]:
    return await _v1_commissioners.get_agenda(request=request, name=name, date_from=date_from, date_to=date_to, limit=limit, page=page, user=user, db=db)
