"""European Parliament-style copy of the v1 European Commission surface — /api/v2/commission/consultations/*.

LIVE — copy-pasted verbatim from the v1 Commission surface; the body delegates
to the v1 handler so there is exactly one implementation during the v1+v2
coexistence period. Summaries, descriptions and signatures are identical to v1;
only the in-description example URLs are rehomed to /api/v2/commission/*.

Generated by scripts/_gen_v2_commission.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401

from api.v1 import consultations as _v1_consultations
from api.v1.consultations import *  # noqa: F401,F403 - reproduce v1 namespace for get_type_hints

router = APIRouter(prefix="/consultations", tags=["v2-commission-consultations"])


@router.get(
    "",
    response_model=PaginatedResponse[ConsultationItem],
    summary="EC HaveYourSay consultations + calls for evidence — open, upcoming, closed, outcome-published",
    description="""**What it does**
Returns the EC's public consultations from HaveYourSay (ec.europa.eu/info/law/better-regulation/have-your-say) — public consultations, calls for evidence, feedback periods, roadmaps, and inception initiatives. Each row carries the initiative_id, title, status, consultation type, the policy area, the responsible DG, the open + close dates, and the URLs to the consultation page + feedback summary.

**When to use it**
For advocacy planning — find open consultations to submit feedback on, track upcoming ones for your sector, or audit which DGs are most consultation-heavy. For per-consultation stakeholder feedback (who responded and what they said), follow up with `/by-initiative/{id}/feedback`.

**Input**
- `q` — substring on title + description.
- `status` — `open` / `upcoming` / `closed` / `outcome_published` / `withdrawn`.
- `consultation_type` — `public_consultation` / `call_for_evidence` / `feedback` / `roadmap` / `initiative`.
- Date + DG filters as standard.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/commission/consultations?status=open&consultation_type=public_consultation
GET /api/v2/commission/consultations?q=AI%20Act
```

**You get back**
A `PaginatedResponse[ConsultationItem]` envelope. Each item carries `initiative_id` (numeric), `title`, `status`, `consultation_type`, `responsible_dg`, `policy_area`, `open_date`, `close_date`, `feedback_count`, `outcome_summary`, plus the 5 envelope-level datapoints.

**Data freshness**
Synced once per day at 04:00 UTC (daily tier) from ec.europa.eu/info/law/better-regulation/have-your-say. Consultations open and close on known schedules; daily sync is sufficient.""",
)
async def list_consultations(
    request: Request,
    q: Optional[str] = Query(None, description="Substring match on title + description"),
    status: Optional[str] = Query(None, description="open | upcoming | closed | outcome_published | withdrawn"),
    consultation_type: Optional[str] = Query(None, description="public_consultation | call_for_evidence | feedback | roadmap | initiative"),
    dg_responsible: Optional[str] = Query(None, description="DG code, e.g. CNECT, JUST"),
    policy_area: Optional[str] = Query(None, description="Single policy area tag"),
    published_from: Optional[date] = Query(None, description="start_date >= value"),
    published_to: Optional[date] = Query(None),
    published_end: Optional[date] = Query(None, description="Alias of published_to. 422 if both differ."),
    updated_from: Optional[datetime] = Query(None, description="last_updated >= value. Returns rows ordered by last_updated desc when set."),
    updated_to: Optional[datetime] = Query(None),
    updated_end: Optional[datetime] = Query(None, description="Alias of updated_to. 422 if both differ."),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[ConsultationItem]:
    return await _v1_consultations.list_consultations(request=request, q=q, status=status, consultation_type=consultation_type, dg_responsible=dg_responsible, policy_area=policy_area, published_from=published_from, published_to=published_to, published_end=published_end, updated_from=updated_from, updated_to=updated_to, updated_end=updated_end, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)


@router.get(
    "/{initiative_id}",
    response_model=ConsultationItem,
    summary="Look up one HaveYourSay consultation by its initiative_id — full description + dates",
    description="""**What it does**
Returns a single HaveYourSay consultation / call for evidence by its initiative_id. Includes the full description (objectives, scope, target group, outcome summary), dates, responsible DG, status, plus the composed body for embedding.

**When to use it**
After locating a consultation via the list endpoint, use this for the full record — particularly when drafting a feedback submission and you need the consultation's stated objectives + scope in front of you.

**Input**
- `initiative_id` (path) — numeric initiative ID (e.g. `13693`). Always numeric — the underlying table has a CHECK constraint that forbids non-numeric values.

**Try it**
```
GET /api/v2/commission/consultations/13693
GET /api/v2/commission/consultations/13687
```

**You get back**
A single `ConsultationItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — synced once per day at 04:00 UTC.""",
)
async def get_consultation_detail(
    initiative_id: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> ConsultationItem:
    return await _v1_consultations.get_consultation_detail(initiative_id=initiative_id, body_threshold=body_threshold, user=user, db=db)


@router.get(
    "/by-initiative/{initiative_id}/feedback",
    response_model=FeedbackEnvelope,
    summary="Stakeholder feedback on a HaveYourSay consultation — live, paginated, with aggregates",
    description="""**What it does**
Returns the stakeholder feedback submitted to the EC HaveYourSay portal for one initiative, plus summary aggregates (totals per country, per stakeholder type) in the same payload — so you get analytics + detail in a single round-trip.

**When to use it**
For consultation-tracking work: "who submitted feedback on the housing-crisis call?", "what's the country breakdown of responses to the AI Act?", or "which industry associations have weighed in?". The aggregates give you the macro view; the paginated feedback array gives you per-response detail.

**Input**
- `initiative_id` (path) — numeric initiative ID. Slug-style call-for-evidence IDs return 422 — only initiatives that accept feedback have numeric IDs.
- Pagination + filter params for the feedback list.

**Try it**
```
GET /api/v2/commission/consultations/by-initiative/13693/feedback?limit=10
```

**You get back**
A `FeedbackEnvelope` extending the standard paginated response, with an additional `aggregates` field carrying totals_by_country, totals_by_stakeholder_type, and overall counts. Each feedback row carries the submitter org/individual, country, stakeholder type, position summary, attachment URLs, and submission date.

**Data freshness**
Live pass-through to the EC HaveYourSay portal, with a 6-hour in-process cache. Feedback closes when the consultation window ends; once closed, the dataset is stable (cache TTL is purely about reducing upstream load).""",
)
async def get_feedback_by_initiative(
    request: Request,
    initiative_id: int,
    limit: int = Query(50, ge=1, le=100, description="Items per page (default 50, max 100)"),
    page: int = Query(1, ge=1),
    country: Optional[str] = Query(None, min_length=3, max_length=3),
    user_type: Optional[str] = Query(None),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> FeedbackEnvelope:
    return await _v1_consultations.get_feedback_by_initiative(request=request, initiative_id=initiative_id, limit=limit, page=page, country=country, user_type=user_type, body_threshold=body_threshold, user=user, db=db)
