"""European Commission infringements: /api/v2/commission/infringements/*.

Backed by the Commission's register of infringement decisions (every decision it has
adopted in infringement procedures against Member States since 1987) and by the
statistics of its 'Implementing EU law' dashboards. Hand-written since 16 Sep 2026:
this module is NOT generated by scripts/_gen_v2_commission.py any more.

  /                         infringement cases (one per infringement number)
  /{case_id}                one case with all its decisions
  /{case_id}/decisions      the decisions of one case
  /decisions                every decision (letter of formal notice, reasoned opinion, ...)
  /decisions/{decision_id}  one decision
  /statistics               the statistics datasets
  /statistics/{dataset}     one dataset (infringements, transposition, pre-infringement dialogues)
  /press-releases[/{ref}]   the Commission press releases about infringements (the
                            collection this path served before 16 Sep 2026)

Tables: infringement_cases, infringement_decisions (migration 233), filled daily by
scripts/sync_infringement_register.py.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request
from fastapi.responses import RedirectResponse
from pydantic import BaseModel, Field
from sqlalchemy import text
from sqlalchemy.orm import Session

from api.v1 import infringements_funding as _v1_infringements_funding
from api.v1._body import body_threshold_param
from api.v1._deps import api_user_with_rate_limit
from api.v1._change_window import SYNC_FIELDS_DOC, SYNC_PARAMS_DOC, UpperBoundDatetime, sql_order, sql_window, validate_window
from api.v1._envelope import PaginatedResponse, build_envelope
from api.v1.infringements_funding import InfringementItem
from core.database import get_db
from models.user import User
from services.infringements import implementing_eu_law as iel

router = APIRouter(prefix="/infringements", tags=["v2-commission-infringements"])

_SOURCE = ("Synced daily from the European Commission's register of infringement decisions "
           "(ec.europa.eu/implementing-eu-law/search-infringement-decisions), which covers every "
           "decision since 1987. The Commission adopts infringement decisions in monthly packages.")
_CASE_TYPES = {
    "NCM": "Non-communication", "NCF": "Non-conformity", "BAD": "Bad application",
    "REG": "Regulations - treaties - decisions",
}
_REGISTER_MEMBER_STATES = {**iel.MEMBER_STATES, "UK": "United Kingdom"}


# --------------------------------------------------------------------------- models
class _DataPoints(BaseModel):
    """The five Brubru datapoints, present even when null."""
    public_url: Optional[str] = Field(None, description="The item's page on the Commission's website: its press release, memo or Court of Justice case when it has one, otherwise the register search page (see `public_url_kind`).")
    body_txt: Optional[str] = Field(None, description="Plain-text body composed from the record (full on detail endpoints; null on lists).")
    body_html: Optional[str] = Field(None, description="HTML body composed from the record (full on detail endpoints; null on lists).")
    document_date: Optional[date] = Field(None, description="The item's own date: the decision date, or a case's latest decision date.")
    creation_date: Optional[datetime] = Field(None, description="When Brubru first recorded the item.")
    updated_date: Optional[datetime] = Field(None, description="When the item's content last changed in Brubru (a new decision in the case, a new press release, a closure...). A daily re-sync that finds the same content does not move it.")


class InfringementDecision(_DataPoints):
    id: int = Field(..., description="Brubru decision id (use it on /decisions/{decision_id}).")
    case_id: Optional[int] = Field(None, description="Brubru id of the case this decision belongs to.")
    infringement_number: str = Field(..., description="The Commission's case number, e.g. INFR(2026)0352.")
    member_state: Optional[str] = Field(None, description="Member State code as the Commission writes it (EL for Greece, UK for the United Kingdom).")
    member_state_name: Optional[str] = None
    decision_date: date
    decision_type: str = Field(..., description="The decision as the register names it, e.g. 'Reasoned opinion Art. 258 TFEU'.")
    decision_type_code: Optional[str] = None
    decision_category: Optional[str] = Field(None, description="LFN (letter of formal notice), ALFN (additional LFN), RO (reasoned opinion), ARO, RTC (referral to Court), CLOSURES, and others.")
    case_type: Optional[str] = Field(None, description="Non-communication | Non-conformity | Bad application | Regulations - treaties - decisions.")
    lead_dg: Optional[str] = None
    lead_dg_code: Optional[str] = None
    title: Optional[str] = Field(None, description="The act or subject the case concerns, as the register titles it.")
    active_case: Optional[bool] = Field(None, description="True while the case is open.")
    non_communication: Optional[bool] = None
    policy_areas: List[str] = Field(default_factory=list)
    press_release: Optional[str] = None
    press_release_url: Optional[str] = None
    memo: Optional[str] = None
    memo_url: Optional[str] = None
    court_case: Optional[str] = Field(None, description="Court of Justice case number, e.g. C-375/92.")
    court_case_url: Optional[str] = None
    public_url_kind: Optional[str] = Field(None, description="What `public_url` points at: press_release | memo | court_case | register_search.")


class InfringementDecisionDetail(InfringementDecision):
    has_body: bool = False
    body_source: Optional[str] = None


class InfringementCase(_DataPoints):
    id: int = Field(..., description="Brubru case id (use it on /{case_id}; the infringement number works too).")
    infringement_number: str = Field(..., description="The Commission's case number, e.g. INFR(2026)0352.")
    member_state: Optional[str] = Field(None, description="Member State code as the Commission writes it (EL for Greece, UK for the United Kingdom).")
    member_state_name: Optional[str] = None
    active_case: Optional[bool] = Field(None, description="True while the case is open.")
    case_type: Optional[str] = None
    non_communication: Optional[bool] = None
    lead_dg: Optional[str] = None
    lead_dg_code: Optional[str] = None
    title: Optional[str] = None
    first_decision_date: Optional[date] = None
    latest_decision_date: Optional[date] = None
    latest_decision_type: Optional[str] = None
    latest_decision_category: Optional[str] = None
    decision_count: int = 0
    policy_areas: List[str] = Field(default_factory=list)
    court_cases: List[str] = Field(default_factory=list)
    press_release_urls: List[str] = Field(default_factory=list)
    public_url_kind: Optional[str] = None


class InfringementCaseDetail(InfringementCase):
    has_body: bool = False
    body_source: Optional[str] = None
    decisions: List[InfringementDecision] = Field(default_factory=list, description="Every decision in the case, oldest first.")


class StatisticsPoint(BaseModel):
    label: str
    value: Optional[float] = None


class StatisticsSeries(BaseModel):
    name: Optional[str] = None
    points: List[StatisticsPoint] = Field(default_factory=list)


class StatisticsRow(BaseModel):
    series: Optional[str] = None
    label: str
    value: Optional[float] = None


class InfringementStatistics(_DataPoints):
    dataset: str
    section: str = Field(..., description="infringements | transposition | pre_infringement_dialogues")
    title: str
    description: str
    unit: str
    parameters: dict = Field(default_factory=dict, description="The parameters the figures were computed with, defaults included.")
    series: List[StatisticsSeries] = Field(default_factory=list)
    rows: List[StatisticsRow] = Field(default_factory=list, description="The same figures as flat rows (series, label, value).")
    source_url: Optional[str] = Field(None, description="The Commission endpoint the figures were read from.")
    has_body: bool = False


class StatisticsDatasetItem(_DataPoints):
    dataset: str
    section: str
    title: str
    description: str
    unit: str
    parameters: List[str] = Field(default_factory=list, description="The query parameters this dataset accepts.")


# --------------------------------------------------------------------------- helpers
_CASE_COLS = ("id, infringement_number, member_state, member_state_name, active_case, case_type, non_communication, "
              "lead_dg, lead_dg_code, title, first_decision_date, latest_decision_date, latest_decision_type, "
              "latest_decision_category, decision_count, policy_areas, court_cases, press_release_urls, public_url, "
              "public_url_kind, creation_date, content_updated_at AS updated_date")
_DECISION_COLS = ("d.id, c.id AS case_id, d.infringement_number, d.member_state, d.member_state_name, d.decision_date, "
                  "d.decision_type, d.decision_type_code, d.decision_category, d.case_type, d.lead_dg, d.lead_dg_code, "
                  "d.title, d.active_case, d.non_communication, d.policy_areas, d.press_release, d.press_release_url, "
                  "d.memo, d.memo_url, d.court_case, d.court_case_url, d.public_url, d.public_url_kind, d.creation_date, d.content_updated_at AS updated_date")


def _bad_request(message: str) -> HTTPException:
    return HTTPException(status_code=422, detail={"error": message, "reason_code": "invalid_query"})


def _not_found(resource: str, value: str) -> HTTPException:
    return HTTPException(status_code=404, detail={"error": f"{resource} not found: {value}",
                                                  "reason_code": "not_found", "resource": resource, "id": value})


def _member_state(value: Optional[str]) -> Optional[str]:
    if value is None or not value.strip():
        return None
    code = iel.MEMBER_STATE_ALIASES.get(value.strip().upper(), value.strip().upper())
    if code == "GB":
        code = "UK"
    if code not in _REGISTER_MEMBER_STATES:
        raise _bad_request(f"member_state must be one of {', '.join(sorted(_REGISTER_MEMBER_STATES))} (Greece is EL)")
    return code


def _case_type(value: Optional[str]) -> Optional[str]:
    if value is None or not value.strip():
        return None
    v = value.strip()
    if v.upper() in _CASE_TYPES:
        return _CASE_TYPES[v.upper()]
    for label in _CASE_TYPES.values():
        if label.lower() == v.lower():
            return label
    raise _bad_request(f"case_type must be one of {', '.join(_CASE_TYPES)} "
                       "(non-communication, non-conformity, bad application, regulations/treaties/decisions)")


def _normalise_number(value: str) -> str:
    return "".join(value.split()).upper()


def _range(where: list, params: dict, column: str, start: Optional[date], end: Optional[date]) -> None:
    if start and end and start > end:
        raise _bad_request("decision_from is after decision_to")
    if start:
        where.append(f"{column} >= :d_from"); params["d_from"] = start
    if end:
        where.append(f"{column} <= :d_to"); params["d_to"] = end


def _decision_from_row(r) -> InfringementDecision:
    r = dict(r)
    r["policy_areas"] = list(r.get("policy_areas") or [])
    r["document_date"] = r["decision_date"]
    return InfringementDecision(**r)


# --------------------------------------------------------------------------- cases
@router.get(
    "",
    response_model=PaginatedResponse[InfringementCase],
    summary="Infringement cases against Member States (open and closed, since 1987)",
    description=f"""**What it does**
Lists infringement cases: the legal proceedings the European Commission opens when it considers a Member State has failed to apply EU law. One item per case, with the Member State, the type of infringement (non-communication of transposition measures, non-conformity, bad application), the Commission department in charge, the subject, whether the case is still open, and its latest step (letter of formal notice, reasoned opinion, referral to the Court of Justice, closure).

**When to use it**
To see which Member States face proceedings on a topic, how far each case has gone, and which are still open. Filter by `member_state`, `active`, `case_type`, `lead_dg` or `policy_area`, search the subject with `q`, or window on the latest decision date.

**Input**
- `member_state`: code as the Commission writes it, e.g. `PL`, `EL` (Greece; `GR` is accepted), `UK`.
- `active`: `true` for open cases, `false` for closed ones.
- `case_type`: `NCM` (non-communication), `NCF` (non-conformity), `BAD` (bad application), `REG` (regulations, Treaties and decisions).
- `lead_dg`: department code, e.g. `ENV`, `GROW`, `MOVE`.
- `policy_area`: text contained in a policy area, e.g. `waste`.
- `latest_decision_category`: e.g. `RTC` for cases whose latest step is a referral to the Court.
- `q`: words in the subject, or an infringement number.
- `decision_from`, `decision_to`: bounds on the latest decision date (YYYY-MM-DD).
{SYNC_PARAMS_DOC}
- `order`: `recent` (default, latest decision first), `oldest`, or a sync order: `updated_asc`, `updated_desc`, `created_asc`, `created_desc`. `limit` (default 100, max 500), `page`.

**Try it**
```
GET /api/v2/commission/infringements?member_state=PL&active=true
GET /api/v2/commission/infringements?case_type=NCM&lead_dg=ENV&active=true
GET /api/v2/commission/infringements?q=nitrates
GET /api/v2/commission/infringements?updated_from=2026-09-21&order=updated_asc&limit=500
```

**You get back**
A paginated list of cases. Each carries `id`, `infringement_number`, `member_state`, `active_case`, `case_type`, `lead_dg`, `title`, `first_decision_date`, `latest_decision_date`, `latest_decision_type`, `decision_count`, `court_cases`, `press_release_urls`, and the five datapoints (`public_url`, `body_txt`, `body_html`, `document_date`, `creation_date`; the bodies are on the detail endpoint). {SYNC_FIELDS_DOC}

**Data freshness**
{_SOURCE}""",
)
def list_cases(
    request: Request,
    member_state: Optional[str] = Query(None, description="Member State code, e.g. PL, EL (Greece), UK."),
    active: Optional[bool] = Query(None, description="true for open cases, false for closed ones."),
    case_type: Optional[str] = Query(None, description="NCM | NCF | BAD | REG."),
    lead_dg: Optional[str] = Query(None, description="Commission department code, e.g. ENV."),
    policy_area: Optional[str] = Query(None, description="Text contained in a policy area."),
    latest_decision_category: Optional[str] = Query(None, description="e.g. LFN, RO, RTC, CLOSURES."),
    q: Optional[str] = Query(None, description="Words in the subject, or an infringement number."),
    decision_from: Optional[date] = Query(None, description="Latest decision on or after (YYYY-MM-DD)."),
    decision_to: Optional[date] = Query(None, description="Latest decision on or before (YYYY-MM-DD)."),
    created_from: Optional[datetime] = Query(None, description="First recorded by Brubru on or after (ISO date or datetime)."),
    created_to: Optional[UpperBoundDatetime] = Query(None, description="First recorded on or before; a bare date covers the whole day."),
    updated_from: Optional[datetime] = Query(None, description="Content last changed on or after. The incremental-sync filter."),
    updated_to: Optional[UpperBoundDatetime] = Query(None, description="Content last changed on or before; a bare date covers the whole day."),
    order: str = Query("recent", pattern="^(recent|oldest|updated_asc|updated_desc|created_asc|created_desc)$"),
    limit: int = Query(100, ge=1, le=500, description="Items per page (default 100, max 500)."),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[InfringementCase]:
    where, params = [], {}
    ms = _member_state(member_state)
    if ms:
        where.append("member_state = :ms"); params["ms"] = ms
    if active is not None:
        where.append("active_case = :active"); params["active"] = active
    ct = _case_type(case_type)
    if ct:
        where.append("case_type = :ct"); params["ct"] = ct
    if lead_dg:
        where.append("upper(lead_dg_code) = :dg"); params["dg"] = lead_dg.strip().upper()
    if policy_area:
        where.append("EXISTS (SELECT 1 FROM unnest(policy_areas) p WHERE p ILIKE :pa)"); params["pa"] = f"%{policy_area.strip()}%"
    if latest_decision_category:
        where.append("latest_decision_category = :cat"); params["cat"] = latest_decision_category.strip().upper()
    if q:
        where.append("(title ILIKE :q OR infringement_number ILIKE :qn)")
        params["q"] = f"%{q.strip()}%"; params["qn"] = f"%{_normalise_number(q)}%"
    _range(where, params, "latest_decision_date", decision_from, decision_to)
    sql_window(where, params, validate_window(created_from, created_to, updated_from, updated_to),
               "creation_date", "content_updated_at")
    clause = ("WHERE " + " AND ".join(where)) if where else ""
    direction = "DESC" if order == "recent" else "ASC"
    ordering = sql_order(order, "creation_date", "content_updated_at") \
        or f"latest_decision_date {direction} NULLS LAST, id {direction}"
    total = int(db.execute(text(f"SELECT count(*) FROM infringement_cases {clause}"), params).scalar() or 0)
    rows = db.execute(text(
        f"SELECT {_CASE_COLS} FROM infringement_cases {clause} "
        f"ORDER BY {ordering} LIMIT :limit OFFSET :offset"),
        {**params, "limit": limit, "offset": (page - 1) * limit}).mappings().all()
    items = []
    for r in rows:
        r = dict(r)
        for k in ("policy_areas", "court_cases", "press_release_urls"):
            r[k] = list(r.get(k) or [])
        r["document_date"] = r["latest_decision_date"]
        items.append(InfringementCase(**r))
    return build_envelope(items, total=total, page=page, limit=limit,
                          published_from=decision_from, published_to=decision_to,
                          op_core_title="Infringement cases", op_core_type="Infringement case",
                          op_core_identifier=str(request.url))


# --------------------------------------------------------------------------- decisions
@router.get(
    "/decisions",
    response_model=PaginatedResponse[InfringementDecision],
    summary="Infringement decisions adopted by the Commission (letters of formal notice, reasoned opinions, Court referrals, closures)",
    description=f"""**What it does**
Lists every decision the European Commission has adopted in infringement procedures since 1987: letters of formal notice, additional letters, reasoned opinions, referrals to the Court of Justice (with or without financial sanctions) and closures. One item per decision, linked to its case, with the press release, memo or Court case when there is one.

**When to use it**
To follow the Commission's monthly infringement packages, list the referrals to the Court for one Member State, or trace how a type of decision has been used over time.

**Input**
- `member_state`: e.g. `IT`, `EL` (Greece), `UK`.
- `infringement_number`: one case, e.g. `INFR(2026)0352`.
- `decision_category`: `LFN` (letter of formal notice), `ALFN`, `RO` (reasoned opinion), `ARO`, `RTC` (referral to Court), `CLOSURES`, `NON_COM_RTC`, `SECOND_RTC`, and others.
- `decision_type`: words in the decision name, e.g. `260(3)` for referrals with financial sanctions.
- `case_type`: `NCM` | `NCF` | `BAD` | `REG`. `lead_dg`: e.g. `ENV`. `policy_area`: text.
- `active`: `true` for decisions in open cases. `with_press_release`: `true` for decisions announced in a press release.
- `q`: words in the subject. `decision_from`, `decision_to`: decision date bounds (YYYY-MM-DD).
{SYNC_PARAMS_DOC}
- `order`: `recent` (default), `oldest`, or a sync order: `updated_asc`, `updated_desc`, `created_asc`, `created_desc`. `limit` (default 100, max 500), `page`.

**Try it**
```
GET /api/v2/commission/infringements/decisions?decision_from=2026-07-01&decision_category=RTC
GET /api/v2/commission/infringements/decisions?member_state=DE&decision_category=RO
GET /api/v2/commission/infringements/decisions?created_from=2026-09-21&order=created_asc&limit=500
```

**You get back**
A paginated list of decisions: `id`, `case_id`, `infringement_number`, `member_state`, `decision_date`, `decision_type`, `decision_category`, `case_type`, `lead_dg`, `title`, `active_case`, `press_release_url`, `memo_url`, `court_case`, `court_case_url`, `public_url_kind`, and the five datapoints (bodies on the detail endpoint). {SYNC_FIELDS_DOC}

**Data freshness**
{_SOURCE}""",
)
def list_decisions(
    request: Request,
    member_state: Optional[str] = Query(None, description="Member State code, e.g. IT, EL (Greece), UK."),
    infringement_number: Optional[str] = Query(None, description="One case, e.g. INFR(2026)0352."),
    decision_category: Optional[str] = Query(None, description="LFN, ALFN, RO, ARO, RTC, CLOSURES, ..."),
    decision_type: Optional[str] = Query(None, description="Words in the decision name, e.g. 260(3)."),
    case_type: Optional[str] = Query(None, description="NCM | NCF | BAD | REG."),
    lead_dg: Optional[str] = Query(None, description="Commission department code, e.g. ENV."),
    policy_area: Optional[str] = Query(None, description="Text contained in a policy area."),
    active: Optional[bool] = Query(None, description="true for decisions in open cases."),
    with_press_release: Optional[bool] = Query(None, description="true for decisions announced in a press release."),
    q: Optional[str] = Query(None, description="Words in the subject."),
    decision_from: Optional[date] = Query(None, description="Decided on or after (YYYY-MM-DD)."),
    decision_to: Optional[date] = Query(None, description="Decided on or before (YYYY-MM-DD)."),
    created_from: Optional[datetime] = Query(None, description="First recorded by Brubru on or after (ISO date or datetime)."),
    created_to: Optional[UpperBoundDatetime] = Query(None, description="First recorded on or before; a bare date covers the whole day."),
    updated_from: Optional[datetime] = Query(None, description="Content last changed on or after. The incremental-sync filter."),
    updated_to: Optional[UpperBoundDatetime] = Query(None, description="Content last changed on or before; a bare date covers the whole day."),
    order: str = Query("recent", pattern="^(recent|oldest|updated_asc|updated_desc|created_asc|created_desc)$"),
    limit: int = Query(100, ge=1, le=500, description="Items per page (default 100, max 500)."),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[InfringementDecision]:
    where, params = [], {}
    ms = _member_state(member_state)
    if ms:
        where.append("d.member_state = :ms"); params["ms"] = ms
    if infringement_number:
        where.append("d.infringement_number = :num"); params["num"] = _normalise_number(infringement_number)
    if decision_category:
        where.append("d.decision_category = :cat"); params["cat"] = decision_category.strip().upper()
    if decision_type:
        where.append("d.decision_type ILIKE :dt"); params["dt"] = f"%{decision_type.strip()}%"
    ct = _case_type(case_type)
    if ct:
        where.append("d.case_type = :ct"); params["ct"] = ct
    if lead_dg:
        where.append("upper(d.lead_dg_code) = :dg"); params["dg"] = lead_dg.strip().upper()
    if policy_area:
        where.append("EXISTS (SELECT 1 FROM unnest(d.policy_areas) p WHERE p ILIKE :pa)"); params["pa"] = f"%{policy_area.strip()}%"
    if active is not None:
        where.append("d.active_case = :active"); params["active"] = active
    if with_press_release is not None:
        where.append("d.press_release_url IS NOT NULL" if with_press_release else "d.press_release_url IS NULL")
    if q:
        where.append("d.title ILIKE :q"); params["q"] = f"%{q.strip()}%"
    _range(where, params, "d.decision_date", decision_from, decision_to)
    sql_window(where, params, validate_window(created_from, created_to, updated_from, updated_to),
               "d.creation_date", "d.content_updated_at")
    clause = ("WHERE " + " AND ".join(where)) if where else ""
    direction = "DESC" if order == "recent" else "ASC"
    total = int(db.execute(text(f"SELECT count(*) FROM infringement_decisions d {clause}"), params).scalar() or 0)
    rows = db.execute(text(
        f"SELECT {_DECISION_COLS} FROM infringement_decisions d "
        f"LEFT JOIN infringement_cases c ON c.infringement_number = d.infringement_number {clause} "
        f"ORDER BY {sql_order(order, 'd.creation_date', 'd.content_updated_at', 'd.id') or f'd.decision_date {direction}, d.id {direction}'} "
        f"LIMIT :limit OFFSET :offset"),
        {**params, "limit": limit, "offset": (page - 1) * limit}).mappings().all()
    return build_envelope([_decision_from_row(r) for r in rows], total=total, page=page, limit=limit,
                          published_from=decision_from, published_to=decision_to,
                          op_core_title="Infringement decisions", op_core_type="Infringement decision",
                          op_core_identifier=str(request.url))


@router.get(
    "/decisions/{decision_id}",
    response_model=InfringementDecisionDetail,
    summary="Look up one infringement decision",
    description=f"""**What it does**
Returns one infringement decision with its full composed body: the decision, its date, the case and Member State, the subject, the department in charge, and links to the press release, memo or Court of Justice case.

**When to use it**
After finding a decision in the decisions list, to read or quote it in full.

**Input**
- `decision_id` (path): the `id` of a decision from the decisions list.
- `body_threshold` (default 500): minimum body length for `has_body=true`.

**Try it**
```
GET /api/v2/commission/infringements/decisions/1
```

**You get back**
The decision's fields as in the list, plus `body_txt`, `body_html`, `body_source` and `has_body`, or 404 with `reason_code: not_found`.

**Data freshness**
{_SOURCE}""",
)
def get_decision(
    decision_id: int = Path(..., description="Brubru decision id."),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> InfringementDecisionDetail:
    r = db.execute(text(
        f"SELECT {_DECISION_COLS}, d.body_txt, d.body_html, d.body_source FROM infringement_decisions d "
        "LEFT JOIN infringement_cases c ON c.infringement_number = d.infringement_number WHERE d.id = :id"),
        {"id": decision_id}).mappings().first()
    if not r:
        raise _not_found("infringement_decision", str(decision_id))
    r = dict(r)
    r["policy_areas"] = list(r.get("policy_areas") or [])
    r["document_date"] = r["decision_date"]
    r["has_body"] = len(r.get("body_txt") or "") >= body_threshold
    return InfringementDecisionDetail(**r)


# --------------------------------------------------------------------------- statistics
@router.get(
    "/statistics",
    response_model=PaginatedResponse[StatisticsDatasetItem],
    summary="Statistics on infringements, transposition of directives and pre-infringement dialogues",
    description="""**What it does**
Lists the statistics datasets published on the Commission's 'Implementing EU law' dashboards, in three sections: infringement cases (active cases per Member State, by type and policy area, decisions per year, trends, durations, time to comply with Court rulings), transposition of directives (transposition and conformity deficits per Member State and over time, directives to transpose), and pre-infringement dialogues (per Member State, by policy area, trends, duration, resolution rate).

**When to use it**
To find which dataset answers a question, and which parameters it takes, before calling `/statistics/{dataset}`.

**Input**
- `section`: `infringements`, `transposition` or `pre_infringement_dialogues` (optional).

**Try it**
```
GET /api/v2/commission/infringements/statistics
GET /api/v2/commission/infringements/statistics?section=transposition
```

**You get back**
One item per dataset: `dataset` (the key for `/statistics/{dataset}`), `section`, `title`, `description`, `unit`, `parameters` (the query parameters it accepts), and the five datapoints (`public_url` is the dashboard page).

**Data freshness**
The catalogue is fixed; each dataset's figures are read from the Commission's dashboards when requested and cached for six hours.""",
)
def list_statistics(
    request: Request,
    section: Optional[str] = Query(None, pattern="^(infringements|transposition|pre_infringement_dialogues)$"),
    user: User = Depends(api_user_with_rate_limit),
) -> PaginatedResponse[StatisticsDatasetItem]:
    items = []
    for ds in iel.DATASETS.values():
        if section and ds.section != section:
            continue
        items.append(StatisticsDatasetItem(
            dataset=ds.key, section=ds.section, title=ds.title, description=ds.description, unit=ds.unit,
            parameters=list(ds.params), public_url=f"{iel.BASE}/{iel.SECTIONS[ds.section][0]}/en",
        ))
    return build_envelope(items, total=len(items), page=1, limit=max(len(items), 1),
                          op_core_title="Implementing EU law statistics", op_core_type="Statistics dataset",
                          op_core_identifier=str(request.url))


@router.get(
    "/statistics/{dataset}",
    response_model=InfringementStatistics,
    summary="One statistics dataset on infringements, transposition or pre-infringement dialogues",
    description="""**What it does**
Returns the figures of one dataset from the Commission's 'Implementing EU law' dashboards, for the parameters you choose: for example the number of open infringement cases per Member State today, the transposition deficit of each Member State in a given month, or pre-infringement dialogues opened and closed per year.

**When to use it**
For comparisons across Member States and trends over time, where the case and decision lists would need counting. List the datasets first with `/statistics`.

**Input**
- `dataset` (path): a key from `/statistics`, e.g. `active-cases-by-member-state`, `transposition-deficit-by-member-state`, `dialogues-opened-closed-active`.
- Only the parameters the dataset accepts (see `/statistics`); any other returns 422:
  - `date` (YYYY-MM-DD, default today), `year`, `month` (1-12), `end_year` (default last year), `year_range` (1-25, default 5);
  - `member_state` (e.g. `PL`, `EL`), `case_type` (`NCM`, `NCF`, `BAD`, `REG`; repeatable), `policy_area` (a department code such as `ENV`, or its numeric id; repeatable).

**Try it**
```
GET /api/v2/commission/infringements/statistics/active-cases-by-member-state
GET /api/v2/commission/infringements/statistics/transposition-deficit-by-member-state?year=2026&month=9
GET /api/v2/commission/infringements/statistics/cases-opened-closed-active?member_state=IT&end_year=2025&year_range=10
```

**You get back**
`dataset`, `title`, `unit`, `parameters` (as applied, defaults included), `series` (named series of labelled values), `rows` (the same as flat rows), `source_url`, and the five datapoints: `public_url` (the dashboard page), `body_txt`/`body_html` (the figures as a readable table), `document_date` (the dashboard's own last update), `creation_date` (when Brubru read the figures).

**Data freshness**
Read from ec.europa.eu/implementing-eu-law when requested and cached for six hours; the Commission updates the dashboards daily.""",
)
def get_statistics(
    dataset: str = Path(..., description="Dataset key from /statistics."),
    date_: Optional[date] = Query(None, alias="date", description="As of this day (YYYY-MM-DD)."),
    year: Optional[int] = Query(None),
    month: Optional[int] = Query(None),
    end_year: Optional[int] = Query(None),
    year_range: Optional[int] = Query(None),
    member_state: Optional[str] = Query(None),
    case_type: Optional[List[str]] = Query(None),
    policy_area: Optional[List[str]] = Query(None),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
) -> InfringementStatistics:
    if dataset not in iel.DATASETS:
        raise _not_found("statistics_dataset", dataset)
    try:
        r = iel.fetch_dataset(dataset, day=date_, year=year, month=month, end_year=end_year, year_range=year_range,
                              member_state=member_state, case_type=case_type, policy_area=policy_area)
    except ValueError as e:
        raise _bad_request(str(e))
    except (ConnectionError, OSError) as e:
        raise HTTPException(status_code=502, detail={"error": f"The Commission's dashboard did not answer: {e}",
                                                     "reason_code": "upstream_unavailable"})
    except Exception as e:  # httpx errors and malformed JSON
        raise HTTPException(status_code=502, detail={"error": f"The Commission's dashboard could not be read ({type(e).__name__})",
                                                     "reason_code": "upstream_unavailable"})
    import html as _html
    params_txt = ", ".join(f"{k}: {v}" for k, v in r["parameters"].items())
    lines = [f"{r['title']} ({params_txt})." if params_txt else f"{r['title']}.", r["description"],
             f"Unit: {r['unit']}."]
    for s in r["series"]:
        lines.append(f"{s['name']}: " + "; ".join(f"{p['label']} {p['value']}" for p in s["points"]))
    lines.append("Source: European Commission, Implementing EU law dashboards.")
    body_txt = "\n\n".join(lines)
    table_rows = "".join(f"<tr><td>{_html.escape(str(x['series']))}</td><td>{_html.escape(x['label'])}</td>"
                         f"<td>{_html.escape(str(x['value']))}</td></tr>" for x in r["rows"])
    body_html = (f"<article><h1>{_html.escape(r['title'])}</h1><p>{_html.escape(r['description'])}</p>"
                 f"<p>{_html.escape(params_txt)}</p><table><thead><tr><th>Series</th><th>Label</th><th>Value</th></tr>"
                 f"</thead><tbody>{table_rows}</tbody></table></article>")
    return InfringementStatistics(
        dataset=r["dataset"], section=r["section"], title=r["title"], description=r["description"], unit=r["unit"],
        parameters=r["parameters"], series=r["series"], rows=r["rows"], source_url=r["source_url"],
        public_url=r["public_url"], body_txt=body_txt, body_html=body_html,
        document_date=r["last_update"], creation_date=r["fetched_at"],
        has_body=len(body_txt) >= body_threshold,
    )


# --------------------------------------------------------------------------- press releases (legacy collection)
@router.get(
    "/press-releases",
    response_model=PaginatedResponse[InfringementItem],
    summary="Commission press releases about infringement decisions",
    description="""**What it does**
Lists the Commission press releases about infringement decisions (monthly infringement packages and individual referrals to the Court). This is the collection `/api/v2/commission/infringements` served before 16 September 2026; the register of cases and decisions now lives at `/api/v2/commission/infringements` and `/decisions`.

**When to use it**
When you want the Commission's press communication about infringements rather than the register itself. Most register decisions that had a press release also carry its link in `press_release_url`.

**Input**
- `member_state` (ISO-2), `procedure_stage` (e.g. `formal notice`), `sector`, `q`, `decision_from`, `decision_to`, `limit` (max 100), `page`.

**Try it**
```
GET /api/v2/commission/infringements/press-releases?member_state=ES
```

**You get back**
A paginated list of press-release items: `inf_reference`, `title`, `summary`, `member_state`, `procedure_stage`, `decision_date`, `source_url`, and the five datapoints.

**Data freshness**
Ingested from the Commission's press corner; not updated since 7 May 2026. For current decisions use `/decisions?with_press_release=true`.""",
)
async def list_press_releases(
    request: Request,
    member_state: Optional[str] = Query(None, min_length=2, max_length=2),
    procedure_stage: Optional[str] = Query(None),
    sector: Optional[str] = Query(None),
    q: Optional[str] = Query(None),
    decision_from: Optional[date] = Query(None),
    decision_to: Optional[date] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[InfringementItem]:
    return await _v1_infringements_funding.list_infringements(
        request=request, member_state=member_state, procedure_stage=procedure_stage, sector=sector, q=q,
        decision_from=decision_from, decision_to=decision_to, limit=limit, page=page, user=user, db=db)


@router.get(
    "/press-releases/{inf_reference:path}",
    response_model=InfringementItem,
    summary="Look up one Commission press release about infringements",
    description="""**What it does**
Returns one press release from `/press-releases` by its reference.

**When to use it**
After finding a press release in `/press-releases`.

**Input**
- `inf_reference` (path): the press release reference, e.g. `IP_26_838`.

**Try it**
```
GET /api/v2/commission/infringements/press-releases/IP_26_838
```

**You get back**
One press-release item, or 404 with `reason_code: not_found`.

**Data freshness**
As `/press-releases`: not updated since 7 May 2026.""",
)
async def get_press_release(
    inf_reference: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> InfringementItem:
    return await _v1_infringements_funding.get_infringement(inf_reference=inf_reference, user=user, db=db)


# --------------------------------------------------------------------------- one case (registered LAST: `{case_id}` would otherwise capture /decisions, /statistics, /press-releases)
def _load_case(db: Session, case_id: str):
    value = case_id.strip()
    if value.isdigit():
        row = db.execute(text(f"SELECT {_CASE_COLS}, body_txt, body_html, body_source FROM infringement_cases WHERE id = :id"),
                         {"id": int(value)}).mappings().first()
        if row:
            return row
    return db.execute(text(f"SELECT {_CASE_COLS}, body_txt, body_html, body_source FROM infringement_cases "
                           "WHERE infringement_number = :n"), {"n": _normalise_number(value)}).mappings().first()


@router.get(
    "/{case_id}",
    response_model=InfringementCaseDetail,
    summary="Look up one infringement case with all its decisions",
    description=f"""**What it does**
Returns one infringement case with its full composed body and every decision the Commission adopted in it, oldest first: from the letter of formal notice to the reasoned opinion, the referral to the Court of Justice and the closure.

**When to use it**
To follow one case from start to finish, or to quote its current state.

**Input**
- `case_id` (path): the case `id` from the list, or its infringement number, e.g. `INFR(2026)0352`.
- `body_threshold` (default 500): minimum body length for `has_body=true`.

**Try it**
```
GET /api/v2/commission/infringements/INFR(2026)0352
```

**You get back**
The case's fields as in the list, plus `body_txt`, `body_html`, `body_source`, `has_body` and `decisions` (each decision with its own datapoints), or 404 with `reason_code: not_found`.

**Data freshness**
{_SOURCE}""",
)
def get_case(
    case_id: str = Path(..., description="Case id, or the infringement number, e.g. INFR(2026)0352."),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> InfringementCaseDetail:
    r = _load_case(db, case_id)
    if not r:
        # Until 16 Sep 2026 this path served press releases, keyed by their reference
        # (IP_26_838) or UUID. Those URLs keep working: they now redirect to /press-releases.
        legacy = db.execute(text("SELECT inf_reference FROM infringement_procedures WHERE NOT is_test "
                                 "AND (inf_reference = :v OR id::text = :v) LIMIT 1"), {"v": case_id.strip()}).scalar()
        if legacy:
            from urllib.parse import quote
            return RedirectResponse(f"/api/v2/commission/infringements/press-releases/{quote(legacy, safe='')}",
                                    status_code=308)
        raise _not_found("infringement_case", case_id)
    r = dict(r)
    for k in ("policy_areas", "court_cases", "press_release_urls"):
        r[k] = list(r.get(k) or [])
    r["document_date"] = r["latest_decision_date"]
    r["has_body"] = len(r.get("body_txt") or "") >= body_threshold
    decisions = db.execute(text(
        f"SELECT {_DECISION_COLS} FROM infringement_decisions d "
        "LEFT JOIN infringement_cases c ON c.infringement_number = d.infringement_number "
        "WHERE d.infringement_number = :n ORDER BY d.decision_date, d.id"), {"n": r["infringement_number"]}).mappings().all()
    r["decisions"] = [_decision_from_row(d) for d in decisions]
    return InfringementCaseDetail(**r)


@router.get(
    "/{case_id}/decisions",
    response_model=PaginatedResponse[InfringementDecision],
    summary="The decisions adopted in one infringement case",
    description=f"""**What it does**
Lists the decisions adopted in one infringement case, oldest first.

**When to use it**
When you only need a case's procedural steps, paginated.

**Input**
- `case_id` (path): the case `id`, or its infringement number, e.g. `INFR(2026)0352`.
- `limit` (max 100), `page`.

**Try it**
```
GET /api/v2/commission/infringements/INFR(2026)0352/decisions
```

**You get back**
A paginated list of decisions, as in `/decisions`, or 404 when the case does not exist.

**Data freshness**
{_SOURCE}""",
)
def list_case_decisions(
    request: Request,
    case_id: str = Path(..., description="Case id, or the infringement number."),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[InfringementDecision]:
    r = _load_case(db, case_id)
    if not r:
        raise _not_found("infringement_case", case_id)
    n = r["infringement_number"]
    total = int(db.execute(text("SELECT count(*) FROM infringement_decisions WHERE infringement_number = :n"), {"n": n}).scalar() or 0)
    rows = db.execute(text(
        f"SELECT {_DECISION_COLS} FROM infringement_decisions d "
        "LEFT JOIN infringement_cases c ON c.infringement_number = d.infringement_number "
        "WHERE d.infringement_number = :n ORDER BY d.decision_date, d.id LIMIT :limit OFFSET :offset"),
        {"n": n, "limit": limit, "offset": (page - 1) * limit}).mappings().all()
    return build_envelope([_decision_from_row(x) for x in rows], total=total, page=page, limit=limit,
                          op_core_title=f"Decisions in infringement case {n}", op_core_type="Infringement decision",
                          op_core_identifier=str(request.url))
