"""European Parliament-style copy of the v1 European Commission surface — /api/v2/commission/infringements/*.

LIVE — copy-pasted verbatim from the v1 Commission surface; the body delegates
to the v1 handler so there is exactly one implementation during the v1+v2
coexistence period. Summaries, descriptions and signatures are identical to v1;
only the in-description example URLs are rehomed to /api/v2/commission/*.

Generated by scripts/_gen_v2_commission.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401

from api.v1 import infringements_funding as _v1_infringements_funding
from api.v1.infringements_funding import *  # noqa: F401,F403 - reproduce v1 namespace for get_type_hints

router = APIRouter(prefix="/infringements", tags=["v2-commission-infringements"])


@router.get(
    "",
    response_model=PaginatedResponse[InfringementItem],
    summary="Commission infringement decisions — Member State legal proceedings (LFN, reasoned opinion, CJEU referral, closure)",
    description="""**What it does**
Returns the infringement decisions adopted by the College of Commissioners in the monthly infringement packages — letters of formal notice (LFN, the first warning), reasoned opinions (the second warning), referrals to the Court of Justice (CJEU litigation), and closures (Member State complied). Each row carries the INF reference, the Member State, the procedure stage, the sector, dates, and the decision summary.

**When to use it**
For compliance + risk-monitoring work: which Member States have open infringements on a topic, what stages of proceedings the Commission has reached, and what risks of CJEU litigation exist. Filter by `member_state` for one country, by `sector` for a topic.

**Input**
- `member_state` — ISO-2 (exact 2 chars).
- `procedure_stage` — substring on stage name (e.g. `formal notice`, `reasoned opinion`).
- `sector` — substring on sector.
- `q` — substring on title + summary.
- `decision_from`, `decision_to` — decision_date filter.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/commission/infringements?member_state=PL&procedure_stage=reasoned%20opinion
GET /api/v2/commission/infringements?sector=environment&decision_from=2026-01-01
```

**You get back**
A `PaginatedResponse[InfringementItem]` envelope. Each item carries `inf_reference`, `title`, `summary`, `member_state`, `procedure_stage`, `sector`, `decision_date`, `source_url`, plus the 5 envelope-level datapoints.

**Data freshness**
Synced once per day at 04:00 UTC (daily tier) from ec.europa.eu/commission/presscorner. The Commission adopts infringement packages monthly + ad-hoc; daily sync catches them within 24h of adoption. is_test=True fixture rows are filtered out at query time.""",
)
async def list_infringements(
    request: Request,
    member_state: Optional[str] = Query(None, min_length=2, max_length=2),
    procedure_stage: Optional[str] = Query(None),
    sector: Optional[str] = Query(None),
    q: Optional[str] = Query(None, description="Substring match on title/summary"),
    decision_from: Optional[date] = Query(None),
    decision_to: Optional[date] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[InfringementItem]:
    return await _v1_infringements_funding.list_infringements(request=request, member_state=member_state, procedure_stage=procedure_stage, sector=sector, q=q, decision_from=decision_from, decision_to=decision_to, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{inf_reference:path}",
    response_model=InfringementItem,
    summary="Look up one infringement decision by its INF reference",
    description="""**What it does**
Fetches a single infringement decision by its INF reference. Returns the same shape as the list endpoint.

**When to use it**
After locating an infringement via the list endpoint, use this for the full record + body composition.

**Input**
- `inf_reference` (path) — INF reference (e.g. `INF(2026)123`). The `:path` matcher accepts parentheses verbatim.

**Try it**
```
GET /api/v2/commission/infringements/INF(2026)123
```

**You get back**
A single `InfringementItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — daily 04:00 UTC sync from ec.europa.eu/commission/presscorner.""",
)
async def get_infringement(
    inf_reference: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> InfringementItem:
    return await _v1_infringements_funding.get_infringement(inf_reference=inf_reference, user=user, db=db)
