"""European Parliament-style copy of the v1 European Commission surface — /api/v2/commission/meetings/*.

LIVE — copy-pasted verbatim from the v1 Commission surface; the body delegates
to the v1 handler so there is exactly one implementation during the v1+v2
coexistence period. Summaries, descriptions and signatures are identical to v1;
only the in-description example URLs are rehomed to /api/v2/commission/*.

Generated by scripts/_gen_v2_commission.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401

from api.v1 import w4_endpoints as _v1_w4_endpoints
from api.v1.w4_endpoints import *  # noqa: F401,F403 - reproduce v1 namespace for get_type_hints

router = APIRouter(prefix="/meetings", tags=["v2-commission-meetings"])


@router.get(
    "",
    response_model=PaginatedResponse[TransparencyMeetingItem],
    summary="Commission officials' meetings with interest representatives (Transparency Initiative)",
    description="""**What it does**
Returns the meetings between Commission officials (Commissioners, Heads of Cabinet, Directors-General) and external interest representatives — lobbyists, NGOs, trade bodies, member-state representatives — as published under the Transparency Initiative. Each row carries the host (UUID + name + role + DG/cabinet), the meeting date + location + subject, the organisation met, its Transparency Register ID, the participating representatives, and policy-area + related-CELEX tags.

**When to use it**
To audit who lobbied which Commissioner on a given topic, build a "meetings on Topic X" view for an advocacy campaign, or cross-reference a known lobbyist against the meetings register. Combined with `/api/v1/specialised/transparency-register`, it lets you trace lobbying activity end-to-end (who is registered → who they met → what was discussed).

**Input**
- `host_uuid` — filter to a specific Commissioner/Cabinet host (UUID from commission.europa.eu).
- `host_dg` — filter to a specific DG (e.g. `COMP`, `CLIMA`).
- `organisation_met` — substring match on the organisation name (e.g. `Microsoft`).
- `transparency_register_id` — filter to a specific registered entity.
- `q` — substring search on the meeting subject.
- `published_from`, `published_to` — date filter on `meeting_date`.
- `updated_from` — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/commission/meetings?host_dg=COMP&q=AI
GET /api/v2/commission/meetings?organisation_met=BusinessEurope&limit=20
```

**You get back**
A `PaginatedResponse[TransparencyMeetingItem]` envelope. Each item carries `host_uuid`, `host_name`, `host_role`, `host_dg`, `host_cabinet`, `meeting_date`, `location`, `subject`, `organisation_met`, `transparency_register_id`, `organisation_type`, `representatives` (array of names), `source_url`, `policy_areas`, `related_celex`, plus a composed `body_txt`/`body_html` (subject + participants + organisation) and the 5 envelope-level datapoints.

**Data freshness**
Synced once per day at 04:00 UTC (daily tier) from ec.europa.eu/transparencyinitiative/meetings/. Cabinet officials are required to publish meetings within ~2 weeks; daily sync catches them inside that window. Seed host UUIDs: ca175ad3... (President), a2c7c963... (Ribera), 9fd4662a... (Hoekstra).""",
)
async def list_meetings(
    request: Request,
    host_uuid: Optional[str] = Query(None),
    host_dg: Optional[str] = Query(None),
    organisation_met: Optional[str] = Query(None, description="Substring match"),
    transparency_register_id: Optional[str] = Query(None),
    q: Optional[str] = Query(None, description="Substring on subject"),
    published_from: Optional[date] = Query(None, description="meeting_date >= value"),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[TransparencyMeetingItem]:
    return await _v1_w4_endpoints.list_meetings(request=request, host_uuid=host_uuid, host_dg=host_dg, organisation_met=organisation_met, transparency_register_id=transparency_register_id, q=q, published_from=published_from, published_to=published_to, updated_from=updated_from, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{meeting_id}",
    response_model=TransparencyMeetingItem,
    summary="Look up one Transparency Initiative meeting by its internal UUID",
    description="""**What it does**
Fetches a single Transparency Initiative meeting record by its Brubru-internal UUID. Returns the same shape as the list endpoint.

**When to use it**
After locating a meeting via the list endpoint, use this to deep-link into a specific record (e.g. embedded in an advocacy report or a chat answer).

**Input**
- `meeting_id` (path) — Brubru UUID of the meeting (returned in `id` from the list endpoint).

**Try it**
```
GET /api/v2/commission/meetings/<uuid>
```

**You get back**
A single `TransparencyMeetingItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found` if no meeting with that UUID exists.

**Data freshness**
Same as the list endpoint — daily 04:00 UTC sync from ec.europa.eu/transparencyinitiative/meetings/.""",
)
async def get_meeting_detail(
    meeting_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> TransparencyMeetingItem:
    return await _v1_w4_endpoints.get_meeting_detail(meeting_id=meeting_id, user=user, db=db)
