"""European Parliament-style copy of the v1 European Commission surface — /api/v2/commission/rsb-opinions/*.

LIVE — copy-pasted verbatim from the v1 Commission surface; the body delegates
to the v1 handler so there is exactly one implementation during the v1+v2
coexistence period. Summaries, descriptions and signatures are identical to v1;
only the in-description example URLs are rehomed to /api/v2/commission/*.

Generated by scripts/_gen_v2_commission.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401

from api.v1 import w4_endpoints as _v1_w4_endpoints
from api.v1.w4_endpoints import *  # noqa: F401,F403 - reproduce v1 namespace for get_type_hints

router = APIRouter(prefix="/rsb-opinions", tags=["v2-commission-rsb-opinions"])


@router.get(
    "",
    response_model=PaginatedResponse[RSBOpinionItem],
    summary="Regulatory Scrutiny Board opinions on Commission impact assessments + evaluations",
    description="""**What it does**
Returns opinions of the Regulatory Scrutiny Board — the independent body within the Commission that scrutinises impact assessments, evaluations, and fitness checks before they're submitted to the College. Each opinion carries the target initiative (the proposed regulation being assessed), the target DG, the procedure reference, the opinion type (`impact_assessment` / `evaluation` / `fitness_check`), and the verdict (`positive` / `positive_with_reservations` / `negative`).

**When to use it**
A negative RSB opinion is a red flag that a forthcoming proposal has methodological gaps — often a leading indicator that the College will delay adoption, send the file back for re-work, or amend the impact assessment. Use this endpoint to monitor RSB output on the policy files you care about, or to filter for "all negative opinions on environment files in 2026" as a quality signal.

**Input**
- `target_dg` — DG code (e.g. `CLIMA`, `ENVI`).
- `procedure_ref` — OEIL reference.
- `verdict` — `positive` / `positive_with_reservations` / `negative` / `unknown`.
- `opinion_type` — `impact_assessment` / `evaluation` / `fitness_check`.
- `q` — substring search on title + summary.
- `published_from`, `published_to` — date filter on `opinion_date`.
- `updated_from` — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/commission/rsb-opinions?verdict=negative&target_dg=CLIMA
GET /api/v2/commission/rsb-opinions?q=AI%20Act
```

**You get back**
A `PaginatedResponse[RSBOpinionItem]` envelope. Each item carries `opinion_reference`, `title`, `target_initiative`, `target_dg`, `procedure_ref`, `opinion_type`, `verdict`, `opinion_date`, `summary`, `pdf_url`, `source_url`, `policy_areas`, `last_updated`.

**Data freshness**
Synced once per week (Sunday 05:00 UTC, weekly tier) from commission.europa.eu/law/law-making-process/regulatory-scrutiny-board/. RSB publishes a handful of opinions per month; weekly sync is appropriate. Scraper queued; endpoint returns empty until ingestion completes.""",
)
async def list_rsb_opinions(
    request: Request,
    target_dg: Optional[str] = Query(None),
    procedure_ref: Optional[str] = Query(None),
    verdict: Optional[str] = Query(None, description="positive | positive_with_reservations | negative | unknown"),
    opinion_type: Optional[str] = Query(None, description="impact_assessment | evaluation | fitness_check"),
    q: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[RSBOpinionItem]:
    return await _v1_w4_endpoints.list_rsb_opinions(request=request, target_dg=target_dg, procedure_ref=procedure_ref, verdict=verdict, opinion_type=opinion_type, q=q, published_from=published_from, published_to=published_to, updated_from=updated_from, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{opinion_reference}",
    response_model=RSBOpinionItem,
    summary="Look up one Regulatory Scrutiny Board opinion by its reference",
    description="""**What it does**
Fetches a single RSB opinion by its reference. Returns the same shape as the list endpoint.

**When to use it**
After locating an RSB opinion via the list endpoint, use this to deep-link into a specific record. Common pattern: list with `verdict=negative` to surface red-flag opinions, then drill into each one.

**Input**
- `opinion_reference` (path) — the RSB opinion reference (format varies; check the list endpoint for examples in the current data).

**Try it**
```
GET /api/v2/commission/rsb-opinions/<reference>
```

**You get back**
A single `RSBOpinionItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — weekly Sunday 05:00 UTC sync from commission.europa.eu/law/law-making-process/regulatory-scrutiny-board/.""",
)
async def get_rsb_detail(
    opinion_reference: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> RSBOpinionItem:
    return await _v1_w4_endpoints.get_rsb_detail(opinion_reference=opinion_reference, user=user, db=db)
