"""European Parliament-style copy of the v1 European Commission surface — /api/v2/commission/tris-notifications/*.

LIVE — copy-pasted verbatim from the v1 Commission surface; the body delegates
to the v1 handler so there is exactly one implementation during the v1+v2
coexistence period. Summaries, descriptions and signatures are identical to v1;
only the in-description example URLs are rehomed to /api/v2/commission/*.

Generated by scripts/_gen_v2_commission.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401

from api.v1 import w4_endpoints as _v1_w4_endpoints
from api.v1.w4_endpoints import *  # noqa: F401,F403 - reproduce v1 namespace for get_type_hints

router = APIRouter(prefix="/tris-notifications", tags=["v2-commission-tris-notifications"])


@router.get(
    "",
    response_model=PaginatedResponse[TRISNotificationItem],
    summary="Member State notifications of national technical regulations (TRIS, Directive 2015/1535)",
    description="""**What it does**
Returns notifications submitted by EU Member States under Directive 2015/1535 — the obligation to notify the Commission of draft national technical regulations that could create barriers to the Single Market (in goods and information-society services). Each row carries the notification reference (e.g. `2026/0123/FR`), the notifying country, the sector, the title + short summary + main content, the standstill period, and the Commission's reaction (detailed opinion / comment / no-reaction).

**When to use it**
Critical for anyone tracking single-market barriers — a French draft law on packaging waste, a German tax on plastic bags, a Polish ban on a specific chemical — all surface here BEFORE they become national law. The 3-month standstill window gives industry and other Member States time to flag incompatibilities. Trade associations, single-market advocates, and product-compliance teams should monitor this continuously.

**Input**
- `notifying_country` — ISO-3166-1 alpha-2 (e.g. `FR`, `DE`).
- `sector` — TRIS sector code (substring).
- `q` — substring search on title + short summary + main content.
- `published_from`, `published_to` — date filter on `notification_date`.
- `updated_from` — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/commission/tris-notifications?notifying_country=FR&q=packaging
GET /api/v2/commission/tris-notifications?sector=N40&published_from=2026-01-01
```

**You get back**
A `PaginatedResponse[TRISNotificationItem]` envelope. Each item carries `notification_number`, `notifying_country`, `sector`, `title`, `short_summary`, `main_content`, `notification_date`, `standstill_period`, `commission_reaction`, `source_url`, `pdf_url`, `policy_areas`, `related_celex`, body fields, and the 5 envelope-level datapoints.

**Data freshness**
Synced once per day at 04:00 UTC (daily tier) from technical-regulation-information-system.ec.europa.eu/. Member States submit notifications throughout the day; daily sync catches them. Backed by `services/scrapers/dg_grow/dg_grow_sync_service.py::sync_tris()`.""",
)
async def list_tris_notifications(
    request: Request,
    notifying_country: Optional[str] = Query(None, description="ISO-3166-1 alpha-2, e.g. FR"),
    sector: Optional[str] = Query(None),
    q: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[TRISNotificationItem]:
    return await _v1_w4_endpoints.list_tris_notifications(request=request, notifying_country=notifying_country, sector=sector, q=q, published_from=published_from, published_to=published_to, updated_from=updated_from, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)


@router.get(
    "/{notification_number:path}",
    response_model=TRISNotificationItem,
    summary="Look up one TRIS notification by its number (e.g. 2026/0123/FR)",
    description="""**What it does**
Fetches a single TRIS notification by its reference. Returns the same shape as the list endpoint.

**When to use it**
After locating a TRIS notification via the list endpoint, use this to fetch the full record (including the main content of the draft national regulation) in a deeper-link context — useful for compliance teams analysing whether a specific national draft impacts their product.

**Input**
- `notification_number` (path) — the TRIS reference, format `YYYY/NNNN/CC` where CC is the ISO country code (e.g. `2026/0123/FR`).

**Try it**
```
GET /api/v2/commission/tris-notifications/2026/0123/FR
```

**You get back**
A single `TRISNotificationItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — daily 04:00 UTC sync from TRIS.""",
)
async def get_tris_detail(
    notification_number: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> TRISNotificationItem:
    return await _v1_w4_endpoints.get_tris_detail(notification_number=notification_number, body_threshold=body_threshold, user=user, db=db)
