"""General Publications domain — /api/v2/general-publications/*.

LIVE — copy-pasted from api.v1.general_publications; body delegates to the v1
handlers. Generated by scripts/_gen_v2_general_publications.py — do not hand-edit.
"""
from __future__ import annotations
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401
from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401
from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import general_publications as _v1
from api.v1.general_publications import *  # noqa: F401,F403


router = APIRouter(prefix="/general-publications")


@router.get(
    "",
    response_model=PaginatedResponse[GeneralPublicationItem],
    summary="EU general publications — brochures, reports and studies",
    description="""**What it does**
Returns the EU Publications Office's general publications (brochures, reports, studies) — Cellar works of resource-type PUB_GEN — each with its title, publication date, and the read/download page.

**When to use it**
To search the EU's catalogue of general (non-legal) publications across all policy areas.

**Input**
- `q` — substring search over the title.
- `published_from`, `published_to` — bound on the publication date.
- `limit` (default 25, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/general-publications?q=artificial+intelligence
```

**You get back**
A `PaginatedResponse[GeneralPublicationItem]` with the five envelope datapoints filled (`public_url` = the publication page, `body_txt`/`body_html` composed, `document_date` = publication date, `creation_date`).

**Data freshness**
Synced from the EU SPARQL endpoint (Cellar). Bodies composed at ingest."""
)
async def list_general_publications(
    request: Request,
    q: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[GeneralPublicationItem]:
    return await _v1.list_general_publications(request=request, q=q, published_from=published_from, published_to=published_to, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{item_id}",
    response_model=GeneralPublicationItem,
    summary="One EU general publication by id",
    description="Fetch a single EU general publication by its Brubru UUID. 404 with `reason_code: not_found` if absent.",
)
async def get_general_publication(item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db)) -> GeneralPublicationItem:
    return await _v1.get_general_publication(item_id=item_id, user=user, db=db)
