"""European Parliament domain — /api/v2/parliament/committee-agendas/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.committee_agendas); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import committee_agendas as _v1
from api.v1.committee_agendas import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/committee-agendas", tags=["v2-parliament-committee-agendas"])


@router.get(
    "",
    response_model=PaginatedResponse[CommitteeAgendaOut],
    summary="EP committee draft agendas — the order of the day for committee meetings, with full text",
    description="""**What it does**
Returns EP committee draft agendas (the official "order of the day" for each committee meeting): the committee, the meeting date, the link to the doceo agenda document, the procedure references scheduled for discussion, and the full agenda text (`body_txt` + `body_html`). It tells you what a committee plans to take up before the meeting happens.

**When to use it**
To see what is coming up in a committee — which files are tabled for discussion or vote at the next meeting, and the full running order. Pair with `/api/v2/parliament/committees/{code}/minutes` (what happened) and `/api/v2/parliament/committee-transcripts` (what was said).

**Input**
- `committee` — EP committee/subcommittee code (e.g. `LIBE`, `ENVI`).
- `procedure_reference` — only agendas that scheduled this procedure (e.g. `2024/0079(COD)`).
- `q` — substring search on the agenda title.
- `upcoming` — `true` returns only agendas dated today or later (the planning view); default `false` returns all.
- `published_from` / `published_to` (aliased `date_from` / `date_to`) — meeting-date range.
- `updated_from` — rows updated at/after this timestamp (incremental sync).
- `body_threshold` — minimum agenda-text length (chars) for `has_body=true`. Default 500.
- `limit` (default 10, max 25 — the agenda document is fetched + cached on first access), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/committee-agendas?committee=LIBE&upcoming=true
GET /api/v2/parliament/committee-agendas?procedure_reference=2024/0079(COD)
```

**You get back**
A `PaginatedResponse[CommitteeAgendaOut]`. Each row carries `committee_code`, `title`, `meeting_date`, `procedure_refs[]`, plus the 5 envelope datapoints: `public_url` (the agenda document), `body_txt` + `body_html` (the agenda text), `document_date` (the meeting date), and `creation_date`. `has_body` is true once the agenda document has been fetched.

**Data freshness**
Agenda metadata syncs from the EP committee pages (`backend/services/scrapers/committee_agenda_sync_service.py`); draft agendas appear ~1 week before a meeting. The agenda document body is fetched from doceo on first access and cached.""",
)
async def list_committee_agendas(
    request: Request,
    committee: Optional[str] = Query(None, description="EP committee/subcommittee code (e.g. LIBE)."),
    procedure_reference: Optional[str] = Query(None, description="Only agendas that scheduled this procedure ref."),
    q: Optional[str] = Query(None, description="Substring search on the agenda title."),
    upcoming: bool = Query(False, description="True = only agendas dated today or later."),
    published_from: Optional[date] = Query(None, alias="date_from"),
    published_to: Optional[date] = Query(None, alias="date_to"),
    updated_from: Optional[datetime] = Query(None),
    body_threshold: int = Depends(body_threshold_param),
    limit: int = Query(10, ge=1, le=25, description="Items per page (default 10, max 25 — each agenda document is fetched + cached on first access)."),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CommitteeAgendaOut]:
    return await _v1.list_committee_agendas(request=request, committee=committee, procedure_reference=procedure_reference, q=q, upcoming=upcoming, published_from=published_from, published_to=published_to, updated_from=updated_from, body_threshold=body_threshold, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{event_id}",
    response_model=CommitteeAgendaOut,
    summary="One committee draft agenda by id — full agenda text + HTML",
    description="""**What it does**
Fetches a single committee draft agenda by its Brubru-internal calendar-event UUID, with the full agenda document body (`body_txt` + `body_html`).

**When to use it**
After locating an agenda via the list endpoint, use this to pull the complete order of the day.

**Input**
- `event_id` (path) — the Brubru-internal UUID from the list endpoint's `id`.

**Try it**
```
GET /api/v2/parliament/committee-agendas/{event_id}
```

**You get back**
A single `CommitteeAgendaOut` (same shape as the list endpoint's `data[i]`), with `body_txt` + `body_html` populated when the agenda document is reachable, or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Agenda body fetched from doceo on first access and cached on the event.""",
)
async def get_committee_agenda_detail(
    event_id: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CommitteeAgendaOut:
    return await _v1.get_committee_agenda_detail(event_id=event_id, body_threshold=body_threshold, user=user, db=db)
