"""European Parliament domain — /api/v2/parliament/committees/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.committees); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import committees as _v1
from api.v1.committees import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/committees", tags=["v2-parliament-committees"])


@router.get(
    "/{code}/work-items",
    response_model=CommitteeWorkEnvelope,
    summary="Legislative files an EP committee is currently working on — with stage + status",
    description="""**What it does**
Returns every legislative file an EP committee is currently working on, with the file's title, rapporteur, current stage (e.g. `awaiting_committee_vote`, `in_trilogue`), status, and any CELEX numbers cross-referenced from the underlying `legislative_carriages` table. Each row enriches the committee_work_items scrape with canonical legislation data via an outer join.

**When to use it**
The fastest way to answer "what is committee X working on?" Use to drive a committee dashboard, build a rapporteur-tracking UI, or feed a chatbot answer about a specific committee's caseload.

**Input**
- `code` (path) — EP committee 4-letter code (e.g. `LIBE`, `ENVI`).
- `q` — substring on title.
- `status` — work-item status.
- `stage` — work-item stage.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/committees/LIBE/work-items
GET /api/v2/parliament/committees/ENVI/work-items?stage=in_trilogue
```

**You get back**
A `CommitteeWorkEnvelope` with paginated work items. Each row carries the procedure ref, title (enriched), rapporteur, stage, status, dates, source URL, and the 5 envelope-level datapoints.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC, warm tier) from europarl.europa.eu/committees/<code>/work. Committee work items move on EP committee meeting cadences; 12h sync catches stage transitions.""",
)
async def list_committee_work(
    request: Request,
    code: str,
    q: Optional[str] = Query(None, description="Substring on title"),
    status: Optional[str] = Query(None),
    stage: Optional[str] = Query(None),
    limit: int = Query(50, ge=1, le=100, description="Items per page (default 50, max 100)"),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CommitteeWorkEnvelope:
    # LEFT JOIN legislative_carriages on procedure_ref so we can enrich every
    # row with the canonical title / current_status / celex_numbers when the
    # CWI scrape only captured a placeholder. Applies to all committees.
    return await _v1.list_committee_work(request=request, code=code, q=q, status=status, stage=stage, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{code}/minutes",
    response_model=CommitteeMinutesEnvelope,
    summary="EP committee meeting minutes — votes, decisions, attendance, decisions taken",
    description="""**What it does**
Returns minutes of a specific EP committee's meetings. Each row carries the meeting date, agenda items, votes (with for/against/abstention tallies), decisions taken, MEPs present, and the doceo URL for the official minutes document.

**When to use it**
To audit what actually happened at a committee meeting — particularly useful for understanding why a file's status changed (e.g. a vote was postponed, an amendment was withdrawn, a rapporteur was reappointed). The official minutes are the authoritative record.

**Input**
- `code` (path) — EP committee 4-letter code (e.g. `LIBE`, `ENVI`).
- `published_from`, `published_to` (aliased as `date_from`, `date_to`) — meeting_date filter.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/committees/LIBE/minutes?date_from=2026-01-01
GET /api/v2/parliament/committees/ENVI/minutes
```

**You get back**
A `CommitteeMinutesEnvelope` with paginated minutes rows. Each row carries the meeting date, agenda items, votes, decisions, attendance, and the doceo URL.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC, warm tier) via `backend/scripts/sync_committee_minutes.py`. Committee minutes are typically published on doceo within a few days of the meeting; 12h sync catches them as soon as they appear.""",
)
async def list_committee_minutes(
    request: Request,
    code: str,
    published_from: Optional[date] = Query(None, alias="date_from"),
    published_to: Optional[date] = Query(None, alias="date_to"),
    limit: int = Query(50, ge=1, le=100, description="Items per page (default 50, max 100)"),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CommitteeMinutesEnvelope:
    return await _v1.list_committee_minutes(request=request, code=code, published_from=published_from, published_to=published_to, limit=limit, page=page, user=user, db=db)
