"""European Parliament domain — /api/v2/parliament/emeeting/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.ep_emeeting); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import ep_emeeting as _v1
from api.v1.ep_emeeting import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/emeeting", tags=["v2-parliament-emeeting"])


@router.get(
    "",
    response_model=PaginatedResponse[EmeetingAgendaItem],
    summary="EP eMeeting — committee meeting agendas and their documents",
    description="""**What it does**
Returns European Parliament committee meeting agendas from eMeeting — one item per committee OJ (agenda). Each agenda carries its full item/document tree in `items`: every agenda item with its OEIL procedure reference, rapporteur(s), and the attached documents (draft reports, amendments, voting lists, compromise amendments) — each document with a direct multi-language PDF URL on the europarl meetdocs store.

**When to use it**
To pull the actual working documents for a committee file the moment they are tabled — the richest source of draft reports and amendments, keyed by the OEIL procedure reference so it joins straight to a tracked legislative file.

**Input**
- `committee` — committee code (AFCO, ENVI, IMCO, LIBE, ...).
- `procedure_ref` — an OEIL procedure reference (e.g. `2026/2013(INI)`); returns agendas whose items touch that file.
- `q` — substring search over title / body / OJ reference.
- `published_from`, `published_to` — bound on the meeting date.
- `updated_from`, `updated_to` — incremental sync on ingest time.
- `limit` (default 25, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/emeeting?committee=AFCO
GET /api/v2/parliament/emeeting?procedure_ref=2026/2013(INI)
```

**You get back**
A `PaginatedResponse[EmeetingAgendaItem]` envelope. Each agenda carries `procedure_refs`, `rapporteurs`, `document_count`, `agenda_pdf_url`, the full `items` tree (document PDF URLs live at `items[].document_sets[].documents[].pdf_url`), and the five envelope datapoints (`public_url`, `body_txt`, `body_html`, `document_date`, `creation_date`).

**Data freshness**
Synced from the eMeeting open JSON API (no scraping). Bodies are composed at ingest time, so the API never calls eMeeting on the request path.""",
)
async def list_emeeting_agendas(
    request: Request,
    committee: Optional[str] = Query(None, description="Committee code, e.g. AFCO."),
    procedure_ref: Optional[str] = Query(None, description="OEIL procedure ref, e.g. 2026/2013(INI)."),
    q: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[EmeetingAgendaItem]:
    return await _v1.list_emeeting_agendas(request=request, committee=committee, procedure_ref=procedure_ref, q=q, published_from=published_from, published_to=published_to, updated_from=updated_from, updated_to=updated_to, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{item_id}",
    response_model=EmeetingAgendaItem,
    summary="One EP eMeeting agenda by id — full item/document tree",
    description="""**What it does**
Fetches a single EP committee agenda by its Brubru UUID, with the complete item/document tree: every agenda item, its OEIL procedure reference and rapporteur(s), and all attached documents with their multi-language PDF URLs.

**When to use it**
After locating an agenda via the list endpoint, to pull every document URL (draft reports, amendments, voting lists, compromise amendments) for that committee meeting.

**Input**
- `item_id` (path) — the Brubru-internal UUID from the list endpoint's `id`.

**Try it**
```
GET /api/v2/parliament/emeeting/{item_id}
```

**You get back**
A single `EmeetingAgendaItem` with the five datapoints filled and the full `items` tree, or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Synced from the eMeeting open JSON API.""",
)
async def get_emeeting_agenda(
    item_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> EmeetingAgendaItem:
    return await _v1.get_emeeting_agenda(item_id=item_id, user=user, db=db)
