"""European Parliament domain — /api/v2/parliament/amendments/* and /api/v2/parliament/votes/* and /api/v2/parliament/ep-documents/* and /api/v2/parliament/reports/* and /api/v2/parliament/opinions/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.ep_entities); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import ep_entities as _v1
from api.v1.ep_entities import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


amendments_router = APIRouter(prefix="/amendments", tags=["v2-parliament-amendments"])

votes_router = APIRouter(prefix="/votes", tags=["v2-parliament-votes"])

ep_documents_router = APIRouter(prefix="/ep-documents", tags=["v2-parliament-ep-documents"])

reports_router = APIRouter(prefix="/reports", tags=["v2-parliament-reports"])

opinions_router = APIRouter(prefix="/opinions", tags=["v2-parliament-opinions"])


@amendments_router.get(
    "",
    response_model=PaginatedResponse[AmendmentItem],
    summary="EP committee amendments — what MEPs propose to change in a draft regulation",
    description="""**What it does**
Returns the individual amendments tabled by MEPs in EP committee meetings — the building blocks of co-decision negotiation. Each amendment carries the procedure reference, the committee, the document PE reference, the amendment number, the author MEPs + political group context, the element being amended (recital/article/paragraph), and crucially the side-by-side text: `original_text` (what's currently proposed) + `proposed_text` (the MEPs' alternative) + `justification`.

**When to use it**
This is the canonical surface for amendment-tracking advocacy. Common patterns: filter by `procedure_reference` to see all amendments on the AI Act, by `political_group` + `procedure_reference` to see what the Greens want to change, or by `committee` to follow ENVI's amendment activity. The `amendment_type` filter (`modification` / `suppression` / `addition`) lets you isolate where MEPs want to delete text vs add new provisions.

**Input**
- `procedure_reference` — OEIL reference (e.g. `2025/0419(COD)`).
- `committee` — 4-letter committee code (e.g. `ENVI`).
- `political_group` — code (e.g. `EPP`, `S&D`).
- `pe_reference` — EP document PE reference.
- `amendment_type` — `modification` / `suppression` / `addition`.
- `element_type` — `recital` / `article` / `paragraph` / `subparagraph`.
- `q` — substring search on element_reference + proposed_text.
- `published_from`, `published_to` — date filter on `document_date`.
- `updated_from` — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/amendments?procedure_reference=2025/0419(COD)&committee=ENVI&limit=50
GET /api/v2/parliament/amendments?political_group=S%26D&q=CBAM
```

**You get back**
A `PaginatedResponse[AmendmentItem]` envelope. Each item carries `procedure_reference`, `committee_code`, `pe_reference`, `amendment_number`, `author_names`, `political_group`, `on_behalf_of_group`, `element_type`, `element_number`, `element_reference`, `amendment_type`, `original_text`, `proposed_text`, `justification`, `source_url`, `document_date`.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC, warm tier) from EP doceo committee meeting documents. Amendments appear on doceo within hours of committee tabling deadlines; 12h sync catches them inside the half-day window.""",
)
async def list_amendments(
    request: Request,
    procedure_reference: Optional[str] = Query(None),
    committee: Optional[str] = Query(None),
    political_group: Optional[str] = Query(None),
    pe_reference: Optional[str] = Query(None),
    amendment_type: Optional[str] = Query(None, description="modification | suppression | addition"),
    element_type: Optional[str] = Query(None),
    q: Optional[str] = Query(None, description="Substring on element_reference + proposed_text"),
    published_from: Optional[date] = Query(None, description="document_date >= value"),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[AmendmentItem]:
    return await _v1.list_amendments(request=request, procedure_reference=procedure_reference, committee=committee, political_group=political_group, pe_reference=pe_reference, amendment_type=amendment_type, element_type=element_type, q=q, published_from=published_from, published_to=published_to, updated_from=updated_from, limit=limit, page=page, user=user, db=db)


@amendments_router.get(
    "/{amendment_id}",
    response_model=AmendmentItem,
    summary="Look up one EP committee amendment by its internal UUID",
    description="""**What it does**
Fetches a single EP committee amendment by its Brubru-internal UUID. Returns the original text being amended, the proposed text, the justification, the author MEPs, the political group context (or whether tabled on behalf of a group), and the doceo URL.

**When to use it**
After locating an amendment via the list endpoint, use this to fetch the full record (with original + proposed text for diff rendering) — particularly useful for embedding in a comparison view in Amendator or in an advocacy briefing.

**Input**
- `amendment_id` (path) — Brubru UUID (returned in `id` from the list endpoint).

**Try it**
```
GET /api/v2/parliament/amendments/<uuid>
```

**You get back**
A single `AmendmentItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — synced every 12 hours (02:00 / 14:00 UTC, warm tier) from EP doceo committee meeting documents.""",
)
async def get_amendment_detail(
    amendment_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> AmendmentItem:
    return await _v1.get_amendment_detail(amendment_id=amendment_id, user=user, db=db)


@votes_router.get(
    "",
    response_model=PaginatedResponse[VoteItem],
    summary="EP roll-call votes — plenary results with tallies (HowTheyVote)",
    description="""**What it does**
Roll-call vote results from European Parliament plenary sittings, sourced from HowTheyVote.eu (the open-source civic-tech mirror of the EP's official register of votes). Each row carries the vote title, procedure reference, EP committee report number, FOR/AGAINST/ABSTENTION/DID-NOT-VOTE tallies, ADOPTED/REJECTED result, and the timestamp.

Filterable by procedure, vote reference, main-vote-only, result, full-text search, and incremental sync.

**When to use it**
- Track how a specific legislative file was voted in plenary.
- Aggregate vote tallies by procedure or rapporteur.
- Build dashboards of EP plenary activity.
- Link to per-MEP voting positions via `/api/v2/parliament/votes/{vote_id}/records`.

**Input**
- `procedure_reference` — e.g. `2024/0123(COD)`.
- `reference` — e.g. `A10-0142/2026` (the EP committee report being voted on).
- `is_main` — true to exclude amendment-level votes.
- `result` — `ADOPTED | REJECTED | UNKNOWN`.
- `q` — substring on `display_title`.
- `published_from` / `published_to` — timestamp range.
- `updated_from` — incremental-sync upper-bound.
- `limit` (1–100, default 50), `page` (default 1).

**Try it**
```
GET /api/v2/parliament/votes?procedure_reference=2024%2F0106(COD)
GET /api/v2/parliament/votes?is_main=true&result=ADOPTED&limit=20
```

**You get back**
Paginated `VoteItem` envelope. `public_url` points to the specific HowTheyVote vote page (`https://howtheyvote.eu/votes/{htv_id}`). All 5 mandatory v1 datapoints present per row.

**Data freshness**
Synced every 6 hours (00:00 / 06:00 / 12:00 / 18:00 UTC) from HowTheyVote.eu (howtheyvote.eu) + EP plenary votes. HowTheyVote importer blocked on ep_political_groups.short_label collision — see CLAUDE.md.
""",
)
async def list_votes(
    request: Request,
    procedure_reference: Optional[str] = Query(None),
    reference: Optional[str] = Query(None, description="Vote reference (e.g. A10-XXXX/2026)"),
    is_main: Optional[bool] = Query(None),
    result: Optional[str] = Query(None, description="ADOPTED | REJECTED | UNKNOWN"),
    q: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None, description="timestamp >= value"),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[VoteItem]:
    return await _v1.list_votes(request=request, procedure_reference=procedure_reference, reference=reference, is_main=is_main, result=result, q=q, published_from=published_from, published_to=published_to, updated_from=updated_from, limit=limit, page=page, user=user, db=db)


@votes_router.get(
    "/{vote_id}",
    response_model=VoteItem,
    summary="Look up one EP roll-call vote by its internal ID — full tallies + HowTheyVote link",
    description="""**What it does**
Returns full metadata for one EP roll-call vote, including title, procedure, committee report, tallies, result, and the citizen-facing HowTheyVote URL.

**When to use it**
After locating a vote via the list endpoint, use this to fetch the full record (with all tallies + ADOPTED/REJECTED result) for embedding in an analysis or a chat answer. To get the per-MEP breakdown of the same vote, follow up with `/api/v2/parliament/votes/{vote_id}/records`.

**Input**
- `vote_id` (path) — `ep_votes.id` (UUID).

**Try it**
```
GET /api/v2/parliament/votes/{vote_id}
```

**You get back**
A `VoteItem` with all 5 mandatory v1 datapoints. `public_url` resolves to `https://howtheyvote.eu/votes/{htv_id}` — the public vote page with per-MEP breakdown, country chart, and group cohesion.

**Data freshness**
Synced every 6 hours (00:00 / 06:00 / 12:00 / 18:00 UTC) from HowTheyVote.eu (howtheyvote.eu) + EP plenary votes. HowTheyVote importer blocked on ep_political_groups.short_label collision — see CLAUDE.md.
""",
)
async def get_vote_detail(
    vote_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> VoteItem:
    return await _v1.get_vote_detail(vote_id=vote_id, user=user, db=db)


@votes_router.get(
    "/{vote_id}/records",
    response_model=PaginatedResponse[MemberVoteItem],
    summary="Per-MEP voting records for a single roll-call vote",
    description="""**What it does**
Per-MEP vote positions (FOR / AGAINST / ABSTENTION / DID_NOT_VOTE) for one specific roll-call vote. Joins `ep_member_votes` to `ep_votes` so callers can see exactly how each named MEP voted, with their country and political-group code at the moment of the vote.

**When to use it**
- Build a "how did my MEP vote?" widget for any specific roll-call.
- Aggregate per-group or per-country breakdowns.
- Feed group-cohesion analysis or position-prediction models.

**Input**
- `vote_id` (path) — `ep_votes.id` (UUID).
- `group` — EP group code (e.g. `EPP`, `S&D`, `Renew`).
- `country` — ISO-2 (e.g. `DE`, `FR`).
- `position` — `FOR | AGAINST | ABSTENTION | DID_NOT_VOTE`.
- `limit` (1–500, default 100), `page` (default 1).

**Try it**
```
GET /api/v2/parliament/votes/{vote_id}/records?group=EPP
GET /api/v2/parliament/votes/{vote_id}/records?country=DE&position=AGAINST
```

**You get back**
Paginated `MemberVoteItem` envelope. `public_url` on each row points to the parent vote's HowTheyVote page. All 5 mandatory v1 datapoints present per row.

**Data freshness**
Synced every 6 hours (00:00 / 06:00 / 12:00 / 18:00 UTC) from HowTheyVote.eu (howtheyvote.eu) + EP plenary votes. HowTheyVote importer blocked on ep_political_groups.short_label collision — see CLAUDE.md.
""",
)
async def list_member_votes(
    vote_id: str,
    group: Optional[str] = Query(None),
    country: Optional[str] = Query(None),
    position: Optional[str] = Query(None, description="FOR | AGAINST | ABSTENTION | DID_NOT_VOTE"),
    limit: int = Query(100, ge=1, le=500),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[MemberVoteItem]:
    return await _v1.list_member_votes(vote_id=vote_id, group=group, country=country, position=position, limit=limit, page=page, user=user, db=db)


@ep_documents_router.get(
    "",
    response_model=PaginatedResponse[EPDocumentItem],
    summary="Unified view of all EP committee output — work items + amendments + adopted texts",
    description="""**What it does**
Returns a unified, cross-committee view that merges three separate document streams into one envelope: (1) `committee_work` items (high-level work programme entries with stage + rapporteur), (2) `amendment_documents` (PR=draft report, AM=amendments, RD=draft recommendation, AD=opinion, PA=draft opinion), and (3) `texts_adopted` (the formal plenary outputs). Each row carries a `source` field telling you which stream it came from and a `document_type` normalised across the three.

**When to use it**
When you want "everything that happened on file X across all stages" without making three separate queries. Useful for assembling a procedure timeline, building a committee activity dashboard, or answering "what is the LIBE committee working on this week?".

**Input**
- `committee` — 4-letter code (e.g. `LIBE`).
- `procedure_reference` — OEIL reference.
- `document_type` — normalised: `draft_report` / `report` / `amendments` / `opinion` / `minutes` / `resolution`.
- `q` — substring search across titles.
- `published_from`, `published_to` — date filter.
- `updated_from` — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/ep-documents?committee=LIBE&document_type=draft_report
GET /api/v2/parliament/ep-documents?procedure_reference=2025/0419(COD)
```

**You get back**
A `PaginatedResponse[EPDocumentItem]` envelope. Each item carries `id`, `source` (which stream this row came from), `document_type`, `committee_code`, `procedure_reference`, `pe_reference`, `title` (enriched with the procedure's plain-language alias when available via `_enrich_doc_title`), `rapporteur_name`, `document_date`, `document_url`, `total_amendments` (for amendment docs), `public_url`, and the 5 envelope-level datapoints.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC, warm tier) via the committee_work sync. Underlying tables (`committee_work_items`, `amendment_documents`, `texts_adopted`) are updated by separate syncs on hot/warm cadences.""",
)
async def list_ep_documents(
    request: Request,
    committee: Optional[str] = Query(None),
    procedure_reference: Optional[str] = Query(None),
    document_type: Optional[str] = Query(None, description="draft_report | report | amendments | opinion | minutes | resolution"),
    q: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[EPDocumentItem]:
    return await _v1.list_ep_documents(request=request, committee=committee, procedure_reference=procedure_reference, document_type=document_type, q=q, published_from=published_from, published_to=published_to, updated_from=updated_from, limit=limit, page=page, user=user, db=db)


@reports_router.get(
    "",
    response_model=PaginatedResponse[EPDocumentItem],
    summary="EP committee reports — draft reports + draft recommendations",
    description="""**What it does**
Returns EP committee reports — both `draft_report` (document type PR) and `draft_recommendation` (RD). These are the rapporteur's first written articulation of the EP's position on a legislative file, before amendments are tabled. Each row carries the procedure reference, the lead committee, the PE document reference, the rapporteur's name, the document date, and the doceo URL.

**When to use it**
Reports are the most quoted EP documents in advocacy work — they set the framing for the committee's negotiation. Use this endpoint to find "the latest report on the AI Act", "all draft reports by rapporteur X", or "all ENVI reports this year". The title is enriched with the procedure's plain-language alias (e.g. "draft_report for 2024/0079(COD) (ENVI)" becomes "draft_report for CBAM Downstream Extension (ENVI)").

**Input**
- `committee` — 4-letter committee code.
- `procedure_reference` — OEIL reference.
- `published_from`, `published_to` — date filter on `document_date`.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/reports?committee=ENVI&published_from=2026-01-01
GET /api/v2/parliament/reports?procedure_reference=2025/0419(COD)
```

**You get back**
A `PaginatedResponse[EPDocumentItem]` envelope, semantic-aliased subset of `/api/v2/parliament/ep-documents` filtered to `document_type ∈ {PR, RD}`. Each item carries `source="amendment_document"`, `document_type` (`draft_report` or `draft_recommendation`), `committee_code`, `procedure_reference`, `pe_reference`, enriched `title`, `rapporteur_name`, `document_date`, `document_url`, `total_amendments`, `last_updated`.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC, warm tier) via the committee_work + amendment_documents syncs from EP doceo.""",
)
async def list_reports(
    request: Request,
    committee: Optional[str] = Query(None),
    procedure_reference: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[EPDocumentItem]:
    return await _v1.list_reports(request=request, committee=committee, procedure_reference=procedure_reference, published_from=published_from, published_to=published_to, limit=limit, page=page, user=user, db=db)


@opinions_router.get(
    "",
    response_model=PaginatedResponse[EPDocumentItem],
    summary="EP associated-committee opinions — what other committees say about a lead committee's file",
    description="""**What it does**
Returns EP committee opinions — both `opinion` (document type AD, the formal adopted opinion) and `draft_opinion` (PA, the rapporteur for opinion's first draft). An opinion is what an associated committee says to the lead committee on a legislative file: e.g. ITRE's opinion to ENVI on the CBAM file. They are non-binding but influence the lead committee's report.

**When to use it**
To find which side-committees are weighing in on a file (e.g. all opinions on the AI Act → CULT, IMCO, JURI, LIBE), to track a specific committee's opinion-rapporteur output, or to assemble a procedure's full inter-committee picture. The `procedure_reference` filter scopes to one file.

**Input**
- `committee` — 4-letter committee code (the OPINIONING committee, not the lead).
- `procedure_reference` — OEIL reference.
- `published_from`, `published_to` — date filter on `document_date`.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/opinions?procedure_reference=2024/0079(COD)
GET /api/v2/parliament/opinions?committee=ITRE&published_from=2026-01-01
```

**You get back**
A `PaginatedResponse[EPDocumentItem]` envelope, semantic-aliased subset of `/api/v2/parliament/ep-documents` filtered to `document_type ∈ {AD, PA}`. Same shape as `/api/v2/parliament/reports`.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC, warm tier) via the committee_work + amendment_documents syncs from EP doceo.""",
)
async def list_opinions(
    request: Request,
    committee: Optional[str] = Query(None),
    procedure_reference: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[EPDocumentItem]:
    return await _v1.list_opinions(request=request, committee=committee, procedure_reference=procedure_reference, published_from=published_from, published_to=published_to, limit=limit, page=page, user=user, db=db)
