"""European Parliament domain — /api/v2/parliament/eprs/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.eprs); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import eprs as _v1
from api.v1.eprs import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/eprs", tags=["v2-parliament-eprs"])


@router.get(
    "",
    response_model=PaginatedResponse[EPRSItem],
    summary="EPRS think-tank publications — Parliament's research service (briefings, studies, in-depth)",
    description="""**What it does**
Returns publications from EPRS — the European Parliamentary Research Service, the EP's in-house think-tank. Covers briefings, studies, in-depth analyses, at-a-glance notes, "EU legislation in progress" tracker entries, initial appraisals, ex-post evaluations, and historical archives. Each row carries the publication ID + type, authors, summary, policy areas, related procedure refs and legal IDs, HTML + PDF URLs, and (when ingested) word + page counts.

**When to use it**
EPRS publications are the highest-quality non-partisan policy briefings on EU files — used by MEPs (and their staff) to understand legislation. Filter by `committee` to find what's been written for the LIBE committee, by `procedure_ref` for everything related to one file, or by `q` for free-text search.

**Input**
- `q` — substring on title + summary.
- `publication_type` — `BRIEFING` / `STUDY` / `IN_DEPTH_ANALYSIS` / `AT_A_GLANCE` / `EU_LEGISLATION_IN_PROGRESS` / `INITIAL_APPRAISAL` / `EX_POST_EVALUATION` / etc.
- `committee` — committee code.
- `procedure_ref` — OEIL reference.
- `celex` — legal identifier cross-link.
- `published_from`, `published_to` (and `published_end` alias).
- `updated_from`, `updated_to` (and `updated_end` alias) — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/eprs?committee=ENVI&publication_type=BRIEFING
GET /api/v2/parliament/eprs?q=CBAM&published_from=2026-01-01
```

**You get back**
A `PaginatedResponse[EPRSItem]` envelope. Each item carries `publication_id` (e.g. `EPRS_BRI(2026)762322`), `title`, `publication_type`, `publication_date`, `authors`, `summary`, `policy_areas`, `committees`, `related_celex_numbers`, `related_procedures`, `html_url`, `pdf_url`, `word_count`, `page_count`, plus the 5 envelope-level datapoints.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC, warm tier) from the EP Think Tank portal RSS (EPRS + ECTI + CASP) + the WordPress blog RSS as secondary source. EPRS publishes throughout the day; 12h sync catches new pieces inside a half-day.""",
)
async def list_eprs(
    request: Request,
    q: Optional[str] = Query(None, description="Substring search on title + summary"),
    publication_type: Optional[str] = Query(None, description="BRIEFING | STUDY | IN_DEPTH_ANALYSIS | AT_A_GLANCE | EU_LEGISLATION_IN_PROGRESS | ..."),
    committee: Optional[str] = Query(None, description="Committee code (LIBE, ENVI, ECON, ...)"),
    procedure_ref: Optional[str] = Query(None, description="OEIL procedure reference"),
    celex: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    published_end: Optional[date] = Query(None, description="Alias of published_to. 422 if both differ."),
    updated_from: Optional[datetime] = Query(None, description="Incremental sync — rows last_updated >= value. Returns rows ordered by last_updated desc when set."),
    updated_to: Optional[datetime] = Query(None),
    updated_end: Optional[datetime] = Query(None, description="Alias of updated_to. 422 if both differ."),
    limit: int = Query(50, ge=1, le=100, description="Items per page (default 50, max 100)"),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[EPRSItem]:
    return await _v1.list_eprs(request=request, q=q, publication_type=publication_type, committee=committee, procedure_ref=procedure_ref, celex=celex, published_from=published_from, published_to=published_to, published_end=published_end, updated_from=updated_from, updated_to=updated_to, updated_end=updated_end, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{publication_id}",
    response_model=EPRSItem,
    summary="Look up one EPRS publication by its publication_id — full metadata + links",
    description="""**What it does**
Fetches a single EPRS publication by its publication_id. Returns the same shape as the list endpoint, including HTML + PDF URLs for the full text and the related procedures / legal IDs the publication cross-references.

**When to use it**
After locating an EPRS publication via the list endpoint, use this to deep-link into a specific publication. The HTML URL is the canonical EP Think Tank page; the PDF URL is the direct download.

**Input**
- `publication_id` (path) — EPRS publication ID (e.g. `EPRS_BRI(2026)762322`). The `:path` matcher accepts parentheses verbatim.

**Try it**
```
GET /api/v2/parliament/eprs/EPRS_BRI(2026)762322
```

**You get back**
A single `EPRSItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — synced every 12 hours from the EP Think Tank portal.""",
)
async def get_eprs_detail(
    publication_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> EPRSItem:
    return await _v1.get_eprs_detail(publication_id=publication_id, user=user, db=db)
