"""European Parliament domain — /api/v2/parliament/meps/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.meps); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import meps as _v1
from api.v1.meps import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/meps", tags=["v2-parliament-meps"])


@router.get(
    "",
    response_model=PaginatedResponse[MEPItem],
    summary="Members of the European Parliament — list / search by country, group, name, term",
    description="""**What it does**
Live list of MEPs from the European Parliament's Open Data REST API v2. Each MEP carries the EP-internal id, full name, party of origin + EU political group, country, parliamentary term, photo, bio URL, committee assignments, and (when hydrated) email + social media handles. Both current and historical MEPs are searchable via `term`.

**When to use it**
Drive an MEP picker UI, find all MEPs from a country (`country=ES`), filter to one political group (`group=EPP`), or look up an MEP by name (`name=Sarri`). For historical research, set `term=9` for the 2019-2024 parliament. Per-MEP profile hydration (country / group / role) runs concurrently when the cache is warm — first cold call may take ~3-5s.

**Input**
- `country` — ISO-3166-1 alpha-2 (exact 2 chars).
- `group` — political group code (`EPP`, `S-D`, `RENEW`, `VERTS-ALE`, `ECR`, `PFE`, `ESN`, `GUE-NGL`, `NI`). Note: the EP API uses hyphens (S-D) but our `/political-groups` returns slugs (sd) — both are accepted.
- `name` — part of the full name, accent- and case-insensitive (`sole` finds `Solé`).
- `term` — parliamentary term (default 10 = current, valid range 1-10).
- `include_former` — current term only. By default the list holds the MEPs sitting today; `true` adds the members elected or seated this term who have since left (`in_office: false`). Any `updated_` window includes them too, so a sync sees a departure as a change.
""" + SYNC_PARAMS_DOC + """ Change dates are kept for the current term (10) only; a date window on an older term is a 422.
- `limit` (default 100, max 500), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/meps?country=ES&group=RENEW
GET /api/v2/parliament/meps?name=Sarri
GET /api/v2/parliament/meps?updated_from=2026-09-21&order=updated_asc&limit=500
```

**You get back**
A `PaginatedResponse[MEPItem]` envelope. Each item carries `id` (the EP's MEP id), `full_name`, `country` (ISO-3 code of citizenship, e.g. `ESP`), `group` (the EP's URI for the political group, e.g. `org/7018`), `role`, `profile_url`, `in_office`, plus the 5 datapoints (`public_url` = the EP profile page; `body_txt`/`body_html` = the MEP's card with membership history; `document_date` = start of the current mandate). """ + SYNC_FIELDS_DOC + """ `in_office` says whether the MEP sits today.

**Data freshness**
Read from data.europarl.europa.eu (the EP's Open Data REST API v2). For the current term the list, the sitting-MEP set and each MEP's record come from Brubru's daily snapshot plus a 6-hour cache, because the EP API rate-limits per-MEP profile calls. The change dates come from that daily snapshot of every current-term MEP (group, role, country, membership history), so `updated_date` moves the day after a change reaches the EP's data.""",
)
async def list_meps(
    request: Request,
    country: Optional[str] = Query(None, min_length=2, max_length=2),
    group: Optional[str] = Query(None),
    name: Optional[str] = Query(None),
    term: int = Query(10, ge=1, le=10, description="Parliamentary term (default 10 — current). Pass term=9 for previous, etc."),
    created_from: Optional[datetime] = Query(None, description="First recorded by Brubru on or after (current term only)."),
    created_to: Optional[UpperBoundDatetime] = Query(None, description="First recorded on or before; a bare date covers the whole day."),
    updated_from: Optional[datetime] = Query(None, description="Record last changed on or after. The incremental-sync filter (current term only)."),
    updated_to: Optional[UpperBoundDatetime] = Query(None, description="Record last changed on or before; a bare date covers the whole day."),
    include_former: bool = Query(False, description="Current term only: also list members who have left Parliament since the election (in_office=false). Always on with an updated_ window, so a sync learns about departures."),
    order: str = Query("ep", pattern="^(ep|updated_asc|updated_desc|created_asc|created_desc)$",
                       description="ep (default, the EP's own order) | updated_asc (use for incremental sync) | updated_desc | created_asc | created_desc."),
    limit: int = Query(100, ge=1, le=500, description="Items per page (default 100, max 500)"),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[MEPItem]:
    return await _v1.list_meps(request=request, country=country, group=group, name=name, term=term, created_from=created_from, created_to=created_to, updated_from=updated_from, updated_to=updated_to, include_former=include_former, order=order, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{mep_id}",
    response_model=MEPItem,
    summary="Look up one MEP by their EP-internal id — full profile + body composition",
    description="""**What it does**
Fetches a single MEP by their EP-internal id (a 5-7 digit numeric identifier visible on europarl.europa.eu URLs like `/meps/en/197488/...`). Returns the full profile including biographical info, committee assignments, declared meetings (when available), and the composed body (name + group + country + roles + contact details as a readable contact card).

**When to use it**
After locating an MEP via the list endpoint, use this for the full record — particularly when embedding an MEP card in a chat answer or building an MEP profile page. The body composition gives you a ready-to-render HTML/text card.

**Input**
- `mep_id` (path) — EP-internal MEP id (e.g. `197488`).

**Try it**
```
GET /api/v2/parliament/meps/197488
```

**You get back**
A single `MEPItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Live pass-through to data.europarl.europa.eu with a 6-hour in-process cache.""",
)
async def get_mep(
    mep_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> MEPItem:
    return await _v1.get_mep(mep_id=mep_id, user=user, db=db)
