"""European Parliament domain — /api/v2/parliament/parliamentary-questions/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.w4_endpoints); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import w4_endpoints as _v1
from api.v1.w4_endpoints import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


parl_q_router = APIRouter(prefix="/parliamentary-questions", tags=["v2-parliament-parliamentary-questions"])


@parl_q_router.get(
    "",
    response_model=PaginatedResponse[ParliamentaryQuestionItem],
    summary="European Parliament questions to Commission, Council or ECB — with answers",
    description="""**What it does**
Returns parliamentary questions submitted by MEPs to the Commission, Council, or ECB — written questions, oral questions, priority questions, and Question Time. Each row includes the original question text, the answering institution's reply when published, the asking MEPs, the answering commissioner (when applicable), related procedure/CELEX cross-references, and the canonical citizen URL on doceo.

**When to use it**
To track what MEPs are asking on a given policy area, find the official Commission position on an emerging topic before formal legislation drops, or build a "what's been asked about X" timeline. The `procedure_ref` filter lets you scope to questions related to a specific legislative file.

**Input**
- `q` — substring search on subject + question text + answer text.
- `question_type` — `written` / `oral` / `priority` / `question_time`.
- `parliamentary_term` — integer (current: 10).
- `asking_mep_id` — filter to questions asked by a specific MEP.
- `answering_institution` — `COMMISSION` / `COUNCIL` / `ECB`.
- `procedure_ref` — OEIL reference (e.g. `2026/0419(COD)`).
- `committee` — 4-letter committee code (e.g. `ENVI`).
- `published_from`, `published_to` — date filter on `submitted_date`.
- `updated_from` — incremental sync (rows where `last_updated >= value`).
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/parliamentary-questions?q=AI%20Act&limit=10
GET /api/v2/parliament/parliamentary-questions?committee=ENVI&published_from=2026-01-01
```

**You get back**
A `PaginatedResponse[ParliamentaryQuestionItem]` envelope. Each item carries `question_reference` (e.g. `E-001234/2026`), `question_type`, `subject`, `text_question`, `text_answer`, dates, asking-MEP arrays, `procedure_ref`, `related_celex`, `policy_areas`, `source_url`, `answer_url`, `body_txt` + `body_html` (semantic article with Question + Answer sections), plus the 5 envelope-level datapoints.

**Data freshness**
Synced once per day at 04:00 UTC (daily tier) from europarl.europa.eu/plenary/en/parliamentary-questions.html. New questions appear on doceo within hours of being tabled; answers can take days to weeks (Commission has up to 6 weeks under Rule 138). Scraper queued; endpoint returns empty result until ingestion completes.""",
)
async def list_parliamentary_questions(
    request: Request,
    q: Optional[str] = Query(None, description="Substring on subject + question text"),
    question_type: Optional[str] = Query(None, description="written | oral | priority | question_time"),
    parliamentary_term: Optional[int] = Query(None),
    asking_mep_id: Optional[str] = Query(None),
    answering_institution: Optional[str] = Query(None, description="COMMISSION | COUNCIL | ECB"),
    procedure_ref: Optional[str] = Query(None),
    committee: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None, description="submitted_date >= value"),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[ParliamentaryQuestionItem]:
    return await _v1.list_parliamentary_questions(request=request, q=q, question_type=question_type, parliamentary_term=parliamentary_term, asking_mep_id=asking_mep_id, answering_institution=answering_institution, procedure_ref=procedure_ref, committee=committee, published_from=published_from, published_to=published_to, updated_from=updated_from, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)


@parl_q_router.get(
    "/{question_reference:path}",
    response_model=ParliamentaryQuestionItem,
    summary="Look up one parliamentary question by its reference (e.g. E-001234/2026)",
    description="""**What it does**
Fetches a single parliamentary question by its reference. Returns the same shape as the list endpoint, including the original question text, the official answer when published, and the citizen URL on doceo.

**When to use it**
After locating a question via the list endpoint, use this to get the full text + answer in a deeper-link context (e.g. embedding in a chat response). Common pattern: `q` search → pick a reference → fetch detail.

**Input**
- `question_reference` (path) — e.g. `E-001234/2026` for a written question or `O-000123/2026` for an oral question. Format: `<TYPE>-<NUMBER>/<YEAR>` where TYPE ∈ {E, O, P, QT}.

**Try it**
```
GET /api/v2/parliament/parliamentary-questions/E-001234/2026
```

**You get back**
A single `ParliamentaryQuestionItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found` if no question with that reference exists in our mirror.

**Data freshness**
Same as the list endpoint — daily 04:00 UTC sync from europarl.europa.eu. If a question exists on doceo but not in our DB, it means it hasn't been picked up by the latest sync yet (max ~24h lag).""",
)
async def get_parl_question_detail(
    question_reference: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> ParliamentaryQuestionItem:
    return await _v1.get_parl_question_detail(question_reference=question_reference, body_threshold=body_threshold, user=user, db=db)
