"""European Parliament domain — /api/v2/parliament/resolutions/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.resolutions); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import resolutions as _v1
from api.v1.resolutions import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/resolutions", tags=["v2-parliament-resolutions"])


@router.get(
    "",
    response_model=PaginatedResponse[ResolutionItem],
    summary="EP non-legislative resolutions — own-initiative reports, legislative initiatives, topical resolutions",
    description="""**What it does**
Returns EP non-legislative outputs — files where the Parliament expresses a position WITHOUT directly amending EU law. Covers: `INL` (legislative initiative reports — EP asks the Commission to propose), `INI` (own-initiative reports — EP positions on horizontal themes), `RSP` (topical resolutions — urgent matters of EU concern, e.g. human rights, foreign policy). Each row carries the procedure ref, title, type, lead committee, rapporteur, adoption date, vote tallies, Commission follow-up status, and full text URL.

**When to use it**
EP resolutions don't have legal force but signal political direction — useful for advocacy work tracking what the EP demands of the Commission, urgent geopolitical positions, or thematic priorities. Filter by `has_commission_followup=true` to find resolutions where the Commission has actually responded.

**Input**
- `q` — substring on title + summary.
- `resolution_type` — `INL` / `INI` / `RSP` / `OTHER`.
- `lead_committee` — 4-letter committee code.
- `rapporteur` — name substring.
- `procedure_ref` — OEIL reference.
- `has_commission_followup` — boolean.
- `published_from`, `published_to` (and `published_end` alias) — adoption_date filter.
- `updated_from`, `updated_to` (and `updated_end` alias) — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/resolutions?resolution_type=INL&lead_committee=ENVI
GET /api/v2/parliament/resolutions?q=Ukraine&resolution_type=RSP
```

**You get back**
A `PaginatedResponse[ResolutionItem]` envelope. Each item carries `procedure_ref`, `title`, `resolution_type`, `lead_committee`, `rapporteur_name`, `adoption_date`, vote tallies, `has_commission_followup`, `full_text_url`, plus the 5 envelope-level datapoints.

**Data freshness**
Synced every 6 hours (00:00 / 06:00 / 12:00 / 18:00 UTC, hot tier) from OEIL XML feeds. Resolutions are adopted at EP plenary sittings; the post-plenary sync catches them inside hours.""",
)
async def list_resolutions(
    request: Request,
    q: Optional[str] = Query(None, description="Substring on title + summary"),
    resolution_type: Optional[str] = Query(None, description="INL | INI | RSP | OTHER"),
    lead_committee: Optional[str] = Query(None),
    rapporteur: Optional[str] = Query(None),
    procedure_ref: Optional[str] = Query(None),
    has_commission_followup: Optional[bool] = Query(None),
    published_from: Optional[date] = Query(None, description="adoption_date >= value"),
    published_to: Optional[date] = Query(None),
    published_end: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    updated_end: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[ResolutionItem]:
    return await _v1.list_resolutions(request=request, q=q, resolution_type=resolution_type, lead_committee=lead_committee, rapporteur=rapporteur, procedure_ref=procedure_ref, has_commission_followup=has_commission_followup, published_from=published_from, published_to=published_to, published_end=published_end, updated_from=updated_from, updated_to=updated_to, updated_end=updated_end, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{procedure_ref:path}",
    response_model=ResolutionItem,
    summary="Look up one EP resolution by its procedure reference",
    description="""**What it does**
Fetches a single EP resolution by its procedure reference. Returns the same shape as the list endpoint, with the full text URL + adoption details + Commission follow-up status.

**When to use it**
After locating a resolution via the list endpoint, use this for the full record — common pattern in chat answers when a user references a specific INI / RSP / INL number.

**Input**
- `procedure_ref` (path) — procedure reference (e.g. `2025/2125(INI)`, `2025/2887(RSP)`). The `:path` matcher accepts slashes + parentheses verbatim.

**Try it**
```
GET /api/v2/parliament/resolutions/2025/2125(INI)
```

**You get back**
A single `ResolutionItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — synced every 6 hours from OEIL XML feeds.""",
)
async def get_resolution_detail(
    procedure_ref: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> ResolutionItem:
    return await _v1.get_resolution_detail(procedure_ref=procedure_ref, user=user, db=db)
