"""European Parliament domain — /api/v2/parliament/resolution-procedures/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.resolutions); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import resolutions as _v1
from api.v1.resolutions import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/resolution-procedures", tags=["v2-parliament-resolution-procedures"])


@router.get(
    "",
    response_model=PaginatedResponse[ResolutionItem],
    summary="EP non-legislative resolutions — own-initiative reports, legislative initiatives, topical resolutions",
    description="""**What it does**
Returns EP non-legislative outputs — files where the Parliament expresses a position WITHOUT directly amending EU law. Covers: `INL` (legislative initiative reports — EP asks the Commission to propose), `INI` (own-initiative reports — EP positions on horizontal themes), `RSP` (topical resolutions — urgent matters of EU concern, e.g. human rights, foreign policy). Each row carries the procedure ref, title, type, lead committee, rapporteur, adoption date, vote tallies, Commission follow-up status, and full text URL.

One row per procedure, whatever its outcome: every INI, INL and RSP procedure the Legislative Observatory (OEIL) serves from 2024 onwards, read from OEIL itself. So a topical debate that ended with no motion voted is here as `closed_without_resolution`, and an own-initiative report still in committee as `pending`. Use `status=adopted` for adopted resolutions only.

**When to use it**
EP resolutions don't have legal force but signal political direction — useful for advocacy work tracking what the EP demands of the Commission, urgent geopolitical positions, or thematic priorities. Filter by `has_commission_followup=true` to find resolutions where the Commission has actually responded.

**Input**
- `q` — substring on title + summary.
- `resolution_type` — `INL` / `INI` / `RSP` / `OTHER`.
- `lead_committee` — 4-letter committee code.
- `rapporteur` — name substring.
- `procedure_ref` — OEIL reference.
- `has_commission_followup` — boolean.
- `status` — `adopted` / `pending` / `closed_without_resolution` (a debate or objection that ended in Parliament with no text adopted) / `rejected` (the final vote was lost).
- `published_from`, `published_to` (and `published_end` alias) — adoption_date filter.
- `updated_from`, `updated_to` (and `updated_end` alias) — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/resolution-procedures?resolution_type=INL&lead_committee=ENVI
GET /api/v2/parliament/resolution-procedures?q=Ukraine&resolution_type=RSP
```

**You get back**
A `PaginatedResponse[ResolutionItem]` envelope. Each item carries `procedure_ref`, `title`, `resolution_type`, `status`, `lead_committee`, `rapporteur`, `adoption_date`, `vote_date`, the final plenary vote (`vote_for` / `vote_against` / `vote_abstention` / `vote_total`, null when not counted), `has_commission_followup`, `eurovoc` / `eurovoc_codes` / `eurovoc_domain` (the Publications Office's EuroVoc indexing, once the text is in the Official Journal), `key_events` (the plenary vote, the Commission's dated follow-ups, or OEIL's own events for a resolution not adopted), `oeil_url`, `text_url`, plus `public_url` (the adopted text's own page), `body_txt` / `body_html` (the adopted text; the OEIL procedure page when Parliament has not published it yet), `document_date`, `creation_date` and `updated_date`.

**Data freshness**
Refreshed about every 6 hours (warm tier) from the Parliament's own sources: texts adopted and their full text (doceo), procedure pages and events (OEIL), final roll-call votes, and the Commission's follow-ups (EP Open Data). A resolution adopted at a plenary sitting appears once Parliament publishes its text, usually within a few days.""",
)
async def list_resolutions(
    request: Request,
    q: Optional[str] = Query(None, description="Substring on title + summary"),
    resolution_type: Optional[str] = Query(None, description="INL | INI | RSP | OTHER"),
    lead_committee: Optional[str] = Query(None),
    rapporteur: Optional[str] = Query(None),
    procedure_ref: Optional[str] = Query(None),
    has_commission_followup: Optional[bool] = Query(None),
    status: Optional[str] = Query(None, description="adopted | pending | closed_without_resolution | rejected"),
    published_from: Optional[date] = Query(None, description="adoption_date >= value"),
    published_to: Optional[date] = Query(None),
    published_end: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[UpperBoundDatetime] = Query(None),
    updated_end: Optional[UpperBoundDatetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[ResolutionItem]:
    return await _v1.list_resolutions(request=request, q=q, resolution_type=resolution_type, lead_committee=lead_committee, rapporteur=rapporteur, procedure_ref=procedure_ref, has_commission_followup=has_commission_followup, status=status, published_from=published_from, published_to=published_to, published_end=published_end, updated_from=updated_from, updated_to=updated_to, updated_end=updated_end, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{procedure_ref:path}",
    response_model=ResolutionItem,
    summary="Look up one EP resolution by its procedure reference",
    description="""**What it does**
Fetches a single EP resolution by its procedure reference. Returns the same shape as the list endpoint, with the full text URL + adoption details + Commission follow-up status.

**When to use it**
After locating a resolution via the list endpoint, use this for the full record — common pattern in chat answers when a user references a specific INI / RSP / INL number.

**Input**
- `procedure_ref` (path) — procedure reference (e.g. `2025/2125(INI)`, `2025/2887(RSP)`). The `:path` matcher accepts slashes + parentheses verbatim.

**Try it**
```
GET /api/v2/parliament/resolution-procedures/2025/2125(INI)
```

**You get back**
A single `ResolutionItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint: refreshed about every 6 hours from the Parliament's own sources.""",
)
async def get_resolution_detail(
    procedure_ref: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> ResolutionItem:
    return await _v1.get_resolution_detail(procedure_ref=procedure_ref, user=user, db=db)
