"""European Parliament domain — /api/v2/parliament/texts-adopted/* and /api/v2/parliament/texts-submitted/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.texts_adopted); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import texts_adopted as _v1
from api.v1.texts_adopted import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


texts_adopted_router = APIRouter(prefix="/texts-adopted", tags=["v2-parliament-texts-adopted"])

texts_submitted_router = APIRouter(prefix="/texts-submitted", tags=["v2-parliament-texts-submitted"])


@texts_adopted_router.get(
    "",
    response_model=PaginatedResponse[TextItem],
    summary="EP plenary texts that have been adopted — resolutions, legislative resolutions, decisions",
    description="""**What it does**
Returns every text adopted by the European Parliament in plenary session — legislative resolutions (the EP's formal positions on legislation), non-legislative resolutions (own-initiative + topical), decisions, recommendations. Each row carries the TA reference (e.g. `P10_TA(2025)0042`), the title, text type, procedure ref + parliamentary term, lead committee, rapporteur, adoption date, vote tallies, and the full-text URL.

**When to use it**
The authoritative record of what the EP has decided in plenary. Use to track positions on co-decision files (legislative_resolution), trace the EP's stance on a topic (resolution), or build a plenary outcomes dashboard. Pair with `/api/v2/parliament/texts-submitted` to see the pipeline from tabled → adopted.

**Input**
- `q` — substring on title + description.
- `text_type` — `resolution` / `legislative_resolution` / `decision` / `recommendation` / `other`.
- `procedure_ref` — OEIL reference.
- `parliamentary_term` — EP term (e.g. 10 for current, 9 for 2019-2024).
- `committee` — lead committee code.
- `rapporteur_mep_id` — filter to one rapporteur's adopted texts.
- `published_from`, `published_to` (and `published_end` alias) — adoption_date filter.
- `updated_from`, `updated_to` (and `updated_end` alias) — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/texts-adopted?text_type=legislative_resolution&committee=ENVI
GET /api/v2/parliament/texts-adopted?procedure_ref=2024/0079(COD)
```

**You get back**
A `PaginatedResponse[TextItem]` envelope. Each item carries `ta_reference`, `title`, `text_type`, `procedure_ref`, `parliamentary_term`, `committees`, `rapporteur_mep_id`, `rapporteur_name`, `adoption_date`, vote tallies, `full_text_url`, plus the 5 envelope-level datapoints.

**Data freshness**
Synced every 6 hours (00:00 / 06:00 / 12:00 / 18:00 UTC, hot tier) via RSS from europarl.europa.eu/plenary/en/texts-adopted.html. Texts appear within hours of plenary adoption.""",
)
async def list_texts_adopted(
    request: Request,
    q: Optional[str] = Query(None, description="Substring on title + description"),
    text_type: Optional[str] = Query(None, description="resolution | legislative_resolution | decision | recommendation | other"),
    procedure_ref: Optional[str] = Query(None),
    parliamentary_term: Optional[int] = Query(None, description="EP term, e.g. 9, 10"),
    committee: Optional[str] = Query(None),
    rapporteur_mep_id: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None, description="adoption_date >= value"),
    published_to: Optional[date] = Query(None),
    published_end: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    updated_end: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[TextItem]:
    return await _v1.list_texts_adopted(request=request, q=q, text_type=text_type, procedure_ref=procedure_ref, parliamentary_term=parliamentary_term, committee=committee, rapporteur_mep_id=rapporteur_mep_id, published_from=published_from, published_to=published_to, published_end=published_end, updated_from=updated_from, updated_to=updated_to, updated_end=updated_end, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)


@texts_adopted_router.get(
    "/{ta_reference}",
    response_model=TextItem,
    summary="Look up one EP plenary-adopted text by its TA reference (e.g. P10_TA(2025)0042)",
    description="""**What it does**
Fetches a single EP plenary-adopted text by its TA reference. Returns the same shape as the list endpoint, including the full-text URL and body composition.

**When to use it**
After locating a text via the list endpoint, use this for the deep-link. Common pattern in chat answers when a user references a specific P10_TA number.

**Input**
- `ta_reference` (path) — the TA reference (format: `P<TERM>_TA(<YEAR>)<NUMBER>`, e.g. `P10_TA(2025)0042`). The `:path` matcher accepts parentheses verbatim.

**Try it**
```
GET /api/v2/parliament/texts-adopted/P10_TA(2025)0042
```

**You get back**
A single `TextItem` (same shape as the list endpoint's `data[i]`), or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same as the list endpoint — synced every 6 hours from europarl.europa.eu/plenary/en/texts-adopted.html.""",
)
async def get_text_adopted_detail(
    ta_reference: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> TextItem:
    return await _v1.get_text_adopted_detail(ta_reference=ta_reference, body_threshold=body_threshold, user=user, db=db)


@texts_submitted_router.get(
    "",
    response_model=PaginatedResponse[TextItem],
    summary="EP plenary texts tabled but NOT YET adopted — the upcoming-vote pipeline",
    description="""**What it does**
Returns EP plenary texts that have been formally tabled for vote but not yet adopted (no adoption_date). Sibling endpoint to `/texts-adopted` — the same row "moves" from submitted to adopted when the plenary vote concludes. Each row carries the procedure ref, title, text type, parliamentary term, lead committee, rapporteur, the tabling date, and the doceo URL.

**When to use it**
For advocacy work focused on upcoming plenary votes — see what's coming next week, identify which committees have files in the pipeline, or filter by rapporteur to track an MEP's pending plenary texts. Pair with `/api/v1/calendar?event_type=PLENARY` to know WHEN each text is expected to be voted.

**Input**
Same shape as `/texts-adopted` — `q`, `text_type`, `procedure_ref`, `parliamentary_term`, `committee`, `rapporteur_mep_id`, date filters, incremental sync, pagination.

**Try it**
```
GET /api/v2/parliament/texts-submitted?committee=LIBE&parliamentary_term=10
GET /api/v2/parliament/texts-submitted?text_type=legislative_resolution
```

**You get back**
A `PaginatedResponse[TextItem]` envelope — same shape as `/texts-adopted`'s response, but with `adoption_date` null on every row (texts are pre-adoption).

**Data freshness**
Synced every 6 hours (00:00 / 06:00 / 12:00 / 18:00 UTC, hot tier) from europarl.europa.eu/plenary/en/texts-submitted.html. New tablings appear on doceo within hours; the 6h sync catches them.""",
)
async def list_texts_submitted(
    request: Request,
    q: Optional[str] = Query(None),
    text_type: Optional[str] = Query(None),
    procedure_ref: Optional[str] = Query(None),
    parliamentary_term: Optional[int] = Query(None),
    committee: Optional[str] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    updated_end: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[TextItem]:
    return await _v1.list_texts_submitted(request=request, q=q, text_type=text_type, procedure_ref=procedure_ref, parliamentary_term=parliamentary_term, committee=committee, updated_from=updated_from, updated_to=updated_to, updated_end=updated_end, limit=limit, page=page, body_threshold=body_threshold, user=user, db=db)
