"""European Parliament domain — /api/v2/parliament/committee-transcripts/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.transcripts); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import transcripts as _v1
from api.v1.transcripts import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/committee-transcripts", tags=["v2-parliament-committee-transcripts"])


@router.get(
    "",
    response_model=PaginatedResponse[CommitteeTranscriptOut],
    summary="EP committee meeting transcripts — full AI transcript of committee webstreams",
    description="""**What it does**
Returns AI-generated transcripts of European Parliament committee (and subcommittee) meetings, produced from the EP Multimedia Centre webstream recordings. Each row carries the committee, meeting date, title, word count, duration, mapped agenda items, the procedure references discussed, and a link to the official recording. This is the textual companion to `/api/v2/parliament/webstreams` (which gives the stream URL + transcript status); this endpoint gives the transcript content itself.

**When to use it**
To read what was actually said in a committee debate — search a committee's deliberations, pull every meeting that discussed a given procedure, or feed a verbatim debate record into your own analysis. For the official summary record instead, use `/api/v2/parliament/committees/{code}/minutes`.

**Input**
- `committee` — EP committee/subcommittee code (e.g. `LIBE`, `ENVI`, `DROI`).
- `procedure_reference` — return only meetings that discussed this procedure (e.g. `2024/0079(COD)`); matches the transcript's mapped `related_procedure_refs`.
- `q` — substring search across the meeting title and the transcript text.
- `has_transcript` — `true` (default) returns only meetings with a completed transcript; set `false` to also see scheduled/pending/failed rows.
- `status` — filter on processing status (`completed`, `pending`, `transcribing`, `failed`).
- `published_from` / `published_to` (aliased `date_from` / `date_to`) — `meeting_date` range.
- `updated_from` — rows updated at/after this timestamp (incremental sync).
- `body_threshold` — minimum transcript length (chars) for `has_body=true`. Default 500.
- `limit` (default 10, max 50 — bodies are always returned and each is large), `page` (1-indexed).

**Try it**
```
GET /api/v2/parliament/committee-transcripts?committee=LIBE
GET /api/v2/parliament/committee-transcripts?procedure_reference=2024/0079(COD)
GET /api/v2/parliament/committee-transcripts?committee=ENVI&limit=3
```

**You get back**
A `PaginatedResponse[CommitteeTranscriptOut]`. Each row carries `committee_code`, `title`, `meeting_date`, `word_count`, `duration_seconds`, `speaker_count`, `agenda_items[]`, `related_procedure_refs[]`, plus the 5 envelope datapoints: `public_url` (the recording page), `body_txt` + `body_html` (the full transcript — always populated when a transcript exists), `document_date` (the meeting date), and `creation_date` (when Brubru transcribed it).

**Data freshness**
Transcribed from EP Multimedia Centre recordings via OpenAI Whisper (`backend/scripts/transcribe_pending_committees.py`). New committee recordings appear on the Multimedia Centre within hours of a meeting; transcription runs as a batch job after the recording is published.""",
)
async def list_committee_transcripts(
    request: Request,
    committee: Optional[str] = Query(None, description="EP committee/subcommittee code (e.g. LIBE)."),
    procedure_reference: Optional[str] = Query(None, description="Return only meetings that discussed this procedure ref."),
    q: Optional[str] = Query(None, description="Substring search on title + transcript text."),
    has_transcript: bool = Query(True, description="True (default) = only meetings with a completed transcript."),
    status: Optional[str] = Query(None, description="completed | pending | transcribing | failed"),
    published_from: Optional[date] = Query(None, alias="date_from"),
    published_to: Optional[date] = Query(None, alias="date_to"),
    updated_from: Optional[datetime] = Query(None),
    body_threshold: int = Depends(body_threshold_param),
    limit: int = Query(10, ge=1, le=50, description="Items per page (default 10, max 50 — full body is always returned, each transcript is large)."),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CommitteeTranscriptOut]:
    return await _v1.list_committee_transcripts(request=request, committee=committee, procedure_reference=procedure_reference, q=q, has_transcript=has_transcript, status=status, published_from=published_from, published_to=published_to, updated_from=updated_from, body_threshold=body_threshold, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{transcript_id}",
    response_model=CommitteeTranscriptOut,
    summary="One committee meeting transcript by id — full transcript text + HTML",
    description="""**What it does**
Fetches a single committee meeting transcript by its Brubru-internal UUID, always with the full body: `body_txt` (the verbatim Whisper transcript) and `body_html` (the same text structured one paragraph per segment, with speaker labels when known).

**When to use it**
After locating a meeting via the list endpoint, use this to pull the complete transcript for display or downstream processing.

**Input**
- `transcript_id` (path) — the Brubru-internal UUID from the list endpoint's `id`.

**Try it**
```
GET /api/v2/parliament/committee-transcripts/{transcript_id}
```

**You get back**
A single `CommitteeTranscriptOut` (same shape as the list endpoint's `data[i]`), always with `body_txt` + `body_html` populated when a transcript exists, or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Transcribed from EP Multimedia Centre recordings via OpenAI Whisper. Re-transcription updates `creation_date` (transcribed_at).""",
)
async def get_committee_transcript_detail(
    transcript_id: str,
    body_threshold: int = Depends(body_threshold_param),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CommitteeTranscriptOut:
    return await _v1.get_committee_transcript_detail(transcript_id=transcript_id, body_threshold=body_threshold, user=user, db=db)
