"""European Parliament domain — /api/v2/parliament/webstreams/*.

LIVE — copy-pasted verbatim from the v1 EP surface (api.v1.webstreams); the body
delegates to the v1 handler so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/parliament/*.

Generated by scripts/_gen_v2_parliament.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import webstreams as _v1
from api.v1.webstreams import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/webstreams", tags=["v2-parliament-webstreams"])


@router.get(
    "",
    response_model=PaginatedResponse[WebstreamItem],
    summary="EP committee webstreams — meeting URLs + transcripts (multimedia.europarl.europa.eu)",
    description="""**What it does**
Every EP committee meeting webstream URL discovered by Brubru's daily scrape of `multimedia.europarl.europa.eu/en/webstreaming`. Each row carries the multimedia landing-page URL (`public_url`), the direct video URL when extracted, the meeting date, the committee code (LIBE, ENVI, ECON, …), and — when Whisper has run — the transcript metadata (duration, speaker count, word count).

**When to use it**
- Build per-committee streaming dashboards.
- Track which committee meetings already have a Brubru transcript.
- Filter to meetings linked to a specific OEIL procedure file.
- Drive incremental sync with `updated_from`.

**Input**
- `committee` — EP committee code (LIBE, ENVI, ECON, IMCO, …).
- `status` — `PENDING | COMPLETED | FAILED | NOT_AVAILABLE` (transcription status, not the meeting itself).
- `has_transcript` — true to filter to rows with a transcript already extracted.
- `procedure_ref` — OEIL reference (e.g. `2024/0123(COD)`) to filter to meetings discussing that file.
- `q` — substring on title.
- `published_from` / `published_to` — meeting-date range.
- `updated_from` / `updated_to` — incremental sync.
- `limit` (1–100, default 50), `page` (default 1).

**Try it**
```
GET /api/v2/parliament/webstreams?committee=LIBE&has_transcript=true
GET /api/v2/parliament/webstreams?procedure_ref=2024%2F0123(COD)
GET /api/v2/parliament/webstreams?updated_from=2026-05-01
```

**You get back**
Paginated `WebstreamItem` envelope. `public_url` is the meeting's `multimedia.europarl.europa.eu` landing page (real, specific). `meeting_start_date` carries the meeting timestamp. All 5 mandatory v1 datapoints present per row.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC) from EP committee + plenary webstreams (europarl.europa.eu/committees/.../webstreaming). Transcription fires on-demand when chatbot query hits transcript intent.
""",
)
async def list_webstreams(
    request: Request,
    committee: Optional[str] = Query(None, description="EP committee code (LIBE, ENVI, ECON, ...)"),
    status: Optional[str] = Query(None, description="PENDING | COMPLETED | FAILED | NOT_AVAILABLE"),
    has_transcript: Optional[bool] = Query(None, description="If true, only rows with transcript_text"),
    procedure_ref: Optional[str] = Query(None, description="Filter to streams linked to a procedure"),
    q: Optional[str] = Query(None, description="Substring on title"),
    published_from: Optional[date] = Query(None, description="meeting_date >= value"),
    published_to: Optional[date] = Query(None),
    published_end: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    updated_end: Optional[datetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[WebstreamItem]:
    return await _v1.list_webstreams(request=request, committee=committee, status=status, has_transcript=has_transcript, procedure_ref=procedure_ref, q=q, published_from=published_from, published_to=published_to, published_end=published_end, updated_from=updated_from, updated_to=updated_to, updated_end=updated_end, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{stream_id}",
    response_model=WebstreamItem,
    summary="Look up one EP committee webstream by its internal id — metadata + transcript status",
    description="""**What it does**
Returns full metadata for one committee-meeting webstream, including the multimedia landing page (`public_url`), direct video URL, meeting date, transcript status, and (when COMPLETED) duration / speaker / word counts.

**When to use it**
After locating a webstream via the list endpoint, use this for the full record — particularly to check transcript status before requesting transcription, or to deep-link into a specific committee meeting in an analysis.

**Input**
- `stream_id` (path) — `committee_meeting_transcripts.id` (UUID).

**Try it**
```
GET /api/v2/parliament/webstreams/{stream_id}
```

**You get back**
A `WebstreamItem` with all 5 mandatory v1 datapoints. Follow `public_url` to view/replay the meeting on multimedia.europarl.europa.eu.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC) from EP committee + plenary webstreams (europarl.europa.eu/committees/.../webstreaming). Transcription fires on-demand when chatbot query hits transcript intent.
""",
)
async def get_webstream_detail(
    stream_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> WebstreamItem:
    return await _v1.get_webstream_detail(stream_id=stream_id, user=user, db=db)


@router.get(
    "/by-procedure/{procedure_ref:path}/transcript",
    response_model=PaginatedResponse[WebstreamItem],
    summary="Webstreams linked to a specific legislative procedure — every committee debate end-to-end",
    description="""**What it does**
Returns every committee-meeting webstream whose `related_procedure_refs` array contains the given procedure reference (OEIL identifier). Useful for tracking every committee debate of a specific legislative file end-to-end.

**When to use it**
To assemble a "complete debate timeline" for an advocacy brief on a specific file — pull every meeting where the file appeared, sorted by date, with deep-links to the multimedia replays. Combine with `/api/v2/parliament/amendments?procedure_reference=X` for the amendments tabled at each meeting.

**Input**
- `procedure_ref` (path) — procedure reference, e.g. `2024/0123(COD)`. URL-encode the slash as `%2F` or use the `:path` matcher which accepts it verbatim.
- `limit` (1–100, default 50), `page` (default 1).

**Try it**
```
GET /api/v2/parliament/webstreams/by-procedure/2024%2F0123(COD)/transcript
```

**You get back**
Paginated `WebstreamItem` envelope ordered by meeting_date desc. Each row's `public_url` resolves to the specific multimedia.europarl.europa.eu meeting page. All 5 mandatory v1 datapoints present per row.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC) from EP committee + plenary webstreams (europarl.europa.eu/committees/.../webstreaming). Transcription fires on-demand when chatbot query hits transcript intent.
""",
)
async def get_webstreams_for_procedure(
    procedure_ref: str,
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[WebstreamItem]:
    return await _v1.get_webstreams_for_procedure(procedure_ref=procedure_ref, limit=limit, page=page, user=user, db=db)
