"""Eurogroup domain — /api/v2/eurogroup/eurogroup-meetings/* and /api/v2/eurogroup/eurogroup-documents/* and /api/v2/eurogroup/eurogroup-work-programme/* and /api/v2/eurogroup/eurogroup-members/* and /api/v2/eurogroup/eurogroup-about/*.

LIVE — copy-pasted verbatim from the v1 surface (api.v1.eurogroup); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/eurogroup/*.

Generated by scripts/_gen_v2_consilium_folders.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import eurogroup as _v1
from api.v1.eurogroup import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


from api.v1.eurogroup import _DESC, _params  # noqa: F401 - used in decorators

meetings_router = APIRouter(prefix="/eurogroup-meetings", tags=["v2-eurogroup-meetings"])
documents_router = APIRouter(prefix="/eurogroup-documents", tags=["v2-eurogroup-documents"])
work_programme_router = APIRouter(prefix="/eurogroup-work-programme", tags=["v2-eurogroup-work-programme"])
members_router = APIRouter(prefix="/eurogroup-members", tags=["v2-eurogroup-members"])
about_router = APIRouter(prefix="/eurogroup-about", tags=["v2-eurogroup-about"])


@meetings_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Eurogroup meetings — meetings of euro-area finance ministers",
    description=_DESC(
        "Returns Eurogroup meetings (the euro-area finance ministers), with date and a body that includes the published 'Main results' outcome narrative for recent meetings — macroeconomic discussions, the digital euro, euro-area competitiveness, and more.",
        "To track what euro-area finance ministers discussed and concluded — the political steer on euro-area economic policy.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of Eurogroup meetings.",
        "GET /api/v2/eurogroup/eurogroup-meetings",
    ),
)
async def list_eurogroup_meetings(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_eurogroup_meetings(request=request, params=params, user=user, db=db)


@meetings_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Eurogroup meeting by id — full body (agenda + outcomes)",
    description="Fetch a single Eurogroup meeting by its Brubru UUID. Returns the five datapoints. 404 with `reason_code: not_found` if absent.",
)
async def get_eurogroup_meeting(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_eurogroup_meeting(item_id=item_id, user=user, db=db)


@documents_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Eurogroup documents — the Eurogroup document register",
    description=_DESC(
        "Returns documents from the Eurogroup document register — draft agendas, annotated agendas, summing-up letters, lists of participants, and the President's remarks — each with date and a link to the PDF.",
        "To read the Eurogroup's own meeting documents, especially the summing-up letters that record the outcome of each meeting.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of Eurogroup documents.",
        "GET /api/v2/eurogroup/eurogroup-documents?q=summing-up",
    ),
)
async def list_eurogroup_documents(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_eurogroup_documents(request=request, params=params, user=user, db=db)


@documents_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Eurogroup document by id — full body",
    description="Fetch a single Eurogroup document by its Brubru UUID. Returns the five datapoints; `pdf_url` is the document PDF. 404 if absent.",
)
async def get_eurogroup_document(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_eurogroup_document(item_id=item_id, user=user, db=db)


@work_programme_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Eurogroup work programme",
    description=_DESC(
        "Returns the Eurogroup work programme — the rolling agenda of priorities the Eurogroup sets itself for the coming period — with the programme text and a link to the PDF.",
        "To see what the Eurogroup plans to work on, the forward calendar of euro-area economic policy themes.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` with the work-programme entry.",
        "GET /api/v2/eurogroup/eurogroup-work-programme",
    ),
)
async def list_eurogroup_work_programme(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_eurogroup_work_programme(request=request, params=params, user=user, db=db)


@work_programme_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Eurogroup work-programme entry by id — full body",
    description="Fetch the Eurogroup work-programme entry by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_eurogroup_work_programme(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_eurogroup_work_programme(item_id=item_id, user=user, db=db)


@members_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Members of the Eurogroup",
    description=_DESC(
        "Returns the members of the Eurogroup — the finance ministers of the euro-area member states, plus the Eurogroup President — including the inclusive-format membership, as a reference entry.",
        "As a reference for who sits in the Eurogroup, in both regular and inclusive formats.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of members entries.",
        "GET /api/v2/eurogroup/eurogroup-members",
    ),
)
async def list_eurogroup_members(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_eurogroup_members(request=request, params=params, user=user, db=db)


@members_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Eurogroup members entry by id — full body",
    description="Fetch a single Eurogroup members entry by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_eurogroup_member(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_eurogroup_member(item_id=item_id, user=user, db=db)


@about_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="About the Eurogroup — how it works, the working group, transparency, history",
    description=_DESC(
        "Returns institutional reference pages about the Eurogroup — how it works, the Eurogroup Working Group (EWG) that prepares its meetings, its transparency arrangements, and its history — each with the page text as body.",
        "As background reference on the Eurogroup as a body and how it operates.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of reference entries.",
        "GET /api/v2/eurogroup/eurogroup-about",
    ),
)
async def list_eurogroup_about(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_eurogroup_about(request=request, params=params, user=user, db=db)


@about_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Eurogroup reference page by id — full body",
    description="Fetch a single Eurogroup reference page by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_eurogroup_about(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_eurogroup_about(item_id=item_id, user=user, db=db)
