"""Council of the EU domain — /api/v2/council/council-meetings/* and /api/v2/council/council-voting-results/* and /api/v2/council/council-register/* and /api/v2/council/council-oj-agendas/* and /api/v2/council/council-preparatory-bodies/* and /api/v2/council/council-press-releases/* and /api/v2/council/council-research-papers/* and /api/v2/council/council-treaties-agreements/*.

LIVE — copy-pasted verbatim from the v1 Council surface (api.v1.council_register); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/council/*.

Generated by scripts/_gen_v2_council.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import council_register as _v1
from api.v1.council_register import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


from api.v1.council_register import _DESC  # noqa: F401 - used in decorators

meetings_router = APIRouter(prefix="/council-meetings", tags=["v2-council-meetings"])
votes_router = APIRouter(prefix="/council-voting-results", tags=["v2-council-voting-results"])
register_router = APIRouter(prefix="/council-register", tags=["v2-council-register"])
oj_router = APIRouter(prefix="/council-oj-agendas", tags=["v2-council-oj-agendas"])
prep_router = APIRouter(prefix="/council-preparatory-bodies", tags=["v2-council-preparatory-bodies"])
press_router = APIRouter(prefix="/council-press-releases", tags=["v2-council-press-releases"])
research_router = APIRouter(prefix="/council-research-papers", tags=["v2-council-research-papers"])
treaties_router = APIRouter(prefix="/council-treaties-agreements", tags=["v2-council-treaties-agreements"])


@meetings_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Council of the EU meetings — ministerial meetings with agenda and outcomes",
    description=_DESC(
        "Returns Council of the EU ministerial meetings (the ten configurations) with their date, configuration, and a body composed from the meeting facts — including the published 'Main results' outcome narrative for recent meetings.",
        "To track what the Council decided in a given configuration (the co-legislator opposite the European Parliament), or to list upcoming and recent ministerial meetings by formation.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of meetings.",
        "GET /api/v2/council/council-meetings?council_configuration=ECOFIN",
    ),
)
async def list_council_meetings(
    request: Request,
    q: Optional[str] = Query(None),
    council_configuration: Optional[str] = Query(None),
    interinstitutional_ref: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_council_meetings(request=request, q=q, council_configuration=council_configuration, interinstitutional_ref=interinstitutional_ref, published_from=published_from, published_to=published_to, updated_from=updated_from, updated_to=updated_to, limit=limit, page=page, user=user, db=db)


@meetings_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Council meeting by id — full body (agenda + outcomes)",
    description="Fetch a single Council meeting by its Brubru UUID. Returns the same shape as the list endpoint with the five datapoints filled. 404 with `reason_code: not_found` if absent.",
)
async def get_council_meeting(
    item_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_council_meeting(item_id=item_id, user=user, db=db)


@votes_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Council of the EU voting results — results of public Council votes",
    description=_DESC(
        "Returns the results of public Council votes from the Council's public document register — the document number (ST/CM), the act being voted, the interinstitutional procedure file, the subject matters, and a link to the full voting-result PDF on the un-walled data.consilium store.",
        "To see how the Council voted on a legislative act (the per-member-state for/against/abstain tally is in the linked PDF), and to join a Council vote to its EP co-decision file via the interinstitutional reference.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of voting-result documents.",
        "GET /api/v2/council/council-voting-results?interinstitutional_ref=2021/0297(COD)",
    ),
)
async def list_council_voting_results(
    request: Request,
    q: Optional[str] = Query(None),
    council_configuration: Optional[str] = Query(None),
    interinstitutional_ref: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_council_voting_results(request=request, q=q, council_configuration=council_configuration, interinstitutional_ref=interinstitutional_ref, published_from=published_from, published_to=published_to, updated_from=updated_from, updated_to=updated_to, limit=limit, page=page, user=user, db=db)


@votes_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Council voting result by id — full body",
    description="Fetch a single Council voting-result document by its Brubru UUID. Returns the five datapoints; the per-member-state tally is in the linked PDF. 404 if absent.",
)
async def get_council_voting_result(
    item_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_council_voting_result(item_id=item_id, user=user, db=db)


@register_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Council of the EU public register — latest documents",
    description=_DESC(
        "Returns the latest documents from the Council of the EU public document register — working-party notes, meeting documents (CM), Council notes (ST) — each with its document number, date, and a link to the PDF on the un-walled data.consilium store.",
        "To monitor what the Council's working parties and COREPER are circulating in near-real-time — the earliest signal of Council-side legislative activity.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of register documents.",
        "GET /api/v2/council/council-register?q=working+party",
    ),
)
async def list_council_register(
    request: Request,
    q: Optional[str] = Query(None),
    council_configuration: Optional[str] = Query(None),
    interinstitutional_ref: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_council_register(request=request, q=q, council_configuration=council_configuration, interinstitutional_ref=interinstitutional_ref, published_from=published_from, published_to=published_to, updated_from=updated_from, updated_to=updated_to, limit=limit, page=page, user=user, db=db)


@register_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Council register document by id — full body",
    description="Fetch a single Council public-register document by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_council_register_document(
    item_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_council_register_document(item_id=item_id, user=user, db=db)


@oj_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Council of the EU OJ agendas — meeting agendas from the OJ of the Council",
    description=_DESC(
        "Returns the agendas of Council meetings as published in the OJ-of-the-Council section of the public register — one row per configuration meeting, with the agenda document number and a link to the agenda PDF.",
        "To read the formal agenda of a Council meeting (the legal record of what each configuration was convened to decide), ahead of or after the meeting.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of meeting-agenda documents.",
        "GET /api/v2/council/council-oj-agendas?published_from=2026-01-01",
    ),
)
async def list_council_oj_agendas(
    request: Request,
    q: Optional[str] = Query(None),
    council_configuration: Optional[str] = Query(None),
    interinstitutional_ref: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_council_oj_agendas(request=request, q=q, council_configuration=council_configuration, interinstitutional_ref=interinstitutional_ref, published_from=published_from, published_to=published_to, updated_from=updated_from, updated_to=updated_to, limit=limit, page=page, user=user, db=db)


@oj_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Council OJ agenda by id — full body",
    description="Fetch a single Council OJ meeting-agenda document by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_council_oj_agenda(
    item_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_council_oj_agenda(item_id=item_id, user=user, db=db)


@prep_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Council of the EU preparatory bodies — COREPER and working-party meetings",
    description=_DESC(
        "Returns meetings of the Council's preparatory bodies — COREPER I/II and the working parties that do the technical groundwork before ministerial Council meetings.",
        "To track where on the Council ladder a file currently sits (working party -> COREPER -> Council), the most granular view of Council-side progress on a dossier.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of preparatory-body meetings.",
        "GET /api/v2/council/council-preparatory-bodies?q=land+transport",
    ),
)
async def list_council_preparatory_bodies(
    request: Request,
    q: Optional[str] = Query(None),
    council_configuration: Optional[str] = Query(None),
    interinstitutional_ref: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_council_preparatory_bodies(request=request, q=q, council_configuration=council_configuration, interinstitutional_ref=interinstitutional_ref, published_from=published_from, published_to=published_to, updated_from=updated_from, updated_to=updated_to, limit=limit, page=page, user=user, db=db)


@prep_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Council preparatory-body meeting by id — full body",
    description="Fetch a single Council preparatory-body (COREPER / working party) meeting by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_council_preparatory_body(
    item_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_council_preparatory_body(item_id=item_id, user=user, db=db)


@press_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Council of the EU press releases — press releases and statements",
    description=_DESC(
        "Returns Council of the EU press releases and statements with their full text body — the official communication of Council decisions, agreements and ministerial remarks.",
        "To read the Council's own account of what it decided, in plain language, the moment it is published — the fastest authoritative narrative of Council outcomes.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of press releases.",
        "GET /api/v2/council/council-press-releases?q=defence",
    ),
)
async def list_council_press_releases(
    request: Request,
    q: Optional[str] = Query(None),
    council_configuration: Optional[str] = Query(None),
    interinstitutional_ref: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_council_press_releases(request=request, q=q, council_configuration=council_configuration, interinstitutional_ref=interinstitutional_ref, published_from=published_from, published_to=published_to, updated_from=updated_from, updated_to=updated_to, limit=limit, page=page, user=user, db=db)


@press_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Council press release by id — full text",
    description="Fetch a single Council press release by its Brubru UUID. The body is the full press-release text. Returns the five datapoints. 404 if absent.",
)
async def get_council_press_release(
    item_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_council_press_release(item_id=item_id, user=user, db=db)


@research_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Council of the EU research papers — ART (Analysis and Research Team) papers",
    description=_DESC(
        "Returns Council research papers published by the General Secretariat's Analysis and Research Team (ART) — foresight and analytical papers feeding Council strategic discussions. Each row links to the paper PDF.",
        "To mine the Council's in-house strategic analysis — an under-used source of where Council thinking is heading on cross-cutting themes.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of research papers. `public_url`/`pdf_url` point to the paper PDF.",
        "GET /api/v2/council/council-research-papers",
    ),
)
async def list_council_research_papers(
    request: Request,
    q: Optional[str] = Query(None),
    council_configuration: Optional[str] = Query(None),
    interinstitutional_ref: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_council_research_papers(request=request, q=q, council_configuration=council_configuration, interinstitutional_ref=interinstitutional_ref, published_from=published_from, published_to=published_to, updated_from=updated_from, updated_to=updated_to, limit=limit, page=page, user=user, db=db)


@research_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Council research paper by id — full body",
    description="Fetch a single Council ART research paper by its Brubru UUID. Returns the five datapoints; `pdf_url` is the paper PDF. 404 if absent.",
)
async def get_council_research_paper(
    item_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_council_research_paper(item_id=item_id, user=user, db=db)


@treaties_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Council of the EU treaties & agreements — the Council's treaties database",
    description=_DESC(
        "Returns a reference entry for the Council of the EU's Treaties and Agreements database (the Council is depositary for many EU international agreements), with the canonical search URL and the database description as the body.",
        "As a pointer to the authoritative Council database of EU treaties and international agreements when you need to look one up by name or party.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` with the treaties-database reference entry.",
        "GET /api/v2/council/council-treaties-agreements",
    ),
)
async def list_council_treaties_agreements(
    request: Request,
    q: Optional[str] = Query(None),
    council_configuration: Optional[str] = Query(None),
    interinstitutional_ref: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[datetime] = Query(None),
    limit: int = Query(25, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_council_treaties_agreements(request=request, q=q, council_configuration=council_configuration, interinstitutional_ref=interinstitutional_ref, published_from=published_from, published_to=published_to, updated_from=updated_from, updated_to=updated_to, limit=limit, page=page, user=user, db=db)


@treaties_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Council treaties/agreements entry by id — full body",
    description="Fetch a single Council treaties-&-agreements entry by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_council_treaty_agreement(
    item_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_council_treaty_agreement(item_id=item_id, user=user, db=db)
