"""Council of the EU domain — /api/v2/council/council-documents/* and /api/v2/council/council-configurations/*.

LIVE — copy-pasted verbatim from the v1 Council surface (api.v1.council_documents); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/council/*.

Generated by scripts/_gen_v2_council.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._body import body_threshold_param  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse, build_envelope  # noqa: F401
from api.v1 import council_documents as _v1
from api.v1.council_documents import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


router = APIRouter(prefix="/council-documents", tags=["v2-council-council-documents"])
configurations_router = APIRouter(prefix="/council-configurations", tags=["v2-council-configurations"])


@router.get(
    "",
    response_model=PaginatedResponse[CouncilDocumentItem],
    summary="Council of the EU documents — press releases, conclusions, meeting agendas, summits",
    description="""**What it does**
Returns a unified feed of Council of the EU + European Council documents and meetings — press releases, Council register documents (notes, working documents, presidency discussion notes), meeting agendas and summit outcomes. It unions Council-tagged `institutional_publications` with `eu_calendar_events` for COUNCIL / EUROPEAN_COUNCIL.

**What the corpus covers, and what it does not**
Read `coverage_note`, `coverage_from` and `coverage_to` on every response before concluding that an empty result means the Council said nothing. The register's SEARCH is behind a Cloudflare challenge (re-checked 24 September 2026 against plain HTTP, a stealth browser and three Scrape.do modes), so documents reach Brubru through the register's own unwalled listings (latest documents, provisional agendas) and the full press-release feed. That is a broad slice, not the complete Council corpus. Until 27 August 2026 the document half held **zero rows** and this endpoint returned only meetings, so a query like `?q=minors` came back empty and read as Council silence — while 25 Member States had in fact signed the Jutland Declaration on protecting minors online.

**When to use it**
For tracking Council positions on legislative files (the "other half" of EP-Council co-decision), summit conclusions (the political guidance feeding into Commission proposals), and ministerial meetings. The Council moves more slowly than the EP but its political conclusions are the most authoritative signal of where EU policy is heading.

**Input**
- `source` — `documents` (default): the register and press corpus. `meetings`: Council meetings from the calendar. `all`: both. Until 24 September 2026 there was no such parameter and the answer was always both, ordered by date; because meetings are FUTURE-dated, an endpoint called council-documents opened with next month's summits and read as a calendar.
- `q` — substring search.
- `document_type` — `press_release` / `conclusions` / `meeting_agenda` / etc.
- `policy_area` — single policy area tag.
- `published_from`, `published_to` (and `published_end` alias).
- `updated_from`, `updated_to` (and `updated_end` alias) — incremental sync.
- `limit` (default 50, max 100), `page` (1-indexed).

**Try it**
```
GET /api/v2/council/council-documents?document_type=conclusions&published_from=2026-01-01
GET /api/v2/council/council-documents?policy_area=energy
GET /api/v2/council/council-documents?source=meetings
```

**You get back**
A `PaginatedResponse[CouncilDocumentItem]` envelope. Each item carries reference, title, document_type, policy_area, dates, source URL, and the 5 envelope-level datapoints.

**Data freshness**
Synced every 12 hours (02:00 / 14:00 UTC, warm tier) for now — will move to dedicated 6h scraper once the Council document register scraper ships. Meanwhile, this surface unions data from the publications sync (every 6h) and the calendar sync (every 6h).""",
)
async def list_council_documents(
    request: Request,
    q: Optional[str] = Query(None),
    source: str = Query("documents", pattern="^(documents|meetings|all)$",
                        description="documents (default): the register and press corpus. "
                                    "meetings: Council meetings from the calendar. "
                                    "all: both, as this endpoint used to return by default."),
    document_type: Optional[str] = Query(None, description="press_release | conclusions | meeting_agenda | ..."),
    policy_area: Optional[str] = Query(None),
    published_from: Optional[date] = Query(None),
    published_to: Optional[date] = Query(None),
    published_end: Optional[date] = Query(None),
    updated_from: Optional[datetime] = Query(None),
    updated_to: Optional[UpperBoundDatetime] = Query(None),
    updated_end: Optional[UpperBoundDatetime] = Query(None),
    limit: int = Query(50, ge=1, le=100),
    page: int = Query(1, ge=1),
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilDocumentItem]:
    return await _v1.list_council_documents(request=request, q=q, source=source, document_type=document_type, policy_area=policy_area, published_from=published_from, published_to=published_to, published_end=published_end, updated_from=updated_from, updated_to=updated_to, updated_end=updated_end, limit=limit, page=page, user=user, db=db)


@router.get(
    "/{doc_id}",
    response_model=CouncilDocumentItem,
    summary="One Council document or meeting by id — full body (text + HTML)",
    description="""**What it does**
Fetches a single Council of the EU item by its Brubru-internal UUID — either a Council institutional publication (press release, conclusions) or a Council / European Council meeting from the calendar. Returns the same shape as the list endpoint with the 5 datapoints filled: `public_url`, `body_txt`, `body_html`, `document_date`, `creation_date`.

**When to use it**
After locating an item via the list endpoint, use this to fetch the full record. For publications the body is the stored HTML content (or summary); for meetings the body is composed from the meeting facts (configuration, date, the legislative files on the agenda).

**Input**
- `doc_id` (path) — the Brubru-internal UUID from the list endpoint's `id`.

**Try it**
```
GET /api/v2/council/council-documents/{doc_id}
```

**You get back**
A single `CouncilDocumentItem`, or HTTP 404 with `reason_code: not_found`.

**Data freshness**
Same sources as the list endpoint (publications sync + calendar sync).""",
)
async def get_council_document_detail(
    doc_id: str,
    user: User = Depends(api_user_with_rate_limit),
    db: Session = Depends(get_db),
) -> CouncilDocumentItem:
    return await _v1.get_council_document_detail(doc_id=doc_id, user=user, db=db)


@configurations_router.get(
    "",
    response_model=PaginatedResponse[CouncilConfigurationItem],
    summary="Council of the EU configurations — the 10 ministerial formations (+ Eurogroup)",
    description="""**What it does**
Returns the ten configurations the Council of the EU meets in (General Affairs, Foreign Affairs, ECOFIN, Justice and Home Affairs, EPSCO, Competitiveness, Transport/Telecommunications/Energy, Agriculture and Fisheries, Environment, Education/Youth/Culture/Sport) plus the informal Eurogroup. For each: the official name, the URL-slug, the consilium public-register entity id, the "council-meetings-explained" page, and a deep-link to the calendar filtered to that formation.

**When to use it**
As a reference list to drive a configuration picker, to resolve a configuration code to its full name, or to get the canonical consilium URLs for a formation. Pair with `/api/v2/council/council-documents?` (meetings are tagged with `council_configuration`).

**Input**
No parameters.

**Try it**
```
GET /api/v2/council/council-configurations
```

**You get back**
A `PaginatedResponse[CouncilConfigurationItem]` with one row per configuration: `code`, `name`, `slug`, `register_entity_id`, `consilium_url`, `calendar_filter_url`, `informal`, plus the 5 envelope datapoints (`public_url` = the consilium page, `body_txt`/`body_html` = the description, `document_date` = null, `creation_date` = server time).

**Data freshness**
Static reference data — the Council configurations are fixed by the Council's Rules of Procedure.""",
)
async def list_council_configurations(
    request: Request,
    user: User = Depends(api_user_with_rate_limit),
) -> PaginatedResponse[CouncilConfigurationItem]:
    return await _v1.list_council_configurations(request=request, user=user)
