"""
Permanent Representations of the EU Member States to the EU (Brussels).

Curated registry (hand-mapped from docs/api/api_council.md, 2 June 2026) - the
member states' working level at the Council. Surfaced as a directory panel in
Council Watch. Static + verified URLs only (no scraping). `who` = who's-who /
personnel page; `news` = the mission's news feed where one exists.

Catalonia is included as a sub-national delegation (region=True), not one of the 27.
"""

PERMREPS = [
    {"code": "AT", "name": "Austria", "home": "https://www.bmeia.gv.at/en/oev-bruessel",
     "about": "https://www.bmeia.gv.at/en/oev-bruessel/about-us/what-we-do",
     "who": "https://www.bmeia.gv.at/en/oev-bruessel/about-us/the-permanent-representative"},
    {"code": "BE", "name": "Belgium", "home": "https://europeanunion.diplomatie.belgium.be/en",
     "about": "https://europeanunion.diplomatie.belgium.be/en/over-ons",
     "who": "https://europeanunion.diplomatie.belgium.be/nl/wie-wie",
     "news": "https://europeanunion.diplomatie.belgium.be/nl/nieuws"},
    {"code": "BG", "name": "Bulgaria", "home": "https://mfa.bg/en/embassies/belgiumpp/541",
     "who": "https://mfa.bg/en/embassies/belgiumpp/542",
     "news": "https://mfa.bg/en/embassies/belgiumpp/news"},
    {"code": "HR", "name": "Croatia", "home": "https://mvep.gov.hr/eu/en",
     "who": "https://mvep.gov.hr/permanent-representation/contact-and-working-hours-94378/94378"},
    {"code": "CY", "name": "Cyprus", "home": "https://www.gov.cy/mfa-permrepeu/en/the-permanent-representation/",
     "about": "https://www.gov.cy/mfa-permrepeu/en/the-permanent-representation/about-the-mission/",
     "who": "https://www.gov.cy/mfa-permrepeu/en/the-permanent-representation/personnel/"},
    {"code": "CZ", "name": "Czechia", "home": "https://mzv.gov.cz/representation_brussels/en/index.html",
     "about": "https://mzv.gov.cz/representation_brussels/en/about_the_representation/index.html",
     "who": "https://mzv.gov.cz/representation_brussels/en/about_the_representation/team_at_the_permanent_representation/index.html",
     "news": "https://mzv.gov.cz/representation_brussels/en/news_and_media/index.html"},
    {"code": "DK", "name": "Denmark", "home": "https://um.dk/eu/en",
     "about": "https://um.dk/eu/en/about-us/",
     "who": "https://um.dk/eu/en/about-us/staff-members/"},
    {"code": "EE", "name": "Estonia", "home": "https://eu.mfa.ee/",
     "who": "https://eu.mfa.ee/personnel/"},
    {"code": "FI", "name": "Finland", "home": "https://finlandabroad.fi/web/eu/frontpage",
     "who": "https://finlandabroad.fi/web/eu/personnel",
     "news": "https://finlandabroad.fi/web/eu/current-affairs"},
    {"code": "FR", "name": "France", "home": "https://ue.diplomatie.gouv.fr/",
     "about": "https://ue.diplomatie.gouv.fr/representation-permanente-de-la-france-aupres-de-lunion-europeenne"},
    {"code": "DE", "name": "Germany", "home": "https://bruessel-eu.diplo.de/eu-en",
     "about": "https://bruessel-eu.diplo.de/eu-en/permanentrepresentation",
     "news": "https://bruessel-eu.diplo.de/eu-en/permanentrepresentation/press-1506098"},
    {"code": "EL", "name": "Greece", "home": "https://www.mfa.gr/brussels/en/permanent-representation-eu/",
     "who": "https://www.mfa.gr/brussels/en/permanent-representation-eu/about-us/permanent-representative.html",
     "news": "https://www.mfa.gr/brussels/en/permanent-representation-eu/news"},
    {"code": "HU", "name": "Hungary", "home": "https://eu-brusszel.mfa.gov.hu/en/bemutatkozas",
     "who": "https://eu-brusszel.mfa.gov.hu/en/munkatarsak",
     "news": "https://eu-brusszel.mfa.gov.hu/en/articles"},
    {"code": "IE", "name": "Ireland", "home": "https://www.ireland.ie/en/eu/brussels/",
     "news": "https://www.ireland.ie/en/eu/brussels/news-and-events/"},
    {"code": "IT", "name": "Italy", "home": "https://italiaue.esteri.it/en/litalia-e-lue/cosa-facciamo/",
     "who": "https://italiaue.esteri.it/en/chi-siamo/il-rappresentante-permanente/",
     "news": "https://italiaue.esteri.it/en/news/"},
    {"code": "LV", "name": "Latvia", "home": "https://www2.mfa.gov.lv/en/brussels",
     "who": "https://www2.mfa.gov.lv/en/brussels/representatives",
     "news": "https://www2.mfa.gov.lv/en/brussels/news"},
    {"code": "LT", "name": "Lithuania", "home": "https://eu.mfa.lt/en",
     "about": "https://eu.mfa.lt/en/about-us/47",
     "who": "https://eu.mfa.lt/en/about-us/permanent-representation/representatives-and-attaches/51",
     "news": "https://eu.mfa.lt/en/news/45"},
    {"code": "LU", "name": "Luxembourg", "home": "https://bruxelles-rpue.mae.lu/en/ambassades.html"},
    {"code": "MT", "name": "Malta", "home": "https://missions.foreign.gov.mt/permanent-representations/european-union/",
     "who": "https://missions.foreign.gov.mt/permanent-representations/european-union/preu-staff-list/",
     "news": "https://missions.foreign.gov.mt/permanent-representations/european-union/news/"},
    {"code": "NL", "name": "Netherlands", "home": "https://www.netherlandsandyou.nl/web/pr-eu-brussels",
     "about": "https://www.netherlandsandyou.nl/web/pr-eu-brussels/about-us",
     "who": "https://www.netherlandsandyou.nl/web/pr-eu-brussels/about-us/permanent-representative"},
    {"code": "PL", "name": "Poland", "home": "https://www.gov.pl/web/eu/permanent-representation",
     "who": "https://www.gov.pl/web/eu/permanent-representative"},
    {"code": "PT", "name": "Portugal", "home": "https://ue.missaoportugal.mne.gov.pt/en/",
     "who": "https://ue.missaoportugal.mne.gov.pt/en/permanent-representation/who-s-who",
     "news": "https://ue.missaoportugal.mne.gov.pt/en/permanent-representation/news"},
    {"code": "RO", "name": "Romania", "home": "https://ue.mae.ro/en/node/436",
     "news": "https://ue.mae.ro/en/local-news"},
    {"code": "SK", "name": "Slovakia", "home": "https://www.mzv.sk/szbrusel-en",
     "about": "https://www.mzv.sk/en/web/szbrusel-en/about-us/our-mission",
     "who": "https://www.mzv.sk/en/web/szbrusel-en/about-us/our-representatives"},
    {"code": "SI", "name": "Slovenia",
     "home": "https://www.gov.si/en/representations/permanent-representation-to-the-european-union-brussels/about-the-permanent-representation-to-the-european-union-brussels/"},
    {"code": "ES", "name": "Spain", "home": "https://en.es-ue.org/",
     "about": "https://en.es-ue.org/quienes-somos/",
     "who": "https://en.es-ue.org/directorio/",
     "news": "https://en.es-ue.org/sala-de-prensa/"},
    {"code": "SE", "name": "Sweden", "home": "https://www.government.se/sweden-in-the-eu/permanent-representation-of-sweden-to-the-eu/",
     "about": "https://www.government.se/sweden-in-the-eu/permanent-representation-of-sweden-to-the-eu/about/",
     "who": "https://www.government.se/sweden-in-the-eu/permanent-representation-of-sweden-to-the-eu/management/"},
    # Sub-national delegation (not one of the 27 member states)
    {"code": "CAT", "name": "Catalonia (Generalitat)", "region": True,
     "home": "https://exteriors.gencat.cat/en/ambits-dactuacio/afers_exteriors/delegacions_govern/ue/delegacio/index.html"},
]
