"""European Council domain — /api/v2/european-council/euco-conclusions/* and /api/v2/european-council/euco-meetings/* and /api/v2/european-council/euco-euro-summit/* and /api/v2/european-council/euco-strategic-agenda/* and /api/v2/european-council/euco-members/* and /api/v2/european-council/euco-about/*.

LIVE — copy-pasted verbatim from the v1 surface (api.v1.european_council); the body
delegates to the v1 handlers so there is exactly one implementation during the
v1+v2 coexistence period. Summaries, descriptions and signatures are identical
to v1; only the in-description example URLs are rehomed to /api/v2/european-council/*.

Generated by scripts/_gen_v2_consilium_folders.py — do not hand-edit; regenerate.
"""
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request  # noqa: F401
from sqlalchemy.orm import Session  # noqa: F401

from core.database import get_db  # noqa: F401
from models.user import User  # noqa: F401
from api.v1._deps import api_user_with_rate_limit  # noqa: F401
from api.v1._envelope import PaginatedResponse  # noqa: F401
from api.v1 import european_council as _v1
from api.v1.european_council import *  # noqa: F401,F403 - reproduce v1's exact namespace for get_type_hints


from api.v1.european_council import _DESC, _params  # noqa: F401 - used in decorators

conclusions_router = APIRouter(prefix="/euco-conclusions", tags=["v2-euco-conclusions"])
meetings_router = APIRouter(prefix="/euco-meetings", tags=["v2-euco-meetings"])
euro_summit_router = APIRouter(prefix="/euco-euro-summit", tags=["v2-euco-euro-summit"])
strategic_agenda_router = APIRouter(prefix="/euco-strategic-agenda", tags=["v2-euco-strategic-agenda"])
members_router = APIRouter(prefix="/euco-members", tags=["v2-euco-members"])
about_router = APIRouter(prefix="/euco-about", tags=["v2-euco-about"])


@conclusions_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="European Council conclusions — the conclusions register (2004-present)",
    description=_DESC(
        "Returns European Council conclusions from the conclusions register — the formal political guidance adopted by the EU heads of state or government at their summits, each with date, document number and a link to the PDF.",
        "To read the most authoritative signal of EU political direction — European Council conclusions set the strategic agenda that Commission proposals and Council decisions follow.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of conclusions documents.",
        "GET /api/v2/european-council/euco-conclusions?published_from=2025-01-01",
    ),
)
async def list_euco_conclusions(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_euco_conclusions(request=request, params=params, user=user, db=db)


@conclusions_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One European Council conclusions document by id — full body",
    description="Fetch a single European Council conclusions document by its Brubru UUID. Returns the five datapoints. 404 with `reason_code: not_found` if absent.",
)
async def get_euco_conclusion(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_euco_conclusion(item_id=item_id, user=user, db=db)


@meetings_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="European Council meetings — summit meetings of EU leaders",
    description=_DESC(
        "Returns European Council summit meetings (the gatherings of EU heads of state or government), with date and a body composed from the meeting facts plus the published outcomes where available.",
        "To track the European Council summit calendar and outcomes — the apex political meetings of the EU.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of summit meetings.",
        "GET /api/v2/european-council/euco-meetings",
    ),
)
async def list_euco_meetings(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_euco_meetings(request=request, params=params, user=user, db=db)


@meetings_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One European Council meeting by id — full body",
    description="Fetch a single European Council meeting by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_euco_meeting(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_euco_meeting(item_id=item_id, user=user, db=db)


@euro_summit_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Euro Summit — heads of state or government of the euro area",
    description=_DESC(
        "Returns the Euro Summit reference — the meeting format that brings together the heads of state or government of the euro-area countries to discuss euro-area governance (distinct from the Eurogroup, which is finance ministers).",
        "To understand the Euro Summit's role and find its meeting calendar — the leaders'-level forum for the euro area.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` with the Euro Summit entry.",
        "GET /api/v2/european-council/euco-euro-summit",
    ),
)
async def list_euco_euro_summit(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_euco_euro_summit(request=request, params=params, user=user, db=db)


@euro_summit_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Euro Summit entry by id — full body",
    description="Fetch a single Euro Summit entry by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_euco_euro_summit(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_euco_euro_summit(item_id=item_id, user=user, db=db)


@strategic_agenda_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="European Council Strategic Agenda 2024-2029",
    description=_DESC(
        "Returns the European Council's Strategic Agenda 2024-2029 — the five-year political priorities agreed by EU leaders that frame the whole institutional cycle — with the agenda text and a link to the full PDF.",
        "To ground any analysis in the EU's top-level political priorities for the 2024-2029 cycle.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` with the Strategic Agenda entry.",
        "GET /api/v2/european-council/euco-strategic-agenda",
    ),
)
async def list_euco_strategic_agenda(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_euco_strategic_agenda(request=request, params=params, user=user, db=db)


@strategic_agenda_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One Strategic Agenda entry by id — full body",
    description="Fetch the Strategic Agenda entry by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_euco_strategic_agenda(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_euco_strategic_agenda(item_id=item_id, user=user, db=db)


@members_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="Members of the European Council",
    description=_DESC(
        "Returns the members of the European Council — the EU heads of state or government, plus the President of the European Council and the President of the European Commission — as a reference entry with the membership listing.",
        "As a reference for who sits on the European Council.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` with the members entry.",
        "GET /api/v2/european-council/euco-members",
    ),
)
async def list_euco_members(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_euco_members(request=request, params=params, user=user, db=db)


@members_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One European Council members entry by id — full body",
    description="Fetch the European Council members entry by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_euco_member(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_euco_member(item_id=item_id, user=user, db=db)


@about_router.get(
    "",
    response_model=PaginatedResponse[CouncilRegisterItemModel],
    summary="About the European Council — how it works, president, role, history",
    description=_DESC(
        "Returns institutional reference pages about the European Council — how it works, the President of the European Council, the role/nominations/appointment process, and its history — each with the page text as body.",
        "As background reference on the European Council as an institution.",
        "A `PaginatedResponse[CouncilRegisterItemModel]` of reference entries.",
        "GET /api/v2/european-council/euco-about",
    ),
)
async def list_euco_about(
    request: Request, params: dict = Depends(_params),
    user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> PaginatedResponse[CouncilRegisterItemModel]:
    return await _v1.list_euco_about(request=request, params=params, user=user, db=db)


@about_router.get(
    "/{item_id}",
    response_model=CouncilRegisterItemModel,
    summary="One European Council reference page by id — full body",
    description="Fetch a single European Council reference page by its Brubru UUID. Returns the five datapoints. 404 if absent.",
)
async def get_euco_about(
    item_id: str, user: User = Depends(api_user_with_rate_limit), db: Session = Depends(get_db),
) -> CouncilRegisterItemModel:
    return await _v1.get_euco_about(item_id=item_id, user=user, db=db)
